### ISSUE TITLE
Tide memory management 

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#114]
1. Tide-index allocates too much memory for patterns of modifications
2. Tide-search loads all the index file at the beginning. check why!
3. Tide-index uses to much memory to generate non-modified peptides. (see 148)

Reported by: wsnoble

**Comment by wsnoble** [comment]
This is related to the memory issue that Kaipo has been working on recently, so I am switching to assign it to him.
