### ISSUE TITLE
Add Bibliospec to Crux

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#169]
Bibliospec is already part of ProteoWizard.  We just need to enable the commands in Crux.

First step is to write the HTML spec, which is why I'm assigning this task to myself.

Reported by: wsnoble

**Comment by wsnoble** [comment]
Doing this will require making the Crux distribution much larger, due to the way that Bibliospec is implemented within Skyline. So let's not do this after all.
