### ISSUE TITLE
invalid vector t subscript with spectral counts

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#171]
I am trying to obtain both NSAF and dNSAF values from an experiment originally run in scaffold.  I have tried exporting files to both pepxml format and mzid format and then run crux spectral-counts.  When running pepxml, I have specified the protein fasta file database.  With mzid, I have not.  Either way I have tried running the program I get an initial set of errors stating "No sequence found..." followed by info:number of matches 309393  Info:number of matches passed the threshold 309393  "FATAL: An exception occurred: invalid vector[t] subscript".  I am guessing that I have not done some required step, but I was unable to find any information on this in the tutorial or in the previous issues.  Thank you for your help.  

Reported by: cpmorris

**Comment by wsnoble** [comment]
User never provided input files.  Closing this one.
