### ISSUE TITLE
Rename header files

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#20]
To add to this point, one error I dealt with when I started integrating Tide was because Crux's Peptide.h and Tide's peptide.h both had the same include guard ("#ifndef PEPTIDE_H \ #define PEPTIDE_H").
I don't think renaming conflicting header files would be a bad idea, but probably doesn't need to be done right away.

I'd say the patch is good to check in but Charles mentioned that he was going to take a look at it as well, so you may or may not want to wait on that.

Thanks,
Kaipo

On 9/11/2013 8:31 AM, William S Noble wrote:
To me, renaming the header files makes a lot of sense.  It seems like having two files with exactly the same name and different content is bound to lead to confusion.

Bill

On Wed, Sep 11, 2013 at 8:19 AM, Sean McIlwain sjoemac@gmail.com wrote:
Kaipo,

This issue arises in our Spectrum.h because there is also a Spectrum.h in the MSToolkit library.  So to include the Spectrum.h header from Comet into the Spectrum.h file in Crux, we have to specify a exact path.  Other than renaming our header files to something like CruxSpectrum.h I don't see another way around this.

Thanks,
Sean

Reported by: wsnoble

**Comment by wsnoble** [comment]
Charles, can you check on the status of this issue?

**Comment by CharlesEGrant** [comment]
This has mostly been fixed by specifying a partial path for the appropriate Spectrum.h file:

#include "model/Spectrum.h"
vs
#include "MSToolkit/Spectrum.h"

However there are a couple of instances of 

#include "Spectrum.h" remaining. Though currently working correctly this is ambiguous and should be brought into line with the others. 10 minutes to make the changes, and hour to test the build after the change.

**Comment by wsnoble** [comment]
Please go ahead and make this change.

**Comment by CharlesEGrant** [comment]
Change completed in edit bc0e82e866e3f610d5e4560460fe9f5b6f105703
