### ISSUE TITLE
Make assign-confidence capable of parsing search-for-xlinks output files

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#269]
The attached output file shows the seg fault that arises when I run assign-confidence on a search-for-xlinks output file. Besides fixing this seg fault, the program needs to automatically detect the presence of the "p-value" column, and use that as the score (with smaller-is-better=T), and handle additional columns like eta, beta, etc.

Reported by: wsnoble

**Comment by wsnoble** [comment]
Search-for-xlinks is no longer in crux.
