### ISSUE TITLE
Implement Waltzthoeni approach to cross-link FDR estimation

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#278]
The article describing this approach is attached.  The key is Equation (10).

Basically, we should have two decoy databases that are the same size as the target.  In one of the decoys, both peptides are shuffled.  In the other, only a single peptide is shuffled.  Then if we set a score threshold, the estimated number of false positives is given by Equation (10): it's the total number of decoys above the threshold minus twice the number of D-D decoys above the threshold.  If you take this value and divide by the total number of targets above the threshold, then you get the FDR.  Importantly, though, this calculation has to be done separately for each kind of identification.  For this purpose, I would be inclined to lump together the linear, selfloop and dead-end matches, and then treat the inters as one category and inter+inter-intra as another category.

I don't know if you want to try to implement this confidence estimation procedure within search-for-xlinks or put it into the assign-confidence command.  I can see an argument for either approach.

Reported by: wsnoble

**Comment by fcyu** [comment]
> Currently,
the new sfx runs the search separately with a target peptide and decoy
peptide database to generate a list for TT and FF. 

Now, I found the reason why search-for-xlinks always report more PSMs than other tools including Kojak and pLink.

Could you please tell me when such fix can be done? I have to wait for it.

Thanks,

Fengchao

**Comment by wsnoble** [comment]
Hi Fengchao,

If you use use-old-xlinks=F with search-for-xlinks, then the option
concat=T is available.  When you set this parameter, the targets and decoys
will compete against each other and get reported in a single file
(search-for-xlinks.txt). You can control how many matches are reported per
spectrum via the top-match parameter.

Currently, the documentation does not indicate that concat is available
with search-for-xlinks. We will fix this.

Thanks.
Bill

**Comment by wsnoble** [comment]
Here is a Python implementation.


[compute-xlink-qvalue.txt](https://github.com/crux-toolkit/crux-toolkit/files/905155/compute-xlink-qvalue.txt)

**Comment by animesh** [comment]
Got it, thanks :)

**Comment by animesh** [comment]
The USAGE part mentions to run the search with --concat=T and --top-match=1 , however when i try to run with these switches, program throws following message:

````
c:\Users\PROMECuser\data\crux-3.1.Windows.AMD64>bin\crux.exe  search-for-xlinks --use-old-xlink F --concat=T and --top-match=1  170317_ung_ctr.raw uniprot-UNGxLink.fasta K,nterm:K,nterm 138.0680742
FATAL: Expected 4 arguments, but found 3

USAGE:

  crux search-for-xlinks [options] <ms2 file> <protein fasta file> <link sites> <link mass>

Run "crux search-for-xlinks" with no arguments to see a full list of options.
````

Any ideas on how to proceed?

**Comment by thabangh** [comment]
Delete the word "and" from your command line.

**Comment by sjoemac** [comment]
Also delete the =

**Comment by animesh** [comment]
Thanks @sjoemac and @thabangh , combining those tips worked 👍 Wondering if it is possible to provide multiple raw files within one command line and how would it affect the final FDR calculations?

**Comment by thabangh** [comment]
You should be able to simply add the names of additional raw files to your
command. The FDR estimation can be done jointly on the resulting PSMs.

Bill

**Comment by animesh** [comment]
Tried to append another file name after the first raw file, however program failed to run, but following

````
c:\Users\PROMECuser\data\crux-3.1.Windows.AMD64>bin\crux.exe  search-for-xlinks --use-old-xlink F --concat T  --top-match 1   --input-ms2  170317_ung_bs3.raw 170317_ung_ctr.raw uniprot-UNGxLink.fasta K,nterm:K,nterm 138.0680742 --overwrite
````
seems to work, however it seems to run search just for the *ctr* file only which it calls index 0... probably there is a different switch to include multiple files which i am not aware of? 

Also, is there a way to supply multiple raw file using wildcard?

**Comment by sjoemac** [comment]
Ani,

Multiple spectra files are currently not supported in search-for-xlinks.
Tide-search support multiple spectra files and we could transfer this
approach to search-for-xlinks, but I'm not sure if wildcards are supported
by this method.

Thanks,
Sean

**Comment by animesh** [comment]
Thanks Sean for information, looking forward to the update supporting multiple files then 👍

**Comment by sjoemac** [comment]
Ani,

The latest development version of crux should now support multiple spectrum
files using sfx with --use-old-xlink F.  I don't believe wildcards are
supported however.

http://crux.ms/download.html

your command line would look like this:

c:\Users\PROMECuser\data\crux-3.1.Windows.AMD64>bin\crux.exe
search-for-xlinks --overwrite T --use-old-xlink F --concat T
--top-match 1 170317_ung_bs3.raw 170317_ung_ctr.raw
uniprot-UNGxLink.fasta K,nterm:K,nterm 138.0680742


You don't need --input-ms2, that is an option for barista/q-ranker and is
not used by sfx.

Thanks,
Sean

**Comment by animesh** [comment]
Thanks Sean :+1:  However the program complains for extra argument:

````
F:\promec\crux-3.1.Windows.AMD64\bin>crux.exe search-for-xlinks --overwrite T --
use-old-xlink F --concat T --top-match 1 170317_ung_bs3.raw 170317_ung_ctr.raw u
niprot-UNGxLink.fasta K,nterm:K,nterm 138.0680742
FATAL: Expected 4 arguments, but found 5

USAGE:

  crux search-for-xlinks [options] <ms2 file> <protein fasta file> <link sites>
<link mass>

Run "crux search-for-xlinks" with no arguments to see a full list of options.
`````
The date stamp on the crux.exe is 18th April, probably it is just that the download link is not updated?

**Comment by CharlesEGrant** [comment]
Hi Ani,

There was an issue with our build server last week. The downloads were not being uploaded. This has been resolved, and the latest version is now being delivered from the download link for the most recent build.

**Comment by animesh** [comment]
Thanks @CharlesEGrant for quick information. I have downloaded the latest one and it seems to run again just for one file. When second raw file is provided, it crashed with following message:

````
FATAL: Unable to parse spectrum file F:\promec\crux-3.1.Windows.AMD64\bin\170317_ung_ctr.raw. Error: [ThermoRawFile] [ScanInfoImpl::initialize(), GetFilterForScanNum()] Failed call to XRawfile: The handle is invalid..
````

**Comment by sjoemac** [comment]
Ani,

Could you try and run sfx with a set of files of different format from RAW
(e.g., ms2 or mzXML)?  It might help us to localize where in the code the
failure occurs.

Thanks,
Sean

**Comment by animesh** [comment]
@sjoemac MGF formats goes fine it seems though number of identifications for two files is less than single raw file. I suspect it is because of filtering during conversion with msconvert? 
[search-for-xlinks.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/971031/search-for-xlinks.log.txt)

**Comment by sjoemac** [comment]
Ani,

A couple of questions occurs to me, could you try running the two raw files
through tide-search? Any chance you could send me the two raw files, the
fasta, and the command line you are using?

Thanks,
Sean

**Comment by animesh** [comment]
Sure @sjoemac tried the tide-serach which throws following exception:
````
INFO: Converting 170317_ung_bs3.raw to spectrumrecords format
INFO: Elapsed time starting conversion: 0.053 s
INFO: Converting 170317_ung_ctr.raw to spectrumrecords format
INFO: Elapsed time starting conversion: 118 s
FATAL: Unable to parse spectrum file F:\GDrive\crux-3.1.Windows.AMD64\bin\170317
_ung_ctr.raw. Error: [ThermoRawFile] [ScanInfoImpl::initialize(), GetFilterForSc
anNum()] Failed call to XRawfile: The handle is invalid..
````
I am also sharing the whole folder of crux https://drive.google.com/drive/folders/0Bxu2c26vracJMG9QMUtDdVlFSzQ?usp=sharing where in the bin directory you can find all the relevant files. The command line i am using is:
````
F:\promec>crux.exe search-for-xlinks --overwrite T --use-old-xlink F --concat T
--top-match 1 170317_ung_bs3.raw uniprot-UNGxLink.fasta K,nterm:K,nterm 138.0680
742
````
Looking forward to the solution :+1:

**Comment by CharlesEGrant** [comment]
Ani, it looks like the problem is not with search-for-xlinks' handling of multiple spectra files, but with the file 170317_ung_ctr.raw specifically.  I tried running search-for-xlinks on 170317_ung_bs3.raw  and another RAW file I had to hand, and Crux was able to correctly process multiple spectra files.

I was unable to get crux to read 170317_ung_ctr.raw even by itself. I also tried to read it with Proteowizard's '[msconvert](http://proteowizard.sourceforge.net/tools.shtml)' utility and [RawConverter](http://fields.scripps.edu/rawconv/), and neither of them could read 170317_ung_ctr.raw. These tools are all using Thermo MSFileReader library. There could be a bug in that library, but since it's Thermo's proprietary format, and other files are read correctly, my suspicion is that something happened to corrupt 170317_ung_ctr.raw.

**Comment by animesh** [comment]
@CharlesEGrant , thanks and sorry for the trouble. Yes it turned out that file was not properly copied although the size was same! I redid and it works :+1: 

````
 F:\GDrive\crux-3.1.Windows.AMD64\bin>crux search-for-xlinks --overwrite T --use-
old-xlink F --concat T --top-match 1 170317_ung_bs3.raw 170317_ung_ctr.raw unipr
ot-UNGxLink.fasta K,nterm:K,nterm 138.0680742
AMOD: mass 57.02, max per 0, max dist 40000, symb *, aa list C
INFO: Beginning search-for-xlinks.
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
INFO: CPU: PROMEC01
INFO: Crux version: 3.1
INFO: Fri 05/19/2017
INFO: Beginning crux search-for-xlinks.
INFO: Preparing database.
INFO: Initializing database
INFO: Preparing protein fasta file uniprot-UNGxLink.fasta
INFO: Created 1 peptide mods, keeping 1 with 255 or fewer aa mods
INFO: Missed cleavages from user:0
INFO: Blocked cleavages from xlink/selfloops:2
INFO: Blocked cleavages from mods/mono-links:0
INFO: Total missed cleavages to consider:2
INFO: Modification 1 has delta mass of 0 Da.
INFO: Considered linear 419 peptides, of which 217 were included in the database
.
INFO:   The database contains 104 linear peptides.
INFO:   The database contains 0 mono-link peptides.
INFO:   The database contains 45 selfloop peptides.
INFO:   The database contains 83 cross-linkable peptides.
INFO: Done initializing database
INFO: Loading spectra 170317_ung_bs3.raw.
INFO: Beginning search.
INFO: Assigning index 0 to 170317_ung_bs3.raw.
INFO: 1000 spectrum-charge combinations searched, 7% complete
INFO: 2000 spectrum-charge combinations searched, 13% complete
INFO: 3000 spectrum-charge combinations searched, 20% complete
INFO: 4000 spectrum-charge combinations searched, 26% complete
INFO: 5000 spectrum-charge combinations searched, 33% complete
INFO: 6000 spectrum-charge combinations searched, 40% complete
INFO: 7000 spectrum-charge combinations searched, 46% complete
INFO: 8000 spectrum-charge combinations searched, 53% complete
INFO: 9000 spectrum-charge combinations searched, 60% complete
INFO: 10000 spectrum-charge combinations searched, 66% complete
INFO: 11000 spectrum-charge combinations searched, 73% complete
INFO: 12000 spectrum-charge combinations searched, 79% complete
INFO: 13000 spectrum-charge combinations searched, 86% complete
INFO: 14000 spectrum-charge combinations searched, 93% complete
INFO: 15000 spectrum-charge combinations searched, 99% complete
INFO: Skipped 3542 (23.429%) spectra with 0 candidates.
INFO: Skipped 0 (0%) spectra with too few peaks.
INFO: Loading spectra 170317_ung_ctr.raw.
INFO: Beginning search.
INFO: Assigning index 1 to 170317_ung_ctr.raw.
INFO: 1000 spectrum-charge combinations searched, 6% complete
INFO: 2000 spectrum-charge combinations searched, 12% complete
INFO: 3000 spectrum-charge combinations searched, 18% complete
INFO: 4000 spectrum-charge combinations searched, 23% complete
INFO: 5000 spectrum-charge combinations searched, 29% complete
INFO: 6000 spectrum-charge combinations searched, 35% complete
INFO: 7000 spectrum-charge combinations searched, 41% complete
INFO: 8000 spectrum-charge combinations searched, 47% complete
INFO: 9000 spectrum-charge combinations searched, 53% complete
INFO: 10000 spectrum-charge combinations searched, 58% complete
INFO: 11000 spectrum-charge combinations searched, 64% complete
INFO: 12000 spectrum-charge combinations searched, 70% complete
INFO: 13000 spectrum-charge combinations searched, 76% complete
INFO: 14000 spectrum-charge combinations searched, 82% complete
INFO: 15000 spectrum-charge combinations searched, 88% complete
INFO: 16000 spectrum-charge combinations searched, 93% complete
INFO: 17000 spectrum-charge combinations searched, 99% complete
INFO: Skipped 4955 (28.9073%) spectra with 0 candidates.
INFO: Skipped 0 (0%) spectra with too few peaks.
INFO: Start to finalize database
INFO: Done finalizing database
INFO: Elapsed time: 441 s
INFO: Finished crux search-for-xlinks.
INFO: Return Code:0

F:\GDrive\crux-3.1.Windows.AMD64\bin>
```

**Comment by wsnoble** [comment]
Search-for-xlinks is no longer in crux.
