### ISSUE TITLE
Percolator got worse

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#281]
I just re-ran the performance test, and I noticed that the curve correpsonding to Percolator with tide p-values got noticeably worse. I will attach the two files showing the old results and the new results. As far as I can tell, all the other methods are performing the same, but the cyan "Tide p-value Percolator" line has dropped considerably. We need to track down what change caused this decline.

Reported by: wsnoble

**Comment by wsnoble** [comment]
This is very old and likely irrelevant by now. Closing out.
