### ISSUE TITLE
Add support for mzTab format

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#300]
http://www.psidev.info/mztab

http://www.ncbi.nlm.nih.gov/pubmed/24980485

Reported by: wsnoble

**Comment by wsnoble** [comment]
FYI, here is a sample mzTab file for Casanovo.

[casanovo.txt](https://github.com/crux-toolkit/crux-toolkit/files/9333752/casanovo.txt)

**Comment by kfattila** [comment]
@wsnoble, The mzTab format seems to be somewhat relaxed. we should specify columns and parameters to be included to this format.

**Comment by wsnoble** [comment]
I think we should include the same columns that we currently do, except eliminate the "cleavage type" one. We should also add a new link to [this page](http://crux.ms/fileformats.html) describing the format.

As for parameters, you can just include the ones that are in the usage statement, though without those related to I/O.

**Comment by kfattila** [comment]
This has been added with tide-lite PR.
