### ISSUE TITLE
sort-by-column bug

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#301]
When I try to sort a very large file, I get an error message saying that the column I want to sort on does not exist.  I can extract the beginning of that same file and sort it just fine. I suspect it is exceeding some memory or hard-coded limit somewhere with the large file size.
- /net/noble/vol1/home/noble/proj/crux/trunk/release/src/crux sort-by-column --column-type real unsorted-decoys.txt 'exact p-value'
  INFO: Beginning sort-by-column.
  FATAL: column exact p-value doesn't exist
- head -10 unsorted-decoys.txt
- /net/noble/vol1/home/noble/proj/crux/trunk/release/src/crux sort-by-column --column-type real head.txt 'exact p-value'
  INFO: Beginning sort-by-column.
  INFO: Elapsed time: 0.00123 s
  INFO: Finished crux sort-by-column.
  INFO: Return Code:0

The file is too large to attach, but it can be found at 

http://noble.gs.washington.edu/~wnoble/proj/malaria/2015orfs/results/bill/2016-01-08jeff-questions/sort-bug/unsorted-decoys.txt.gz

Reported by: wsnoble

**Comment by wsnoble** [comment]
I ran into this bug again later and asked Kaipo about it. Here is what he said: "I think we ran into this before - I don't really know too much about how that command works but it looks like it sorts and creates temporary files every 200,000 lines. This limit is hardcoded and when I increased it to a value more than the number of rows in the file (1,062,519) it works fine."

**Comment by wsnoble** [comment]
We are removing this command from crux.
