### ISSUE TITLE
Create Crux build without vendor libraries

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#313]
Reported by: wsnoble

**Comment by CharlesEGrant** [comment]
The vendor libraries are only included in the Windows build. We currently support a CMAKE flag to build without the vendor libraries: INCLUDE_VENDOR_LIBRARIES. This defaults to true, but can be set to false on the CMake command line. Currently TeamCity only builds Windows with the Vendor libraries. It would take about an hour to also include a Windows build without vendor libraries in TeamCity and the download web site. Do we still want to do this?

**Comment by wsnoble** [comment]
It seems to me that this was motivated by someone requesting this. Do you know who that was? If we can't remember who it was, then I think we should just close this out.

**Comment by CharlesEGrant** [comment]
This was the original request was from Jarrett Egerson (see below). I'm not sure if the request is still relevant, or if he was satisfied with the cmake command line option.

> Hi all,
> 
>    Kaipo -- thanks for putting us in touch.  Charles and Bill -- thanks in advance for your help.  If it isn't too much to ask, in addition, we would love a percolator only build.  This is for Brian's project which is currently distributed as a java .jar file with percolator executables for the 3 major OS's built in.  Because the project would bundle the 3 crux executables, we are a bit sensitive to the executable size.  We prefer to use crux percolator because we know we won't have to worry about building it ourselves (the new percolator has no mac executable), and we trust the file input / output and default parameters to not change as often as it does with Percolator.  We also use crux-percolator for our DDA pipeline, so it makes sense for us to stick with what works.
> 
> -Jarrett
>

**Comment by CharlesEGrant** [comment]
The latest word from Jarrett is that is would have been useful, but he personally doesn't have any need for it now.

> It's great to hear from you. I wouldn't personally find use for this at this point. It would have been handy for Brian Searle at the time to use with his EncyclopeDIA software tool, but I suspect by now he's got a workaround that he's happy with. I'm sure Mike can comment further.

Mike McCoss thought that Brian Searle mind find it useful, but wasn't sure. I'm sending email to Brian to check.

**Comment by wsnoble** [comment]
The MacCoss lab said they no longer need this.
