### ISSUE TITLE
Seg fault from make-pin

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#326]
Kaipo, 
Would you please take a look at this seg fault from make-pin?  The command line is simply

crux make-pin search-for-xlinks.target.txt 

The input files and the log file are attached. The backtrace from the seg fault looks like this:

(gdb) bt
#0  0x00000000006ed51e in get_aa_mod_from_mass(float) ()
#1  0x00000000006ed7d8 in get_aa_mod_from_mass(float) ()
#2  0x00000000006eda93 in convert_to_mod_aa_seq(char const_, unsigned short_*, MASS_FORMAT_T) ()
#3  0x00000000006d66e7 in MatchFileReader::parsePeptide() ()
#4  0x00000000006d7598 in MatchFileReader::parseMatch() ()
#5  0x00000000006d8a10 in MatchFileReader::parse() ()
#6  0x00000000006d8cb3 in MatchFileReader::parse(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Database_, Database_) ()
#7  0x00000000006e1df3 in MatchCollectionParser::create(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x00000000006cd8d0 in MakePinApplication::main(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#9  0x00000000006ce961 in MakePinApplication::main(int, char**) ()
#10 0x00000000006b036a in CruxApplicationList::main(int, char**) ()
#11 0x00000000005a5de9 in main ()

(gdb) 

Reported by: wsnoble

**Comment by wsnoble** [comment]
Charles, can you dig up the original file that I attached to this bug report (back when we were using the old issue handler)? I'd like to check whether this problem still exists.

**Comment by CharlesEGrant** [comment]
Here are the files that were uploaded for this bug in the SourceForge bug tracker for Crux
[make-pin.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/1258984/make-pin.log.txt)
[search-for-xlinks.decoy.txt](https://github.com/crux-toolkit/crux-toolkit/files/1258983/search-for-xlinks.decoy.txt)
[search-for-xlinks.target.txt](https://github.com/crux-toolkit/crux-toolkit/files/1258982/search-for-xlinks.target.txt)

**Comment by wsnoble** [comment]
OK, I have verified that this problem still exists.  Basically, make-pin does not work for files created by search-for-xlinks because the peptides look weird. Kaipo, is this an easy thing to fix?
