### ISSUE TITLE
Add --require-xlink-candidate flag to search-for-xlinks

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#330]
This flag will skip spectra that don't have any cross-linked candidates, even if they have non-cross-linked candidates.  It would be good to print an INFO line indicating how many spectra were skipped due to this flag.

Reported by: wsnoble

**Comment by wsnoble** [comment]
Sean, it looks like this is done. Can I (or you) resolve this issue?
