### ISSUE TITLE
Enable pepXML output from search-for-xlinks

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#339]
Kaipo,

Mike H (cc'd) has a poster at the Cascadia Symposium about extending PepXML to handle crosslinks. He said he would send you a copy of the preliminary schema. Can you look into this and comment on how difficult it would be to make search-for-xlinks produce pepXML?

Thanks!

Bill

---

Hi Bill,

I'm not as familiar with search-for-xlinks output, but I don't see any major obstacles. My thoughts are that we would just extend our objects with the additional fields they need, our tab-delimited parser to read in the fields, and the pepXML writer to format and write out those fields. Then we can read in the tab-delimited output and write it out as pepXML, like with psm-convert. Sean can correct me if I am missing something obvious though.

Thanks,
Kaipo

Reported by: wsnoble

**Comment by wsnoble** [comment]
Search-for-xlinks is no longer in crux.
