### ISSUE TITLE
Percolator seg fault during final conversion

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#340]
The percolator command given below runs to near-completion but seg faults during the final conversion step. I can run the stand-alone Percolator command on this same input file, and it works fine.

./crux percolator --overwrite T --output-dir ribo search-for-xlinks.pin.tsv

~/proj/crux/trunk/ext/bin/percolator -r ribo/percolator.target.peptides.txt -v 2 -P decoy_ --seed 1 -p 0.01 -n 0 --trainFDR 0.01 --testFDR 0.01 --maxiter 10 -s search-for-xlinks.pin.tsv

Reported by: wsnoble

**Comment by wsnoble** [comment]
We no longer have a final conversion step, because Percolator handles its own output.
