### ISSUE TITLE
search-for-xlinks does not handle ties properly in computing delta_cn

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#344]
When search-for-xlinks enocunters a tie in XCorr score, it reports both matches. This is correct. However, the delta_cn values are different.  In this file:

http://noble.gs.washington.edu/~wnoble/proj/crux-projects/2016gaussian/results/bill/2016-07-24xlink-candidate/ribo.require-xlink=T/search-for-xlinks.txt

the first two lines correspond to matches to scan 22. Both have an xcorr score of 0.039691944, but the first has a delta_cn of 0, and the second has a delta_cn of 0.00029008836.

Reported by: wsnoble

**Comment by sjoemac** [comment]
Can you try this patch? I'm assuming 0.00029008836 is the correct value for both in the example above.
[issue_344.diff.txt](https://github.com/crux-toolkit/crux-toolkit/files/1033189/issue_344.diff.txt)

**Comment by wsnoble** [comment]
Alas, this did not fix the problem. I made a smaller example, and now it's more clear what's going on. If you look at the search-for-xlinks.txt file, you'll see that the last scan (50) has two identical matches.  The only difference between them is that one is target-target and one is target-decoy. I guess when the peptide got shuffled, the shuffle happened to have no effect. In this case, I think it's fine to report both matches, but the deltaCn is still being calculated incorrectly.

[search-for-xlinks.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/1035150/search-for-xlinks.log.txt)
[search-for-xlinks.txt](https://github.com/crux-toolkit/crux-toolkit/files/1035151/search-for-xlinks.txt)
[scan1-50.txt](https://github.com/crux-toolkit/crux-toolkit/files/1035152/scan1-50.txt)
[ecoli_K12_ribo_02.txt](https://github.com/crux-toolkit/crux-toolkit/files/1035153/ecoli_K12_ribo_02.txt)

**Comment by wsnoble** [comment]
Search-for-xlinks is no longer in crux.
