### ISSUE TITLE
Fix handling of mods in tide-index

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#351]
The original version of tide-index allowed multiple variable modifications at a single residue. This is not correct, since you can't have two modifications at the same spot. We have fixed tide-index to not allow this, but the fix is a kludge. In particular, tide-index opens 2^n files, where n is the number of distinct mods. But with the new approach, the vast majority of these files remain at size zero. The logic should be changed so that we don't open all those useless files.

Reported by: wsnoble

**Comment by kaipot** [comment]
Fixed with #384
