### ISSUE TITLE
Percolator segfault

### ISSUE THREAD

**Issue by jpm369** [crux-toolkit/crux-toolkit#361]
cmd line: ./crux percolator proj/2016xl-percolator/results/jpm369/search-for-xlinks/pol2/pol2_concatenated.txt --overwrite T --feature-file-in T

Input file: [pol2_concatenated.txt](https://github.com/crux-toolkit/crux-toolkit/files/549715/pol2_concatenated.txt)
Log file: [percolator.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/549718/percolator.log.txt)

Always crashes at the same place after merging models, but before it gets rid of redundant peptides. The same file runs fine in the standalone distribution of percolator 3.00 (build date June 8 2016). Anything resembling this input crashes at the same place.

**Comment by wsnoble** [comment]
We no longer have a "feature-file-in" option to crux percolator. This command now fails because the file is in PIN format but has a "txt" ending.  Renaming the file to end in .pin fixes the problem.
