### ISSUE TITLE
FATAL: An exception occurred: Parameter 'decoys' does not exist

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#363]
It would appear that search-for-xlinks has some problem with how it accesses parameters.  It is looking for (and not finding) a parameter called "decoys." The tar file at ~wnoble/bug.tgz demonstrates the problem (it's too big to upload). Note that a much smaller input file will likely yield the same bug; I just don't have a convenient way to make one from this file.

**Comment by kaipot** [comment]
This parameter is for determining the type of decoy to generate (reverse or shuffled), I guess we can use the decoy-format parameter here?

**Comment by wsnoble** [comment]
Yes, that's right.  Tide allows three values for that parameter (protein-reverse, peptide-reverse and shuffle).  Does sfx also have three options, or just two?  We should be sure that the description of the option makes it clear if the two commands have different possible values.

**Comment by kaipot** [comment]
The current logic is to use reverse decoys if using reverse protein decoys, and shuffler otherwise. Tide also has a 'none' option, which I'm not sure should be allowed in this case.

**Comment by wsnoble** [comment]
I'm not sure I understand.  Currently, does it do reversed proteins or reversed peptides?  Those two are slightly different.  Also, I think it would be nice to allow a "none" option if the user doesn't want decoys at all.  Is this easy?

**Comment by kaipot** [comment]
The code currently says to reverse the peptide sequence if the "decoys" parameter is set to protein reverse, which doesn't seem right. It gets called from this LinearPeptide::shuffle function. I think that implementing a 'none' option would be easy but Sean should confirm that, I'm not sure if it would cause problems elsewhere in the xlink code.

```
/**
 *\returns a shuffled version of the peptide
 */
void LinearPeptide::shuffle(vector<XLinkMatch*>& decoys) {
  string seq = getSequenceString();
  Crux::Peptide* decoy_peptide = new Crux::Peptide(peptide_);

  decoy_peptide->**transformToDecoy()**;

  XLink::addAllocatedPeptide(decoy_peptide);

  LinearPeptide* decoy = new LinearPeptide(decoy_peptide);

  string decoy_seq = decoy->getSequenceString();
  //  carp(CARP_INFO, "Shuffled: %s", decoy_seq.c_str());

  decoy->setNullPeptide(true);
  decoys.push_back(decoy);
}
```

```
void Peptide::transformToDecoy() {
  bool reverse_seq = (get_decoy_type_parameter("decoys") == PROTEIN_REVERSE_DECOYS);
  ... if (reverse_seq) reverse; else shuffle ...
```

**Comment by wsnoble** [comment]
While waiting to hear back from Sean, I did some additional experiments.  Oddly, if I leave everything else the same but swap out the 8-protein database that I originally provided with a 1-protein database (attached), the program runs fine.  Any guess as to why this is, Kaipo?
[size=1.fa.txt](https://github.com/crux-toolkit/crux-toolkit/files/813815/size.1.fa.txt)

**Comment by sjoemac** [comment]
Right now, sfx supports only shuffle.  It could support none and
peptide-reverse but so far hasn't been implemented.  There is special
handling of shuffling for the xlink peptide products, I just had the linear
peptide call the original shuffle code from the crux Peptide library.

I think we should make a cucumber test that has use-old-xlink set to false
to prevent these parameter changes/deletions from causing issues with the
new code.

As for the 1-protein database, I have no idea.  I would have to spend some
time with the code.  You could turn off linear peptides and I imagine
things would work fine.


Thanks,
Sean

**Comment by wsnoble** [comment]
OK, I am fine with sfx only supporting peptide-shuffle.  Kaipo, why don't you just get rid of the reference to the non-existent "decoys" parameter and just be sure that things are being shuffled?  It might be worthwhile to add to the general description of search-for-xlinks a statement like "Note that, unlike Tide, search-for-xlinks does not have a --decoy-format option; instead, shuffled decoy peptides are always created."

**Comment by kaipot** [comment]
Here is the patch:
[shuffle.txt](https://github.com/crux-toolkit/crux-toolkit/files/815022/shuffle.txt)

**Comment by wsnoble** [comment]
This looks good to me. All tests pass. I also verified that tide-index can
still reverse sequences when asked to do so.
