### ISSUE TITLE
Update how mono-links are specified in search-for-xlinks

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#376]
Currently, we overload the "--mod" operator, adding in a couple of additional Booleans to allow specification of whether a cross-link prevents cleavage and prevents cross-links. Here is the current spec:

--mod [string] – Consider modifications on any amino acid in aa list with at most max-per-peptide in one peptide. The parameter takes the form [mass change]:[aa list]:[max per peptide]:[prevents cleavage]:[prevents cross-link]. This parameter may be included with different values multiple times so long as the total number of mod, cmod, and nmod parameters does not exceed 11. The "prevents cleavage" and "prevents cross-link" arguments are optional T/F arguments for describing whether the modification prevents enzymatic cleavage of cross-linking, respectively. This option is only available when use-old-xlink=F. Note that this parameter only takes effect when specified in the parameter file. Also, to specify multiple modifications, it is necessary to include multiple instances of this parameter, each on a separate line of the parameter file. Default = NO MODS.

I suggest that we separate out the mono-links into a separate option:

--mono-link [mass change]:[aa list]:[max per peptide]:[prevents cleavage]:[prevents cross-link] – Add one or more variable modifications representing mono-link events. The components of the specification string match those used by the "--mod" option, with two additional arguments: The "prevents cleavage" and "prevents cross-link" arguments are T/F arguments describing whether the modification prevents enzymatic cleavage or cross-linking, respectively. Note that mass changes may be provided, separated by commas, subject to the constraint that the total number of variable modifications does not exceed 11. This option is only available when use-old-xlink=F. Default = no modifications.

At the same time, I think we should rename the --mod option to --mods-spec to be consistent with tide. Otherwise, users will likely get them mixed up. Currently, there is no way for Crux to know that an irrelevant parameter was specified, so the user will say search-for-xlinks --mods-spec and not know that this had now effect.

**Comment by sjoemac** [comment]
Should we make the mono-link option follow the same format as the mods-spec format?

i.e. 1M+35:T:T rather than 35:M:1:T:T?

**Comment by wsnoble** [comment]
Yes, that seems like a good idea to me.

**Comment by sjoemac** [comment]
[mod_spec_monolink.tar.gz](https://github.com/crux-toolkit/crux-toolkit/files/906924/mod_spec_monolink.tar.gz)
Could you try this patch?  This should allow mod-spec to be used (mod parameter is disabled).  The mono-link parameter is also added.  Adding the :T:T specifiers are optional (assumes default of :F:F.)

**Comment by wsnoble** [comment]
OK, I am running a search now using the patched version. Lab notebook entry
is here:

http://noble.gs.washington.edu/~wnoble/proj/crux-projects/2016gaussian/results/bill/results.html

It will take a while for the search to complete.  Meanwhile, some minor
comments on the code are below.

Delete commented-out line

//read_mods_from_file(parameter_file.c_str());
in CruxApplication.cpp.

For consistency with the other Carp messages, please begin with a capital
letter and put a space after colons (e.g., carp(CARP_INFO, "missed
cleavages from user:%d" becomes carp(CARP_INFO, "Missed cleavages from
user: %d")

Remove commented block in XLinkDatabase::print() and in
XLinkDatabase:getMonoLinkEnd().

I do not understand the TODO item on line 1044 of mod_spec_monolink.diff.
Can you explain?

In general, TODO items should not go in the code, but should be added as
issues to the issue tracker.

The DETAILED_DEBUG Carp statements in get_aa_mod_from_mass(FLOAT_T mass)
are hard to understand. They should be made more verbose or eliminated.

All of the commented-out functions should be eliminated before checking in,
e.g.,

//void print_a_mod(AA_MOD_T* mod);

**Comment by wsnoble** [comment]
The search referred to in my previous comment completed, and the results look reasonable. So after addressing my previous comments, this can be checked in.
