### ISSUE TITLE
do not enforce q-value threshold on final iteration of cascade-search

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#377]
Here is a patch that makes it so that, in the final iteration of cascade-search, all PSMs are reported, not just the ones up to the specified q-value threshold.

Kaipo, will you please review it?

[cascade-q.diff.txt](https://github.com/crux-toolkit/crux-toolkit/files/873852/cascade-q.diff.txt)

**Comment by kaipot** [comment]
The changes look good to me.
