### ISSUE TITLE
bad allocation via search-for-xlinks  routine

### ISSUE THREAD

**Issue by animesh** [crux-toolkit/crux-toolkit#379]
I tried to analyze a Qexactive raw file (about 700MB consisting of roughly 25K spectra) via search-for-xlinks routine but it threw following error after running for about 15 hours:
````
crux-3.1.Windows.AMD64>bin\crux.exe  search-for-xlinks  "170317_ung_bs3.raw" uniprot-human-jan-2017.fasta K,nterm:Q 137.011
INFO: Beginning search-for-xlinks.
INFO: Writing results to output directory 'crux-output'.
INFO: CPU: promec01
INFO: Crux version: 3.1
INFO: Wed 04/05/2017
INFO: Beginning crux xlink-search (old code)
WARNING: Ignoring peptides with ambiguous amino acids (B, X, Z).
FATAL: An exception occurred: bad allocation
````

so  I am wondering how to fix this and also how to make the program go faster? Is there a way to multithread? Is there a way to reduce the database without significantly compromising the statistical calculations specifically pertaining to false discovery?

**Comment by wsnoble** [comment]
Your program almost certainly ran out of memory. Search-for-xlinks is
designed to consider all pairs of peptides whose masses sum to the observed
precursor mass of a given spectrum.  It looks like you provided the full
human proteome as input. This will produce an extremely massive database
that will not fit in memory.  You will need to use a much smaller database
(on the order of 100 proteins) for this to work.  I suggest that you first
search the data using Tide/Comet+Percolator and then create a database
containing only the highly confidently identified proteins.  If that is
still too many proteins, then you can use those with high abundance (based
on spectral counts).

Also, you probably will want to experiment with the newer version of
search-for-xlinks, by using "--use-old-xlink F".

Unfortunately, we do not have threading implemented yet in
search-for-xlinks.  This is on the to do list.

Bill

**Comment by animesh** [comment]
Thanks Bill for quick insight :+1: 

I tried to run crux in pipeline mode using the same files, but it threw another memory error:

````
F:\promec\Animesh\crux-3.1.Windows.AMD64>bin\crux.exe  pipeline  "f:\promec\Qexa
ctive\LARS\2017\UNG crosslink\170317_ung_bs3.raw" f:\promec\FastaDB\uniprot-huma
n-iso-jan-2017.fasta
INFO: Creating index from 'f:\promec\FastaDB\uniprot-human-iso-jan-2017.fasta'
INFO: Running tide-index...
INFO: Writing results to output directory 'crux-output\tide-search.tempindex'.
INFO: Reading f:\promec\FastaDB\uniprot-human-iso-jan-2017.fasta and computing u
nmodified peptides...
INFO: Ignoring 4828 peptide sequences containing unrecognized characters
INFO: Failed to generate decoys for 6033 low complexity peptides
INFO: Writing decoy fasta...
INFO: Reading proteins
INFO: Wrote 100000 peptides
INFO: Wrote 200000 peptides
INFO: Wrote 300000 peptides
INFO: Wrote 400000 peptides
INFO: Wrote 500000 peptides
INFO: Wrote 600000 peptides
INFO: Wrote 700000 peptides
INFO: Wrote 800000 peptides
INFO: Wrote 900000 peptides
INFO: Wrote 1000000 peptides
INFO: Wrote 1100000 peptides
INFO: Wrote 1200000 peptides
INFO: Wrote 1300000 peptides
INFO: Precomputing theoretical spectra...
INFO: Beginning pipeline.
WARNING: The output directory 'crux-output' already exists.
Existing files will not be overwritten.
INFO: CPU: promec01
INFO: Crux version: 3.1
INFO: Thu 04/06/2017
INFO: Running pipeline with the following steps:
INFO: --> tide-search
INFO: --> percolator
INFO: Running tide-search...
INFO: Search will be run with the following files against database 'f:\promec\Fa
staDB\uniprot-human-iso-jan-2017.fasta':
INFO: --> f:\promec\Qexactive\LARS\2017\UNG crosslink\170317_ung_bs3.raw
INFO: Running tide-search...
INFO: Number of Threads: 32
INFO: Reading index crux-output\tide-search.tempindex
INFO: Converting f:\promec\Qexactive\LARS\2017\UNG crosslink\170317_ung_bs3.raw
to spectrumrecords format
INFO: Elapsed time starting conversion: 1.06 s
^C
F:\promec\Animesh\crux-3.1.Windows.AMD64>del crux-output
F:\promec\Animesh\crux-3.1.Windows.AMD64\crux-output\*, Are you sure (Y/N)? Y

F:\promec\Animesh\crux-3.1.Windows.AMD64>bin\crux.exe  pipeline  "f:\promec\Qexa
ctive\LARS\2017\UNG crosslink\170317_ung_bs3.raw" f:\promec\FastaDB\uniprot-huma
n-iso-jan-2017.fasta
INFO: Creating index from 'f:\promec\FastaDB\uniprot-human-iso-jan-2017.fasta'
INFO: Running tide-index...
WARNING: The output directory 'crux-output\tide-search.tempindex' already exists
.
Existing files will not be overwritten.
FATAL: Index file(s) already exist, use --overwrite T or a different index name

F:\promec\Animesh\crux-3.1.Windows.AMD64>bin\crux.exe  pipeline  "f:\promec\Qexa
ctive\LARS\2017\UNG crosslink\170317_ung_bs3.raw" f:\promec\FastaDB\uniprot-huma
n-iso-jan-2017.fasta  --overwrite T
INFO: Creating index from 'f:\promec\FastaDB\uniprot-human-iso-jan-2017.fasta'
INFO: Running tide-index...
WARNING: The file 'crux-output/tide-index.decoy.fasta' already exists and will b
e overwritten.
WARNING: The output directory 'crux-output\tide-search.tempindex' already exists
.
Existing files will be overwritten.
INFO: Reading f:\promec\FastaDB\uniprot-human-iso-jan-2017.fasta and computing u
nmodified peptides...
INFO: Ignoring 4828 peptide sequences containing unrecognized characters
INFO: Failed to generate decoys for 6033 low complexity peptides
INFO: Writing decoy fasta...
INFO: Reading proteins
INFO: Wrote 100000 peptides
INFO: Wrote 200000 peptides
INFO: Wrote 300000 peptides
INFO: Wrote 400000 peptides
INFO: Wrote 500000 peptides
INFO: Wrote 600000 peptides
INFO: Wrote 700000 peptides
INFO: Wrote 800000 peptides
INFO: Wrote 900000 peptides
INFO: Wrote 1000000 peptides
INFO: Wrote 1100000 peptides
INFO: Wrote 1200000 peptides
INFO: Wrote 1300000 peptides
INFO: Precomputing theoretical spectra...
INFO: Beginning pipeline.
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
INFO: CPU: promec01
INFO: Crux version: 3.1
INFO: Thu 04/06/2017
INFO: Running pipeline with the following steps:
INFO: --> tide-search
INFO: --> percolator
INFO: Running tide-search...
INFO: Search will be run with the following files against database 'f:\promec\Fa
staDB\uniprot-human-iso-jan-2017.fasta':
INFO: --> f:\promec\Qexactive\LARS\2017\UNG crosslink\170317_ung_bs3.raw
INFO: Running tide-search...
INFO: Number of Threads: 32
INFO: Reading index crux-output\tide-search.tempindex
INFO: Converting f:\promec\Qexactive\LARS\2017\UNG crosslink\170317_ung_bs3.raw
to spectrumrecords format
INFO: Elapsed time starting conversion: 1.02 s
INFO: Reading spectra file crux-output/170317_ung_bs3.raw.spectrumrecords.tmp
INFO: Sorting spectra
INFO: Running search
INFO: 1000 spectrum-charge combinations searched, 7% complete
INFO: 2000 spectrum-charge combinations searched, 13% complete
INFO: 3000 spectrum-charge combinations searched, 20% complete
INFO: 4000 spectrum-charge combinations searched, 26% complete
INFO: 5000 spectrum-charge combinations searched, 33% complete
INFO: 6000 spectrum-charge combinations searched, 40% complete
INFO: 7000 spectrum-charge combinations searched, 46% complete
INFO: 8000 spectrum-charge combinations searched, 53% complete
INFO: 9000 spectrum-charge combinations searched, 60% complete
INFO: 10000 spectrum-charge combinations searched, 66% complete
INFO: 11000 spectrum-charge combinations searched, 73% complete
INFO: 12000 spectrum-charge combinations searched, 79% complete
INFO: 13000 spectrum-charge combinations searched, 86% complete
INFO: 14000 spectrum-charge combinations searched, 93% complete
INFO: 15000 spectrum-charge combinations searched, 99% complete
INFO: Time per spectrum-charge combination: 0.007930 s.
INFO: Average number of candidates per spectrum-charge combination: 2532.102539

INFO: Running percolator...
INFO: Post-processing will be run using the following files:
INFO: --> crux-output/tide-search.target.txt
INFO: --> crux-output/tide-search.decoy.txt
INFO: Running make-pin
INFO: Parsing crux-output/tide-search.target.txt
INFO: Assigning index 0 to f:\promec\Qexactive\LARS\2017\UNG crosslink\170317_un
g_bs3.raw.
INFO: Parsing crux-output/tide-search.decoy.txt
INFO: There are 75461 target matches and 75461 decoys
INFO: Finished make-pin.
INFO: Percolator version 3.01.nightly-13-655e4c7, Build Date Mar 30 2017 16:50:0
5
INFO: Copyright (c) 2006-9 University of Washington. All rights reserved.
INFO: Written by Lukas K├ñll (lukall@u.washington.edu) in the
INFO: Department of Genome Sciences at the University of Washington.
INFO: Issued command:
INFO: percolator --results-peptides crux-output/percolator.target.peptides.txt -
-decoy-results-peptides crux-output/percolator.decoy.peptides.txt --results-psms
 crux-output/percolator.target.psms.txt --decoy-results-psms crux-output/percola
tor.decoy.psms.txt --verbose 2 --protein-decoy-pattern decoy_ --seed 1 --subset-
max-train 0 --trainFDR 0.01 --testFDR 0.01 --maxiter 10 --search-input auto --no
-schema-validation --protein-enzyme trypsin --post-processing-tdc crux-output/ma
ke-pin.pin
INFO: Started Thu Apr 06 11:53:15 2017
INFO: Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
INFO: Reading tab-delimited input from datafile crux-output/make-pin.pin
INFO: Features:
INFO: deltLCn deltCn XCorr PepLen Charge1 Charge2 Charge3 Charge4 enzN enzC enzI
nt lnNumDSP dM absdM
INFO: Found 150922 PSMs
INFO: Separate target and decoy search inputs detected, using target-decoy compe
tition on Percolator scores.
INFO: Train/test set contains 75461 positives and 75461 negatives, size ratio=1
and pi0=1
INFO: Selecting Cpos by cross-validation.
INFO: Selecting Cneg by cross-validation.
INFO: Split 1:  Selected feature 3 as initial search direction. Could separate 2
2 training set positives in that direction.
INFO: Split 2:  Selected feature 3 as initial search direction. Could separate 2
0 training set positives in that direction.
INFO: Split 3:  Selected feature 12 as initial search direction. Could separate
55 training set positives in that direction.
INFO: Found 0 test set positives with q<0.01 in initial direction
INFO: Reading in data and feature calculation took 3.952 cpu seconds or 4 second
s wall clock time.
INFO: ---Training with Cpos selected by cross validation, Cneg selected by cross
 validation, fdr=0.01
INFO: Iteration 1:      Estimated 0 PSMs with q<0.01
INFO: Iteration 2:      Estimated 0 PSMs with q<0.01
INFO: Iteration 3:      Estimated 0 PSMs with q<0.01
INFO: Iteration 4:      Estimated 0 PSMs with q<0.01
INFO: Iteration 5:      Estimated 0 PSMs with q<0.01
INFO: Iteration 6:      Estimated 0 PSMs with q<0.01
INFO: Iteration 7:      Estimated 0 PSMs with q<0.01
INFO: Iteration 8:      Estimated 0 PSMs with q<0.01
INFO: Iteration 9:      Estimated 0 PSMs with q<0.01
INFO: Iteration 10:     Estimated 0 PSMs with q<0.01
INFO: Learned normalized SVM weights for the 3 cross-validation splits:
INFO:  Split1    Split2  Split3 FeatureName
INFO:  0.4412    0.2489 -0.4375 deltLCn
INFO: -0.0188    0.1383  0.2956 deltCn
INFO:  0.8054    0.9694  0.0640 XCorr
INFO: -2.3305   -3.0939  3.7466 PepLen
INFO:  0.0000    0.0000  0.0000 Charge1
INFO:  0.5719    0.1547 -0.5534 Charge2
INFO: -0.7047   -0.0159  0.3718 Charge3
INFO:  0.1343   -0.2194  0.3239 Charge4
INFO:  0.0000    0.0000  0.0000 enzN
INFO:  0.0000    0.0000  0.0000 enzC
INFO: -0.0745   -0.2218 -0.1064 enzInt
INFO: -2.1082   -2.6836  5.7450 lnNumDSP
INFO: -1.4385   -1.5339  0.0857 dM
INFO: -1.7189   -1.5839  0.5579 absdM
INFO: -8.3505   -8.6228 -5.2508 m0
INFO: Found 0 test set PSMs with q<0.01.
INFO: No target score better than best decoy
INFO: Resetting score vector, using default vector
INFO: Split 1:  Selected feature 3 as initial search direction. Could separate 2
2 training set positives in that direction.
INFO: Split 2:  Selected feature 3 as initial search direction. Could separate 2
0 training set positives in that direction.
INFO: Split 3:  Selected feature 12 as initial search direction. Could separate
55 training set positives in that direction.
INFO: Selected best-scoring PSM per scan+expMass (target-decoy competition): 765
5 target PSMs and 7451 decoy PSMs.

Unhandled Exception: System.AccessViolationException: Attempted to read or write
 protected memory. This is often an indication that other memory is corrupt.
   at mainCRTStartup()
````

any ideas on how to proceed here?

**Comment by wsnoble** [comment]
OK, there are two problems here.  First, your Percolator training failed,
as evidenced by these lines:

INFO: No target score better than best decoy
INFO: Resetting score vector, using default vector


Second, Percolator seems to have tried to access uninitialized memory.  The
latter should be easier to debug. Can you send us the make-pin.pin file
that was generated by this command?

Thanks.
Bill

**Comment by animesh** [comment]
Ok, so should i go ahead with target-decoy strategy instead? 

"Can you send us the make-pin.pin file
that was generated by this command?"
Yes [make-pin.zip](https://github.com/crux-toolkit/crux-toolkit/files/902280/make-pin.zip) :)

**Comment by thabangh** [comment]
OK, so I found out two things.

(1) The memory problem does not show up when you run this same command on a
linux system.  Since this is a Windows-specific problem, debugging will
have to wait till someone in Seattle (with access to a Windows machine)
wakes up and can take a look at it. (It's the middle of the night there
right now.)

(2) The reason Percolator fails is that there is no separation at all
between targets and decoys.  Here is a plot of the distributions of target
and decoy XCorr scores from the make-pin.pin file:

[image: Inline image 1]

Given that the right tails of these distributions almost perfectly
coincide, it is not surprising that Percolator fails.  This suggests a
problem with the data, or perhaps with the parameters of the search.  One
possible culprit is the conversion from .raw format. You might try running
msconvert (from Proteowizard) on your .raw file first and making sure that
the resulting spectra look reasonable.

Bill

**Comment by sjoemac** [comment]
I would also like to add that using --use-old-xlink F and xlink-top-n=100,
250, or 500 (default 250).  Would run much faster than on your data and
would be less likely to run out of memory. A smaller value of xlink-top-n
will run faster at the cost of limiting the amount of pairs that are
considered for each spectrum.

These two settings run sfx in a kojak-like mode that helps deal with both
the exponential memory and search time issues.  If you want to search all
possible pairs, at the cost of speed and memory, use xlink-top-n=-1.  The
newer version of sfx should have better memory management than the old
version.

Thanks,
Sean

**Comment by kaipot** [comment]
I've verified that the issue occurs on Windows and looking into fixing it.

**Comment by animesh** [comment]
Thanks @thabangh for looking into the distributions. Actually the search with reduced database created using top hits from http://www.proteinmetrics.com/products/preview/about-preview/ did go through and provided results. However there were no q-values using --use-old-xlink F, probably because of what you mentioned. When i removed --use-old-xlink F, the search gave results with q-value < 10E-5 and they fit with the published results. Thus I am wondering if it is OK to use these results or I am seeing signal where there is none?

@sjoemac i will test out your approach and get back if i hit a wall :)

@kaipot thanks for confirming. i could move to linux, but then i need to convert the raw files which i would like to avoid...

**Comment by wsnoble** [comment]
On Fri, Apr 7, 2017 at 11:14 AM, Ani <notifications@github.com> wrote:

> Thanks @thabangh <https://github.com/thabangh> for looking into the
> distributions. Actually the search with reduced database created using top
> hits from http://www.proteinmetrics.com/products/preview/about-preview/
> did go through and provided results. However there were no q-values using
> --use-old-xlink F, probably because of what you mentioned. When i removed
> --use-old-xlink F, the search gave results with q-value < 10E-5 and they
> fit with the published results. Thus I am wondering if it is OK to use
> these results or I am seeing signal where there is none?
>

I am glad to hear that you are getting sensible results. It's impossible to
guarantee, based on this level of description, that your FDR is well
controlled, but the fact that your results agree with published results is
encouraging.  I think the p-values based on Weibull fitting should be taken
with a grain of salt. But the q-values you are seeing are based on standard
target-decoy analysis, so they should be OK.

Bill

**Comment by animesh** [comment]
Thanks again Bill :+1: , could you also comment on the reason why old algorithm gave a result file with q-values (search-for-xlinks.qvalues.txt) while the new one failed to do so even though those q-value might be bizarre?

**Comment by wsnoble** [comment]
We simply don't have the FDR estimation implemented on that branch of the
code. Attached is a Python script that does this. Hopefully, we'll get this
into search-for-xlinks soon.

Bill

**Comment by animesh** [comment]
OK, looking forward to it then :) Meanwhile could you reshare the python script, didn't seem to make it through github response...

**Comment by kaipot** [comment]
Hi @animesh I've committed a fix for the System.AccessViolationException bug, which should be available once our build system pushes an updated version to the website.

**Comment by animesh** [comment]
Thanks @kaipot 👍 looking forward!

**Comment by kaipot** [comment]
Sure no problem, the download is available now.

**Comment by animesh** [comment]
thanks @kaipot , tried the one from http://crux.ms/download.html , but still has the same issue... must note that version number also reflects the old version i think.

**Comment by kaipot** [comment]
@animesh , hmm that is strange. Can you check that the "Date modified" of the crux.exe executable you downloaded is April 18th or newer?

**Comment by animesh** [comment]
"Tuesday, ‎January ‎17, ‎2017, ‏‎7:29:10 PM" , so yes, still old...

**Comment by kaipot** [comment]
Ah sorry I should have been more clear - you will need to click the button to download the most recent build, rather than release 3.1.

**Comment by animesh** [comment]
Thanks @kaipot , that worked :+1:  

No results though, i guess for the reason Bill mentioned where percolator is unable to find a good separation between target-decoy.
