### ISSUE TITLE
Allow specification of relevant peptides in search-for-xlinks

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#381]
Here is an idea for a new feature for search-for-xlinks that I think would be both easy to implement and potentially quite useful.  The idea is that users may be interested in identifying new cross-links between a complex of interest and other proteins. They could search their data first using linear peptides and identify present proteins.  Then they could use search-for-xlinks but specify a subset of the present proteins as "relevant" proteins to focus on. The XL database would then only include cross-links in which at least one of the linked proteins is in the relevant set. This will avoid the quadratic blow-up of the database and still allow people to search a reasonably large set of potential interactors.

The interface would be an option like "--relevant-proteins <file>", where the file contains a list of protein IDs.  Sean, can you comment on whether you think this would be hard/easy to implement?

**Comment by sjoemac** [comment]
It would probably be easy to implement.  Might take a bit of restructuring.  Are you thinking this would be used in conjunction with the top-n (and other search constraint type) parameter(s)?

**Comment by thabangh** [comment]
I had not considered how this might interact with other parameters. Would
the implementation be significantly more difficult if we did not have to
worry about dependencies? I.e. if the user could use this new option in
conjunction with any others?

**Comment by wsnoble** [comment]
Search-for-xlinks is no longer in crux.
