### ISSUE TITLE
Allow multiple MS2 input files for search-for-xlinks

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#382]
Currently, search-for-xlinks only works for a single MS2 file at a time.  We could use the same mechanism as Tide to handle multiple input files.

**Comment by sjoemac** [comment]
Could you try this patch?  Should work with the new code. (use-old-xlink F).

Thanks,
Sean
[sfx_multiple_files.diff.txt](https://github.com/crux-toolkit/crux-toolkit/files/956260/sfx_multiple_files.diff.txt)

**Comment by thabangh** [comment]
I verified that this works OK. The code looks good, and it produces correct
results on one set of input files.

The only minor issue is that the usage statement printed to the HTML still
says "File containing spectra to be searched." It would be better if you
could change it to say "The name of one or more files from which to parse
the fragmentation spectra, in any of the file formats supported by
ProteoWizard."'

Also, it probably makes sense to include a --file-column option, as in
tide-search.  And please add a minor update note to release-notes.html
about this change.

Bill

**Comment by sjoemac** [comment]
Okay, how is this?

Thanks,
Sean
[sfx_multiple_files.diff.2.txt](https://github.com/crux-toolkit/crux-toolkit/files/959704/sfx_multiple_files.diff.2.txt)

**Comment by wsnoble** [comment]
Yes, this looks great. Please go ahead and check this in, close the issue,
and let the user on crux-users know about the fix.

Thanks!
Bill

**Comment by wsnoble** [comment]
Actually, I just noticed one small thing. When compute percentages of spectra skipped, the numerator seems to be over all files and the denominator is only over the current file (see 111% below). It would be good to fix this.

INFO: Assigning index 0 to ../2017-04-19new-data/mewing_D1607_102.ms2.
INFO: Skipped 761 (86.8721%) spectra with 0 candidates.
INFO: Skipped 0 (0%) spectra with too few peaks.
INFO: Loading spectra ../2017-04-19new-data/mewing_D1607_103.ms2.
INFO: Beginning search.
INFO: Assigning index 1 to ../2017-04-19new-data/mewing_D1607_103.ms2.
INFO: 1000 spectrum-charge combinations searched, 38% complete
INFO: 2000 spectrum-charge combinations searched, 76% complete
**INFO: Skipped 2956 (111.885%) spectra with 0 candidates.**
INFO: Skipped 0 (0%) spectra with too few peaks.

**Comment by sjoemac** [comment]
This patch should fix this minor issue

[sfx_multiple_files.diff.3.txt](https://github.com/crux-toolkit/crux-toolkit/files/962932/sfx_multiple_files.diff.3.txt)

**Comment by thabangh** [comment]
Yes, this looks good. Please go ahead and check in.

**Comment by sjoemac** [comment]
Committed.
