### ISSUE TITLE
tide-search does not use the seed parameter

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#383]
When tide-search is run with a fasta file, it shuffles the peptides to create decoys.  Currently, this shuffling is done the same way every time, even if the --seed parameter is set.  The decoys should be different if we use a different seed.  I created an example, but it's too big to upload. I will email it directly to Kaipo.

**Comment by kaipot** [comment]
I'm guessing the seed parameter will work if tide-index is called on its own, but if tide-search calls tide-index it will not. tide-index gets called as part of tide-search's initialization function, and the random is seeded in the same function but afterwards. So, I think we can just rearrange the code in the initialization, here is a patch.

[seed.txt](https://github.com/crux-toolkit/crux-toolkit/files/926439/seed.txt)

**Comment by thabangh** [comment]
Yes, this seems to fix the problem. And the changes to the code look fine.
Please go ahead and check this in, and resolve this issue.
