### ISSUE TITLE
too many missed cleavages

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#385]
Here is a search-for-xlinks command with a single scan over an 8-protein database. I asked for two missed cleavages, but it reports a match with three missed cleavages (two in the first peptide and two in the second peptide):

ALQASALKAWGGKKENLK, KILGEKGKNIK (8,1)

Is the limit on missed cleavages being applied to single peptides or to the cross-linked pair?

The command line is

/net/noble/vol1/home/noble/proj/crux/crux-toolkit2/src/crux search-for-xlinks --use-z-line F --precursor-window-type mz --precursor-window 3 --mz-bin-width 0.02 --use-old-xlink F --overwrite T --concat T --missed-cleavages 2 --mod 156.0786,155.0946278:K,nterm:1:T:T --xlink-include-linears T --xlink-include-deadends T --xlink-include-selfloops T --xlink-include-intra T --xlink-include-inter T --xlink-include-inter-intra T --top-match 1000 --output-dir scan14690 --overwrite T scan14690.ms2 8ProteinMix.fasta K,nterm:K,nterm 138.0680796

[scan14690.txt](https://github.com/crux-toolkit/crux-toolkit/files/961606/scan14690.txt)
[8ProteinMix.txt](https://github.com/crux-toolkit/crux-toolkit/files/961607/8ProteinMix.txt)

**Comment by sjoemac** [comment]
Could you try this patch?

[xlink_missed_cleavage.diff.txt](https://github.com/crux-toolkit/crux-toolkit/files/1033175/xlink_missed_cleavage.diff.txt)

**Comment by thabangh** [comment]
Yes, this seems to work. The code changes look fine, and tests pass. Please
check this in.
Bill

**Comment by sjoemac** [comment]
Checked in.
