### ISSUE TITLE
param-medic does not read spectrumrecords input

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#386]
I ran tide-search with the --store-spectra parameter set, and then I tried to pass the resulting file into a different run of tide-search.  It complained that the file format is not recognized.

/net/noble/vol1/home/noble/proj/crux/crux-toolkit2/src/crux tide-search --overwrite T --precursor-window-type ppm --precursor-window 10 --mod-precision 4 --top-match 1 --auto-mz-bin-width fail --output-dir xcorr 20170403_172_feller_Epi4mini_20170113_DDA.spectrumrecords ../2017-05-16relative-mods/maxMods=2
INFO: param-medic processing input file 20170403_172_feller_Epi4mini_20170113_DDA.spectrumrecords...
FATAL: Unable to parse spectrum file /net/noble/vol4/noble/user/noble/proj/crux-projects/2017histones/results/bill/2017-05-16histone-search/20170403_172_feller_Epi4mini_20170113_DDA.spectrumrecords. Error: [MSDataFile::readFile()] Unsupported file format..

If I get rid of the --auto-mz-bin-width option, then the program runs to completion. We should enable reading of spectrumrecords format when param-medic is used.

**Comment by kaipot** [comment]
Here is a patch that allows param-medic to read spectrumrecords files. Also, it might not be much benefit but it should allow any application using SpectrumCollectionFactory (xlink, print-processed-spectra, get-ms2-spectrum, spectral-counts, etc) to read spectrumrecords files.
[spectrumrecords.txt](https://github.com/crux-toolkit/crux-toolkit/files/1029981/spectrumrecords.txt)

**Comment by wsnoble** [comment]
Yes, this looks good. I re-ran my original search and verified that
param-medic now runs successfully. I also checked the smoke tests.  The
code changes look good. You can check this in.

Bill

**Comment by wsnoble** [comment]
Kaipo, has this fix been checked in? If so, please close this issue.
