### ISSUE TITLE
tide-search core dump on large index with many mods

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#387]
I created a large index from a small number of proteins with many mods. The index has 12.2M target peptides in it. The tide-search command seg faults unpredictably.  Sometimes it is after 98% of the search is complete, sometimes after 95% or 92%.  One time it ran successfully to completion.

The input files are far too large to attach here. I am putting a tar file here:

http://noble.gs.washington.edu/~wnoble/temp/bug.tgz

**Comment by kaipot** [comment]
Hmm, I ran this a few times on my own machine and on tyrosine but couldn't reproduce it. Which machine did you get the seg fault on?

**Comment by wsnoble** [comment]
pyrrolysine

Maybe try it under valgrind? Seems like there must be a memory issue, given the unpredictability of the seg fault.

**Comment by wsnoble** [comment]
FYI, I also submitted this to the cluster. It got assigned to node23 with 100 GB of memory and still dumped core with a seg fault after 92% of the search was complete.

**Comment by kaipot** [comment]
What I've found so far is that it runs okay on my machine (2 cores) and tyrosine (8 cores) but seg faults on cluster when running with the default 24 threads. On the cluster, when --num-threads 8 is specified it does not fail. When running with valgrind, it immediately fails due to an illegal instruction.

**Comment by wsnoble** [comment]
I tried this with 8 cores and 4 cores on pyrrolysine, and it still dumps core.  However, when I set num-threads=1, it runs to completion.  So given that there is a workaround, I am going to remove the "high priority" flag on this issue.

**Comment by wsnoble** [comment]
I found another search that yields a threading bug on tide-search. Some of its behavior might be informative.  When I run the search using a small window (e.g., 1 Da or 10 ppm), then the search runs to completion.  However, if I search using a larger precursor window (e.g., 10 Da or higher), then I get a seg fault. If I then switch to using a single thread, the search runs to completion.  The ms2 file and index are available here:

https://drive.google.com/open?id=0B8J9AwWaqOAabHBWdENxY24wSWc
