### ISSUE TITLE
param-medic does not print to stdout

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#391]
According to the HTML spec for param-medic, the primary outputs are supposed to be printed to stdout:

"Output:
stdout – the estimated parameter values for precursor mass tolerance (in ppm) and fragment bin size (in Th), as well as the standard deviations of the estimated error distributions for precursor and fragment masses."

Currently, everything is sent to stderr.  The attached patch fixes this problem. Kaipo, can you review it?
[parammedic-stdout.txt](https://github.com/crux-toolkit/crux-toolkit/files/1077360/parammedic-stdout.txt)

**Comment by kaipot** [comment]
That change looks good to me.
