### ISSUE TITLE
Add max-charge-feature to make-pin

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#393]
Sometimes when combining results from multiple searches, the maximum observed charge state differs from one run to the next.  When this happens, the feature vectors produced by make-pin will be of different lengths.  I added the max-charge-feature option so that the user can override the default behavior of creating charge features up to the maximum observed charge.

Kaipo, would you please review this patch?

[max-charge-feature.txt](https://github.com/crux-toolkit/crux-toolkit/files/1088101/max-charge-feature.txt)

**Comment by kaipot** [comment]
The patch looks good to me.
