### ISSUE TITLE
sort-by-column fails perversely on large files

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#397]
I tried to run sort-by-column on a file containing 467,010 lines, and it fails saying that the requested column ("scan") does not exist.  However, if I run the command on a truncated version of the same file with just 10 lines, then it works fine.

bash-4.1$ ~/proj/crux/crux-toolkit2/src/crux sort-by-column --column-type real --ascending F foo scan > foobar
INFO: Beginning sort-by-column.
FATAL: column scan doesn't exist
bash-4.1$ head foo > foo-head
bash-4.1$ ~/proj/crux/crux-toolkit2/src/crux sort-by-column --column-type real --ascending F foo-head scan > foobar
INFO: Beginning sort-by-column.
INFO: Elapsed time: 0.00111 s
INFO: Finished crux sort-by-column.
INFO: Return Code:0
bash-4.1$ wc -l foo
467010 foo
bash-4.1$ wc -l foo-head
10 foo-head
bash-4.1$ 

[foo.txt.gz](https://github.com/crux-toolkit/crux-toolkit/files/1432071/foo.txt.gz)

**Comment by kaipot** [comment]
It looks like there is a row limit (presumably to avoid issues when the entire file cannot be read into memory) - once it hits the limit, it is supposed to sort and write them to a temporary file, then join them all at the end but there is some kind of bug here which I'll have to track down.

For a quick workaround, line 80 of src/app/SortColumn.cpp can be changed such that max_rows is a value larger than the number of rows in the file.
`int max_rows = 200000;`

**Comment by wsnoble** [comment]
We are removing this command from crux.
