### ISSUE TITLE
Skip lower ranked PSMs when parsing for assign-confidence

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#399]
When running assign-confidence, the default behavior is to use only PSMs with rank=1.  Unfortunately, if you include lower-ranked PSMs in the input, these all get stored in memory and sorted before being weeded out:

INFO: Found 24825624 PSMs in plasmodium/tide-search.target.txt.
INFO: Score type=exact_pvalue, sorting in ascending order
INFO: Found 24611477 PSMs in plasmodium/tide-search.decoy.txt.
INFO: Skipped 24792655 target and 24578508 decoy PSMs with rank > 1.
INFO: There are 32969 target and 32969 decoy PSMs for q-value computation.

It would be better to allow the parsing routine to skip over lower-ranked PSMs so that the above job does not take so much memory (and time, due to the sort).

**Comment by kaipot** [comment]
Here's a patch:
[top-match-in.txt](https://github.com/crux-toolkit/crux-toolkit/files/1532755/top-match-in.txt)

It adds a new parameter `top-match-in <int>` where the value is the maximum ranking allowed, so `--top-match-in 1` would only allow rank 1 PSMs.

**Comment by thabangh** [comment]
This looks good. Please add a note about it to the release notes. Also,
please make sure this shows up in the list of options for assign-confidence.

Then you can check in and resolve this issue.

Bill

**Comment by kaipot** [comment]
committed in 4478ad830b4c125d88835dde88d2bef8b9cf60cc
