### ISSUE TITLE
Percolator targets have isDecoy=true

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#400]
When running on my data it seems that both target
and decoy data have the flag "isDecoy" set to true (see attached zip).
Basically I get

$ grep -c 'isDecoy..true'
/tmp/20171219_184019_hr-Precision-5520_13467_1/crux-output/percolator.*.mzid
/tmp/20171219_184019_hr-Precision-5520_13467_1/crux-output/percolator.decoy.mzid:18
/tmp/20171219_184019_hr-Precision-5520_13467_1/crux-output/percolator.target.mzid:108

which does not seem right.

(Submitted by Hannes Roest.)

[percolator.decoy.mzid.txt](https://github.com/crux-toolkit/crux-toolkit/files/1576394/percolator.decoy.mzid.txt)
[percolator.target.mzid.txt](https://github.com/crux-toolkit/crux-toolkit/files/1576395/percolator.target.mzid.txt)

**Comment by hroest** [comment]
I can see this when applying percolator as follows:

```
$ crux percolator "--output-dir" perc_out/ "--verbosity" "30" "--concat" "T" "--mzid-output" "T" "--decoy-xml-output" "T" "--test-fdr" "0.01" "--train-fdr" "0.05" "--decoy-prefix" "DECOY_" "--overwrite" "T" crux-output/tide-search.txt
$ grep -c 'isDecoy..true' perc_out/*mzid
perc_out/percolator.decoy.mzid:18
perc_out/percolator.target.mzid:108
```

on the attached files

[crux-output.tar.gz](https://github.com/crux-toolkit/crux-toolkit/files/1576464/crux-output.tar.gz)

**Comment by kaipot** [comment]
[mzid-decoy.txt](https://github.com/crux-toolkit/crux-toolkit/files/1605166/mzid-decoy.txt)

Here is a patch to fix this issue

**Comment by thabangh** [comment]
Kaipo,

These code changes look straightforward, and the smoke tests all pass on my
system.  I think you can go ahead and check this in.

Bill
