### ISSUE TITLE
Discrepancy between tide-index and generate-peptides

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#401]
In principle, the peptide-list option to tide-index should generate the same list of peptides as the generate-peptides command, assuming they are run with the same parameters. However, it seems that this is not quite the case. 

I ran tide-index like this:

crux tide-index --peptide-list T --output-dir index --decoy-format none sp9606_20131001_canonical_target.nodecoy.fasta index

And I ran generate-peptides like this:

crux generate-peptides --output-dir peptide-list --decoy-format none sp9606_20131001_canonical_target.nodecoy.fasta

I then extracted the first column of the two output files, sorted them, and did a diff:

diff <(awk '{print $1}' index/tide-index.peptides.target.txt | sort) \
     <(awk '{print $1}' peptide-list/generate-peptides.target.txt | sort) \
     > diffs.txt

The result (attached) is a set of 31 peptides that show up in the generate-peptides list but not the tide-index list.  Weird!  FASTA and diff file are attached.

[diffs.txt](https://github.com/crux-toolkit/crux-toolkit/files/1580216/diffs.txt)
[sp9606_20131001_canonical_target.nodecoy.fasta.txt](https://github.com/crux-toolkit/crux-toolkit/files/1580217/sp9606_20131001_canonical_target.nodecoy.fasta.txt)

**Comment by kaipot** [comment]
These 31 peptides have at least one amino acid that tide considers invalid (BJOUXZ). It looks like generate-peptides considers only BXZ "invalid" (it still allows them, but when computing mass, assigns 7000 to each, so they fall outside of allowed mass range). I guess J is an ambiguous leucine/isoleucine; O and U are pyrrolysine and selenocysteine. I don't see any problems with allowing tide to use J, O, and U; shall I do that?

**Comment by thabangh** [comment]
Sure, that sounds fine. Note that you'll need to extend the amino acid
frequency vectors used in Tide's p-vale computation.

Bill

**Comment by kaipot** [comment]
Here is a patch - tide-index output for this fasta matches generate-peptides output now
[extra-aas.txt](https://github.com/crux-toolkit/crux-toolkit/files/1580980/extra-aas.txt)

I'm not sure where in the code to extend the amino acid frequency vectors, is it something to do with this line in ActivePeptideQueue::CountAAFrequency:
`const unsigned int MaxModifiedAAMassBin = 2000 / binWidth;   //2000 is the maximum size of a modified amino acid`

Exact p-value search seems to work okay with the patch and finds peptides with selenocysteine.

**Comment by thabangh** [comment]
Yes, these changes seem sensible to me.

In principle, we should handle 'J' a bit differently, because it's a
combination of I and L, but I don't think it's worth worrying about this
right now.

Please add a note to the release notes about this change, then you can
check in.

Bill
