### ISSUE TITLE
incorrect priority of score types in assign-confidence

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#402]
If you run assign-confidence on a tide-search output file that contains the "combined p-value" score type, the program erroneously sorts by "exact p-value."  The logic should be modified so that the "combined p-value," when present, is preferred over "exact p-value."

INFO: Automatically detected score type: exact_pvalue
INFO: Score type=exact_pvalue, sorting in ascending order
INFO: Using a-TDC (3 decoy sets).
[sample.txt](https://github.com/crux-toolkit/crux-toolkit/files/1905739/sample.txt)

**Comment by bmx8177** [comment]
Bug fixed on April 13, 2018
