### ISSUE TITLE
Percolator's picked-protein option does not work in Crux

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#403]
The --picked-protein option produces output on stdout that should be sent to a file. Then it dumps core.

Here is a sample command line crux percolator  --picked-protein homosapiensSWISSPROTJan2017.fasta tide-search.txt 

I have a sample that demonstrates the problem, but it's too big. I will send via email.

**Comment by kaipot** [comment]
[percolator-segfault.txt](https://github.com/crux-toolkit/crux-toolkit/files/1921856/percolator-segfault.txt)

This patch fixes the segmentation fault. The output being written to stdout is a separate issue - which file should it be sent to?

**Comment by thabangh** [comment]
I will check the patch you sent soon.  Meanwhile, the stdout information
should, I believe, go to percolator.target.protein.txt.

**Comment by thabangh** [comment]
Yes, I checked this, and it looks good to me. Please go ahead and check it
in.
Bill
