### ISSUE TITLE
assign-confidence core dump

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#404]
Here is a seg fault from assign-confidence.  Can you take a look?

bash-4.1$ /net/noble/vol1/home/noble/proj/crux/crux-toolkit/src/crux assign-confidence tide-search.target.txt
INFO: Writing results to output directory 'crux-output'.
INFO: CPU: pyrrolysine.gs.washington.edu
INFO: Crux version: 3.1-cb4c82c
INFO: Thu Apr 19 20:34:07 PDT 2018
INFO: Beginning assign-confidence.
INFO: Estimation method = tdc.
INFO: Assigning index 0 to /net/noble/vol1/data/crux-datasets/2007percolator//y\
east-01.ms2.gz.
INFO: Found 69705 PSMs in ../yeast-01.2/tide-search.target.txt.
INFO: Automatically detected score type: xcorr_score
INFO: Score type=xcorr_score, sorting in descending order
INFO: Found 69705 PSMs in ../yeast-01.2/tide-search.decoy.txt.
INFO: 69705 tdc_collection
INFO: Randomly broke 14 ties in 69705 target-decoy competitions.
Segmentation fault (core dumped)

[tide-search.target.txt](https://github.com/crux-toolkit/crux-toolkit/files/1930552/tide-search.target.txt)

[tide-search.decoy.txt](https://github.com/crux-toolkit/crux-toolkit/files/1930553/tide-search.decoy.txt)

**Comment by kaipot** [comment]
I'm not able to reproduce this on my machine, would you mind sending the binary that this happened with?

**Comment by kaipot** [comment]
Weirdly that binary works on my machine but seg faults when I try it on arginine. The backtrace shows that it is happening in a place that doesn't make much sense to me, so I'll try to figure out what's going on here.

**Comment by kaipot** [comment]
[assign-confidence-segfault.txt](https://github.com/crux-toolkit/crux-toolkit/files/1933347/assign-confidence-segfault.txt)
Can you try this patch?

**Comment by wsnoble** [comment]
Yes, that fixes it, and the changes look reasonable. Please go ahead and
check this in.
