### ISSUE TITLE
Add "equal-I-and-L" option to tide-index and spectral-counts

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#405]
Hi, 

I am analyzing samples of the California sea lion. Since there is no genome information published yet, I am searching against Uniprot Carnivora sequences.
This works fine with a Crux Comet/ Percolator Pipeline (for i in *.mzML.gz; do crux pipeline --search-engine comet --decoy_search 1 --add_C_cysteine 57 --variable_mod01 '16 M 0 3 -1 0 0' --variable_mod02 '1 QN 0 3 -1 0 0' --compute-sp T --overwrite T --protein T --output-dir $i-crux-comet-percolator $i uniprot-Carnivora.fasta; done). I get reasonable hits with high probability.

Nevertheless, when trying spectal counting with the same fasta database (for i in *mzML.gz-crux-comet-percolator; do crux spectral-counts --overwrite T --protein-database uniprot-Carnivora.fasta $i/comet.target.txt --output-dir $i-spectral-counts; done), the command fails, because some peptide sequences are not contained in the previously matched proteins. 

I reviewed the concerning entries, and indeed, e.g. J9P540 dies not contain the matched peptide LISWYDNEFGYSNR, but IISWYDNEFGYSNR (I instead of L).

Where does this mis-match come from, and how can I work around this to make the spectral counting work?

-------

So I guess what's happening is that two variants of a given peptide appear in the database, and these peptides occur in different proteins. Comet happily reports the peptide as detected and (reasonably) says that it appears in both proteins. But the spectral counter the complains because it can't find, say, the "I" version of the peptide in the "L"-containing protein (and vice versa).

There are two potential solutions to this problem, but unfortunately, neither is working right now.

One solution is to tell Comet not to treat "I" and "L" interchangeably.  Comet actually has parameter, "equal_I_and_L," which will allow a user to control this behavior.  Setting this parameter to "0" should treat I and L as different.  Unfortunately, Jimmy Eng looked at the code and discovered a bug which makes this parameter ineffective.  So there is no way, currently, not to assume I and L residues are the same. Jimmy will post a fixed version of Comet soon, which we can then incorporate into Crux.

The alternative is to fix the spectral-counts command to treat I and L as the same. This is something we will look into doing. Sorry that we don't have an immediate fix. If you want to send sample input files that we can use to test the fixed version of Crux, that would be helpful.

**Comment by kaipot** [comment]
[protein-il.txt](https://github.com/crux-toolkit/crux-toolkit/files/1993038/protein-il.txt)

This patch fixes the issue.

**Comment by kaipot** [comment]
[protein-il.2.txt](https://github.com/crux-toolkit/crux-toolkit/files/2002085/protein-il.2.txt)
That makes sense to fix also, here's an updated patch.

**Comment by wsnoble** [comment]
I think you have to nest your if's here. E.g., in the case when you are preceded by "-", I think you need something that says

if (StringUtils::StartsWith(protein_seq, peptide_sequence))) {
  return 1
} else {
  return -1
}

**Comment by kaipot** [comment]
I guess it's a question of whether the function should require the flanking amino acids to be correct or just use them as hints. Originally it would search for (n+sequence+c), and if that failed just search for the sequence. I think we want to use the same logic when a flanking amino acid is "-", to check if the protein starts/ends with the sequence; if not, continue through the function (where it will check for the sequence without flanking amino acids)

**Comment by wsnoble** [comment]
Ah, I see. Agreed. I think you can go ahead and check this in.
