### ISSUE TITLE
Comet putting decoys in target file

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#406]
In this example (sent by Robert Winkler) it appears that the pipeline command is producing a target file that contains both targets and decoys.

COMMAND LINE: /net/noble/vol1/home/noble/proj/crux/crux-toolkit2/src/crux pipeline --search-engine comet --decoy_search 1 --add_C_cysteine 57 --variable_mod01 16 M 0 3 -1 0 0 --variable_mod02 1 QN 0 3 -1 0 0 --compute-sp T --overwrite T --protein T 2-1.mzML.gz uniprot-Carnivora.fasta

[comet.zip](https://github.com/crux-toolkit/crux-toolkit/files/2002058/comet.zip)

(Two input files were sent by Robert Winkler on crux-users.)

**Comment by kaipot** [comment]
I think this is just normal crux comet behavior - with decoy_search=1 it produces a concatenated output file named comet.target.txt (decoy_search=2 produces comet.target.txt and comet.decoy.txt). We could ask Jimmy to change output files to omit the "target" part of the name if it's a concatenated search.

**Comment by wsnoble** [comment]
I emailed Jimmy to ask him to make this change.
