### ISSUE TITLE
Percolator runs out of memory on msgf+ file

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#410]
Strangely, the crux- (comet/percolator) workflow works fine on my 16Gb computer, but trying to process msgf+ results (processed wir msgf2pin) with the current percolator version for debian (3.02) fills the memory and freezes the machine.
The pin.tab is only ~6M.
Is there any solution available yet?

--Robert Winkler

Addition: the problem occurs with the -f xx.fasta option. Calculating the protein inference with -A (Fido) works!

Attached an example for a pin.tab

--Robert Winkler

[2-1.mzML.pin.zip](https://github.com/crux-toolkit/crux-toolkit/files/2139318/2-1.mzML.pin.zip)

**Comment by MatthewThe** [comment]
This is a percolator issue due to the many allowed miscleavages in MSGF+: https://github.com/percolator/percolator/issues/191

**Comment by wsnoble** [comment]
Given that this issue is not within Crux per se, I am going to mark it as resolved here.
