### ISSUE TITLE
Performance test yields -nan values for res-ev

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#411]
Running the performance test in the current trunk yields an error from assign-confidence because it can't parse the -nan values produced by tide-search.  The problem arises when using the res-ev score function.  Here is the offending command line:

../../src/crux tide-search --output-dir tide-res-ev --parameter-file crux.param --exact-p-value T --score-function residue-evidence 051708-worm-ASMS-10.ms2 worm+contaminants

The resulting output file (and log file) is attached.

[tide-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/2142966/tide-search.log.txt)
[tide-search.txt](https://github.com/crux-toolkit/crux-toolkit/files/2142967/tide-search.txt)

**Comment by bmx8177** [comment]
Bug fixed with October 18, 2019 commit.
