### ISSUE TITLE
cleavable crosslinker DSSO search with search-for-xlinks for MS2/MS3 orbitrap raw files

### ISSUE THREAD

**Issue by animesh** [crux-toolkit/crux-toolkit#420]
Looking at the list in [search-for-xlink]( http://crux.ms/commands/search-for-xlinks.html ), i see the parameters for [DSSO](https://www.thermofisher.com/document-connect/document-connect.html?url=https://assets.thermofisher.com/TFS-Assets/LSG/manuals/MAN0016303_MSCleavableCrosslinkers_PI.pdf&title=Product%20Info%20Sheet:%20MS-Cleavable%20Crosslinker) with mass changes:
![dsso-masses](https://user-images.githubusercontent.com/21457/49583616-066ccf80-f959-11e8-90b2-2b285255d5a2.png)
are not available, thus i am wondering if the following invokation of crux will work correctly?
````
crux.exe search-for-xlinks  --use-old-xlink F --concat T --top-match 1  "..\..\..\xLink\check\181130_ip_ctr_DSSO_test.raw" ..\..\..\xLink\181130_ip_ctr_DSSO_test\181130_ip_ctr_DSSO_test.fasta K,nterm:K,nterm 158.0038 --mono-link 1K+157.038:T:T,1K+176.0143,1K+155.0946278,1K+175.0303,1K+279.0777,1K+54.01056,1K+103.9932,1K+85.982635,1K+85.05276,1K+111.0320
````

**Comment by animesh** [comment]
thanks @wfondrie 👍 i will check out xlinkx as i do have PD. meanwhile it seems like --mono-link invocation is creating a combinatorial explosion (it worked fine without it), wondering what is the way to control the number of threads as it does look like RAM is the bottleneck here...

**Comment by wfondrie** [comment]
Unfortunately the search space does dramatically increase with the number of `--mono-links` that are specified. In your original command, it looks like there are 10 potential modifications which could explain the problem you saw. If you limit those to the three (or even two, if you know the quenching reagent) `--mono-links` that I mentioned, it should be much less memory intensive.

With regard to changing the number of threads, I think search-for-xlinks will respect the `--num-threads` argument. However, I haven't verified this yet.

**Comment by animesh** [comment]
it turned out to be tris and it did manage to finish, so thanks for the tip @wfondrie 👍
