### ISSUE TITLE
Windows path parsing bug in spectral-counts --protein-database option

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#424]
A user reported the following bug:

On Fri, Jan 4, 2019 at 7:54 PM Kyle Hogan <kyleleahyhogan@gmail.com> wrote:
Hello,

I am a brand new user of this software. I was able to install it correctly and set up my environment (I think!!)

> I am attempting to go through the tutorial with the demo files provided. Everything appears to work fine until I get to the spectral-counts step where I get the following error. 
> 
> C:\Users\hogan>crux_development\crux3.2\bin\crux spectral-counts --protein-database C:\users\hogan\crux_development\small-yeast.fasta C:\users\hogan\crux-output\percolator.target.psms.txt --overwrite T
> WARNING: The output directory 'crux-output' already exists.
> Existing files will be overwritten.
> WARNING: The file 'crux-output/spectral-counts.log.txt' already exists and will be overwritten.
> INFO: CPU: LT-HOGAN
> INFO: Crux version: 3.2-0bf523f
> INFO: Fri 01/04/2019
> INFO: Beginning spectral-counts.
> FATAL: Could not open binary protein file ./C:\users\hogan\crux_development\small-yeast-binary-fasta
> 
> I am unsure of what to do about this error. Am I missing a component that allows crux to open binary protein files? Any help would be greatly appreciated.

I was able to duplicate this error on my WIndows machine. The problem seems to be limited to Windows, where the user specifies a path to the protein database. If the protein database is just a file in the current directory (so no path info in the argument) spectral-counts seems to work correction. So for example:

`bin\crux spectral-counts --protein-database doc\examples\small-yeast.fasta crux-output\percolator.target.psms.txt --overwrite T`

and

 `bin\crux spectral-counts --protein-database c:\Users\cegrant\crux-3.2.Windows.AMD64\small-yeast.fasta crux-output\percolator.target.psms.txt --overwrite T
`

fail, but if you copy small-yeast.fasta into the working directory, the following succeds:

`bin\crux spectral-counts --protein-database small-yeast.fasta crux-output\percolator.target.psms.txt --overwrite T`

This looks like the code is incorrectly parsing paths on Windows.

**Comment by sjoemac** [comment]
I found the issue in parse_filename_path.  It expects the unix style separators.  I made a change to line
if (file[end_idx-1] == '/')

to 

if (file[end_idx-1] == '/' || file[end_idx-1] == '\\')

And spectral counts then works.  However, I wonder if this will be a problem with paths that escape spaces in the file path using the \.

**Comment by wsnoble** [comment]
In what circumstances does a space get replaced with a period? I am not
sure we need to worry about that right now. Have you checked that the fix
you made addresses the problem raised initially? If so, can you go ahead
and check in the patch?

Bill
