### ISSUE TITLE
Please allow to use external dependencies

### ISSUE THREAD

**Issue by yurivict** [crux-toolkit/crux-toolkit#425]
```ext/CMakeLists.txt``` downloads many external projects that already have packages.

Reasons:
* FreeBSD, Debian package builders don't allow external downloads because it is unsafe to download source code and not check fingerprints
* It is hard to fix security issues when the affected code is bundled into many other packages
* Imagine the situation when every project bundles every dependency: every project would be built and installed hundreds or thousands of times, which would consume an enormous amount of disk space and resources. You rely on the consideration that "we would bundle, but others won't". But what if everybody would bundle? This is obviously not a scalable approach.

**Comment by rita-gwen** [comment]
Hi, Yuri, thank you for your (rightful) comment. Yes, we recognize that the build process is becoming more and more complex to the point of being unmanageable. I think we'll go with making it more configurable where the end user can decide what external dependencies they would like to download and build and possibly breaking them off into separate wrapper builds.
