### ISSUE TITLE
spectral-counts tutorial not working

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#427]
I noticed that our tutorial is out of date after the "upgrade" to Percolator v3.0.  In order to get spectral-counts to run to completion, I need to add a "--threshold 0.1" option. But then, even though the log file indicates that everything is working, the output file contains a header line and nothing else.

I tested this on Linux, so I am not sure if the problem is cross-platform.

**Comment by sjoemac** [comment]
When I compile and run on my mac, I get the following:
static-209-70:crux-demo mcilwain$ ./crux spectral-counts --overwrite T --protein-database small-yeast.fasta --threshold 0.1 ./crux-output/percolator.target.psms.txt
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
WARNING: The file 'crux-output/spectral-counts.log.txt' already exists and will be overwritten.
INFO: CPU: static-209-70.vpn.wisc.edu
INFO: Crux version: 3.2-939c57b0
INFO: Sat Feb  2 13:28:30 CST 2019
INFO: Beginning spectral-counts.
INFO: Total proteins found: 56
INFO: Assigning index 0 to ./crux-output/percolator.target.psms.txt.
INFO: Number of matches:109
INFO: Number of matches passed the threshold 61
INFO: Number of peptides 16
INFO: Number of proteins 14
INFO: Elapsed time: 0.0232 s
INFO: Finished crux spectral-counts.
INFO: Return Code:0
static-209-70:crux-demo mcilwain$ ls ./crux-output/spectral-counts.target.txt 
./crux-output/spectral-counts.target.txt
static-209-70:crux-demo mcilwain$ more ./crux-output/spectral-counts.target.txt 
protein id      NSAF
YLR043C 0.61235213
YGL135W 0.18496266
YEL027W 0.089591287
YGL009C 0.036802582
YLR185W 0.032578651
YGR192C 0.0086353049
YGR086C 0.0084569948
YMR235C 0.0070440322
YLL024C 0.0044865748
YGL022W 0.0039929263
YDR205W 0.003959836
YGR157W 0.0032991038
YBR115C 0.0020595698
YDR093W 0.0017784871


Looks like the tutorial is working on the mac.  I'll get my linux dist up and running and try it there.

**Comment by wsnoble** [comment]
Sean also did this on linux and found no problem.
