### ISSUE TITLE
Tide modification report

### ISSUE THREAD

**Issue by ypriverol** [crux-toolkit/crux-toolkit#428]
Hi all: 

We started running tide in PRIDE database. We just realize that when you export the modifications you truncate the original masses provided values. for example: 

> 1090	M[15.99]GVAGR	1_V_15.99	trypsin-full-digest

Even when our config was: `2M+15.994915`

Best Regards 
Yasset

**Comment by thabangh** [comment]
I don't have an easy way to check this right now, but I would expect the
mass precision to be controlled by this option:


   - --mass-precision <integer> – Set the precision for masses and m/z
   written to sqt and text files. Default = 4.


If it does not, then we can change it to do that. Would that be sufficient
for your needs?

Bill

**Comment by ypriverol** [comment]
Thanks @thabangh I have found the parameter. 

mod-precision=6

Thanks
