### ISSUE TITLE
b/y-matches in tide

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#433]
[From crux-users]
I've tried searching a triplex-labeled (reductive dimethylated with light (+28)/medium(+32)/heavy(+36) formaldehyde) sample using tide and filtering with percolator. Each "channel" was search individually and the results.txt combined for percolator. The IDs post percolator match very closely our expectations using other search engines.

When I inspect the intermediate data, I notice that some PSMs have high xcorr scores but 0 (or low) b/y ions matched. I'm trying to understand why this is and greatly appreciate any help. Thanks in advance!

I've attached the tide parameters and ~30 such result entries.

**Comment by wsnoble** [comment]
Adding attachment from previous message.
[by-ions.zip](https://github.com/crux-toolkit/crux-toolkit/files/2931943/by-ions.zip)

**Comment by wsnoble** [comment]
[from Bill]

Hmm, this sounds like maybe a problem with how the b/y ions are computed. Are the examples you sent cherry-picked from you full results file, or is it the case that all of the PSMs have "0" reported in the "b/y ions matched" column? If it's not all of them, then is there a particular variable modification that tends to occur in the 0-matches PSMs?

To fully debug, it would help if you could send the input files as well as the log file generated by Crux.

[from Kenneth]

Yeah I was cherry-picking from the results file. There are indeed other entries that have non-zero b/y ions matched. But the Xcorr scores don't trend with the # reported  (if I understand correctly, Xcorr score is a function of b/y ions matched?). At first glance it looked like there weren't particular var mods that gave 0 scores, but I'll give it a closer look.

I alluded to it before but wanted to specifically clarify — the high Xcorr scoring peptides do in fact belong to be "correct" (based on our usual pipeline). So it really does seem like it's a b/y counting issue.

Since the files were too big here I've attached them over at:
https://drive.google.com/drive/folders/1HvYkp6_9uuXG9WF6O_0JWoRUBBXjLl2j

**Comment by kfattila** [comment]
Just a comment about this issue: The XCorr scores are calculated with one code, and the number of matching b/y ions are calculated with a totally different code, usually only for the report, using the actual, matched peptide sequence. Apparently these two code chunks are inconsistent. Perhaps, some types of modifications are not considered, they use (slightly) different amino acid masses, or the calculated b/y ions are matching with experimental peaks with zero intensities.

**Comment by kfattila** [comment]
Fixed with tide-lite PR.
