### ISSUE TITLE
Same lnNumDSP values for all targets and all decoys after tide-search

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#436]
I was using crux to analyze MALDI MS/MS data. Strangely, tide-search output has one same value of lnNumDSP for all targets  and other same value for all decoy.

Because of which, I am not able to process the results further using percolator. 

Following is the link to google drive folder where the mzML file, the database fasta file, the crux-output folder etc. has been uploaded. 

https://drive.google.com/open?id=19W2G7reTdmkbNVWJ-b9aaymGZZNdhaJe

Kindly suggest what is the issue and how can it be tackled.

Abhishek Dubey <abhishekdubey198115dec@gmail.com>

**Comment by CharlesEGrant** [comment]
I was able to reproduce the problem with seeing the same value of lnNumDSP for all matches. However, when I examined the spectrum file you provided (651.mzML) I noticed that all the spectra had a precursor m/z of 651.0. Given the name of the file I assume this was deliberate. A precursor window of 2.0 was also specified.  This means that for each spectrum, the only peptides that will be considered as candidates will be in the mass range 651 +/- 2.  In the tide-search.target.txt file the values in the column 'distinct matches/spectrum' are all 77. This means that the protein database contains only 77 peptides in that mass range, and each spectrum gets compared to the same 77 peptides. lnNumDSP is just the natural log of the distinct matches / spectrum.
