### ISSUE TITLE
Unhandled Exception when using Residue-Evidence scoring for Tide

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#437]
(from crux-users)

I've been unable to alleviate this issue by changing other parameters.
C:/Users/me/Downloads/Crux/bin/crux tide-search --compute-sp T --auto-precursor-window warn --score-function residue-evidence --use-neutral-loss-peaks false --precursor-window-type ppm --precursor-window 6 --mz-bin-width 0.02 --overwrite T --auto-mz-bin-width warn --min-peaks 10 --output-dir C:/Base/MS_Files/Yeast/190213/crux-output/bad --fileroot 190408_yM2-tide C:/Base/MS_Files/Yeast/190213/190408_yM2.mgf C:/Base/MS_Files/Yeast/search-index

Error:
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at mainCRTStartup()

Index created from yeast proteome available on uniprot, probably not necessary to recreate the entire thing:
C:/Users/me/Downloads/Crux/bin/crux tide-index --overwrite T --clip-nterm-methionine T --mods-spec "C+57.02146 3STY+79.966331 2M+15.9949 2K+42.01056" --missed-cleavages 2 --output-dir C:/Base/MS_Files/Yeast/search-index C:/Base/MS_Files/Yeast/Yeast_Proteome_Isoforms.fasta C:/Base/MS_Files/Yeast/search-index

Running windows using the latest build that I downloaded on 3/23/19. Regular XCorr score works fine using all the same parameters (with neutral loss included)

mgf:
https://drive.google.com/file/d/15wPQ9mHWPtuSmpLmPnt-XvG0CySEK0et/view?usp=sharing

Any help is appreciated!
Thanks

**Comment by wsnoble** [comment]
I asked them to run with --num-threads 1. Their response: "Tried it to no avail, I think I posted it here and the message somehow got erased. Lmk if you'd like the log file."

**Comment by kfattila** [comment]
Hello,

Tide-index generates around 262 million peptides, perhaps --max-mods should be specified. I think, the bug is in int ActivePeptideQueue::CountAAFrequencyRes(...). The amino acid frequencies are estimated by going over all peptides with a while loop, but the allocated memory, in each iteration, is not released. My guess: out of memory occurs. 

See function: int ActivePeptideQueue::CountAAFrequency(...), which uses
     delete[] dAAResidueMass;
     fifo_alloc_peptides_.ReleaseAll();

Good luck ;)

**Comment by kfattila** [comment]
I think, this is not relevant anymore. Maybe it is fixed with the tide-lite PR.
