### ISSUE TITLE
Make trypsin/p the default for tide-search

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#445]

**Comment by wsnoble** [comment]
We discussed this issue today. Andy will make the change and update the smoke tests to explicitly set trypsin as the enzyme, to avoid breaking them all.

**Comment by bmx8177** [comment]
After some discussion we decided not to change the default for this parameter to avoid breaking any existing analyses. Users can select trypsin/p if they prefer that digestion enzyme.
