### ISSUE TITLE
Tide's handling of charged fragments in inconsistent

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#448]
From Attila: "Somewhere in one of your articles you say that the (a) raw XCorr score function and (b) the underlying XCorr score function of exact-p-value method in tide-search is the same, namely, for an experimental spectra with precursor charge state n, the n-1 charged theoretical peaks are generated. This is not true, unfortunately. The two XCorr score functions are implemented with different code, and  they actually calculate different scores. (note that the difference is really minor). The raw XCorr generates only 2+ charged theoretical peaks for any experimental spectra with precursor charge state larger than 2+. This is a little bit cumbersome, because the results are not directly comparable, i.e we don't know if we get better results because of the score calibration or because of the underlying score function has better discriminative power. Note that Comet does it in a third way: there is a user defined parameter to limit the charge states of the theoretical peaks generated, and its default value is 3. So, by default the XCorr in Comet and Tide are the same. I note that, the difference is really minor, but I think you should be aware of that."

We should modify Tide to include the Comet parameter.

**Comment by kfattila** [comment]
XCorr and refactored xcorr are now handling the charged fragments in the same way.
