### ISSUE TITLE
Bug: Command line parameters and parameters from "parameter file"  are not compatible

### ISSUE THREAD

**Issue by lhuangjs** [crux-toolkit/crux-toolkit#458]
For example, I want to specify the prefix of the protein names that indicate a decoy in tide-index. I use parameter `--decoy-prefix REV__`. In output directory, it will generate a decoy library with prefix **REV__**. It is right! However, the value of the parameter  **decoy_prefix**(There is no a parameter named **decoy-prefix** and only a parameter named **decoy_prefix** in the file `tide-index.params.txt`) is still default value **decoy_**  in the file `tide-index.params.txt`, so I cannot use the parameter file for other crux program.

> complete command
```
crux tide-index \
--overwrite true \
--decoy-prefix REV__ \
/home/huangjs/archive/java/metaproteomics/practise/crux/test-pipeline/species1.fasta \
library/species2
```
Then, I use parameter `--decoy_prefix REV__`(modify `-` between **decoy** and **prefix** to `_` ). In output directory, it will generate a decoy library with prefix **decoy_**. It is wrong! However, the value of the parameter  **decoy_prefix** is **REV__**  in the file `tide-index.params.txt`.

> complete command
```
crux tide-index \
--overwrite true \
--decoy_prefix REV__ \
/home/huangjs/archive/java/metaproteomics/practise/crux/test-pipeline/species1.fasta \
library/species2
```

So I think crux make some wrong between `decoy-prefix` and `decoy_prefix`. These two formats should only retain one. And the other parameters may exist the problem.

**Comment by thabangh** [comment]
On Tue, Oct 8, 2019 at 1:24 AM lhuangjs <notifications@github.com> wrote:

> For example, I want to specify the prefix of the protein names that
> indicate a decoy in tide-index. I use parameter --decoy-prefix REV__. In
> output directory, it will generate a decoy library with prefix *REV__*.
> It is right! However, the value of the parameter *decoy_prefix* is still
> default value *decoy_* in the file tide-index.params.txt, so I cannot use
> the parameter file for other crux program.
>

Unfortunately, Comet and Tide use a different standard for parameter names:
Tide uses hyphens whereas Comet uses underscores.  Hence, it is not
surprising that if you set decoy-prefix to REV_ Crux does not change
decoy_prefix to REV_.  These are two different parameters with different
values.  If you want to change both, you can specify both options
(--decoy-prefix REV_ --decoy_prefix REV_).

Bill

complete command

**Comment by lhuangjs** [comment]
Thank you very much for your reply. But I think the comment can be updated in the file `tide-index.params.txt`.

modify
```
# Specifies the prefix of the protein names that indicate a decoy.
# Available for percolator
decoy-prefix=decoy_
```
to
```
# Specifies the prefix of the protein names that indicate a decoy.
# Available for percolator and tide-index
decoy-prefix=decoy_
```
