### ISSUE TITLE
Cannot analyze pepxml generated by crux percolator using ProteinProphet

### ISSUE THREAD

**Issue by lhuangjs** [crux-toolkit/crux-toolkit#459]
I generated `pepxml` using the parameter `--pepxml-output true` of `crux percolator`. Then, I want to analysis the pepxml file using ProteinProhet. The command is as follows:
```
ProteinProphet Run1_P1.percolator.target.pep.xml Run1_P1.percolator.target.prot.xml
```
The command can work well. **But probability for all proteins are 0 in the result protxml file**, like
```
<protein_group group_number="467" probability="0.0000">
      <protein protein_name="259_AIO19726.1" n_indistinguishable_proteins="1" probability="0.0000" unique_stripped_peptides="DYFITQLNDTLK+GDDSVTQLILPIR+TTLPILTGIK" group_sibling_id="a" total_number_peptides="0" total_number_distinct_peptides="0" confidence="nan">
         <parameter name="prot_length" value="0"/>
         <annotation protein_description="259_AIO19726.1"/>
      </protein>
</protein_group>
```
- crux version
```
crux version 3.0
Percolator version 3.02.0
```

- ProteinProphet version
```
ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.2.0 Flammagenitus, Build 201907110004-exported (Linux-x86_64))
```
- tide-search pepxml file: tide-search.pep.xml
- percolator pepxml file: Run1_P1.percolator.target.pep.xml
- protxml file: Run1_P1.percolator.target.prot.xml

All files can be found at [https://drive.google.com/open?id=1yG4gTxIv-W4xZYO_wu2NzDZk7mbPwO6b](https://drive.google.com/open?id=1yG4gTxIv-W4xZYO_wu2NzDZk7mbPwO6b)

**Comment by rita-gwen** [comment]
When I try to run crux percolator using the following command line:
`crux percolator --parameter-file ./crux/Run1_P1.percolator.params.txt --pepxml-output T ./crux/tide-search.pep.xml`
it fails with the following message:
`
INFO: Parsing ./crux/tide-search.pep.xml
FATAL: Parse error at line 2405:
not well-formed (invalid token)
`
The line 2405 reads:
`<alternative_protein protein="decoy_PaD_peg.4464" protein_descr="" num_tol_term="1"  peptide_prev_aa="d" peptide_next_aa="^@"/> `

The files were downloaded from your Google Drive. I wonder about two things:
* is it a bug in tide-search? We had an issue with prev/next AAs just recently in spectral counts, if I remember correctly;
* why your percolator did not produce this error?

Could you provide the command line you used to run it?

**Comment by lhuangjs** [comment]
Thanks for your reply! But I did not use `pep.xml` file as percolator input. I used `pin` file as percolator input. When I used `pep.xml` file as percolator input, I met the same error as you. What am I doing wrong?
I run all commands again. the commands are as follow:
```
## tide-index
crux tide-index \
--parameter-file tide.properties \
--overwrite true \
--output-dir tide-index \
biomass.fasta \
biomass

## tide-search
crux tide-search \
--parameter-file tide.properties \
--overwrite true \
--num-threads 20 \
--output-dir tide-search-Run1_P1 \
Run1_P1_96ng.mgf \
biomass

## percolator
crux percolator \
--decoy-prefix decoy_ \
--decoy-xml-output true \
--pepxml-output true \
--pout-output true \
--output-dir percolator-Run1_P1 \
--fileroot Run1_P1 \
--overwrite true \
tide-search-Run1_P1/tide-search.pin

## ProteinProphet
ProteinProphet \
percolator-Run1_P1/Run1_P1.percolator.target.pep.xml \
Run1_P1.percolator.target.pep.xml
```
But the probability still is 0.
And the result files can be found at (https://drive.google.com/open?id=1tcGcMjw7hmeYwPOf1DJohK2_p4pqn7Tv)[https://drive.google.com/open?id=1tcGcMjw7hmeYwPOf1DJohK2_p4pqn7Tv]. It contains raw data, result files and all commans(a shell script).

- biomass.fasta 
- command.sh: all commands
- Run1_P1_96ng.mgf: raw data
- tide.properties: customized crux parameters
- tide-index: tide-index result dir
- tide-search-Run1_P1: tide-search result
- percolator-Run1_P1: percolator result dir

Note: I didn't upload the database(named biomass) generated by tide-index because it is too big.

**Comment by rita-gwen** [comment]
Sorry for the late response. 
We looked into the pep.xml output from crux percolator using your data and there seems to be no anomalies there comparing to the output of standalone percolator. This combination of crux and ProteinProphet has never really been tested and it is not clear if they are data-compatible. You can try to ask the ProteinProphet team to find the problem on their side, but we would recommend using protein-level output of crux percolator (`--protein true` option) instead.

**Comment by lhuangjs** [comment]
ok, thanks
