### ISSUE TITLE
Docs are incorrect re: preventing digestion

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#463]
The tide-index documentation says to use '{X}|{X}' to prevent digestion. I tried this, but I get "FATAL: No target sequences generated. Is '...' a FASTA file?"; using '[Z]|[Z]' doesn't cause this error, and it prevents digestion (based on the tide-index.peptides.targe.txt file created by tide-index). I'm using crux 3.1.

**Comment by bmx8177** [comment]
Can you give me the exact command and fasta that you are using? I have used '{X}|{X}' and it works for me.
