### ISSUE TITLE
Print version

### ISSUE THREAD

**Issue by bittremieux** [crux-toolkit/crux-toolkit#470]
Crux should have a command to easily print the version so that people can report it in their manuscripts. Same for embedded tools such as Comet and Percolator.

Version information is available in the `.params.txt` files after running a tool, but I'm too lazy to always have to check that.

**Comment by wsnoble** [comment]
This exists.  It is called "version" (surprising, right?):

(base) bash-3.2$ ~/proj/crux-3.2.Darwin.x86_64/bin/crux version
INFO: Beginning version.
====================
Crux version 3.2-8aa66a2d
====================
Proteowizard version 3.0.19117
====================
Percolator version 3.02.nightly-11-aaab4d0-dirty, Build Date Apr 27 2019
13:44:39
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
====================
Comet version 2018.01 rev. 2
====================
Boost version 1_67
====================
INFO: Elapsed time: 0.00132 s
INFO: Finished crux version.
INFO: Return Code:0

**Comment by bittremieux** [comment]
Perfect. I couldn't find it in the documentation on the website or in the Crux help message when I run it without options.

Maybe it is somewhat surprising actually, because it's a command rather than an option. I was trying `--version` and `-version`, but that didn't work.

**Comment by thabangh** [comment]
FWIW, it is listed here:

http://crux.ms/

and it is also listed when you type "crux" with no options.

**Comment by bittremieux** [comment]
Aha, indeed. I looked at that page multiple times yesterday and somehow didn't notice it.
