### ISSUE TITLE
generate-peptides enzymes list

### ISSUE THREAD

**Issue by JB91451** [crux-toolkit/crux-toolkit#474]
Dear crux developers,

I am aware of the option to use _generate-peptides_ command in combination with _--custom-enzyme_ to apply new cleavage rules. 
However, I wrote a larger script to generate a batch file with changing options for the digest. While this works fine for the implemented proteases, I also would like to use other ones (especially LysArgiNase currently). The option _--custom-enzyme [ ]:[KR]_ would not work within my script and it would require a lot of modification to make it working.

Therefore I wanted to ask, if it is possible to add such custom-enzymes to the default list? I think this would also help people working frequently with the same non-standard protease.

Best regards,
Juergen

**Comment by thabangh** [comment]
Hi Juergen,
Yes, this should be relatively straightforward. Can you send the names and
rules for the enzymes you would like to see included?
Thanks.
Bill

**Comment by JB91451** [comment]
Hi Bill,

for us it would only be 
LysArgiNase, cleaving N-terminal to lysine and arginine ( [ ] : [KR] ).

Thank you in advance.
Juergen

**Comment by JB91451** [comment]
Hi Bill,

just a short additional comment on this topic: I am not sure if the enzyme definition from generate-peptides is bound to the other modules. If using LysArgiNase, some search engines may get disturbed in their scoring systems as b-ions are much more predominat than y-ions. As far as I remember, for comet ion type selection is binary but I don't know how this works with your tide algorithm.

Best regards,
Juergen

**Comment by thabangh** [comment]
OK, this change is now implemented and should show up on the crux web page
soon. You can check the release notes to see when it gets pushed:

http://crux.ms/release-notes.html

The Tide search engine uses an XCorr style scoring scheme which treats b-
and y-ions the same, so this should not be an issue.

Cheers.
Bill

**Comment by JB91451** [comment]
Dear Bill and Andy,

Thank you for implementing this so fast!
I tried it already and it works perfectly.

Best,
Juergen
