### ISSUE TITLE
Differing neutral loss behavior between XCorr and XCorr p-value

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#475]
It appears the XCorr and XCorr p-value use a different set of neutral losses.

From the documentation (which I assume correctly represents XCorr): "Controls whether neutral loss ions are considered in the search. Two types of neutral losses are included and are applied only to singly charged b- and y-ions: loss of ammonia (NH3, 17.0086343 Da) and H2O (18.0091422)."

Looking at the code for XCorr p-value (look near end of function of tide/spectrum_collection.cc:Spectrum::CreateEvidenceVector) there is an additional CO loss for b-ions. In addition neutral losses are done for all fragment from 1 to n-1 where is n precursor charge.

**Comment by wsnoble** [comment]
Andy, can you update the documentation for "--use-neutral-loss-peaks" to clarify which neutral losses are employed for the two different score functions?

**Comment by bmx8177** [comment]
Here is the current version of the documentation:
"Controls whether neutral loss ions are considered in the search. Two types of neutral losses are included and are applied only to singly charged b- and y-ions: loss of ammonia (NH3, 17.0086343 Da) and H2O (18.0091422). Each neutral loss peak has intensity 1/5 of the primary peak.    

Here is what I propose:
"Controls whether neutral loss ions are considered in the search. "
    "For XCorr, two types of neutral losses are included and are applied only to "
    "singly charged b- and y-ions: loss of ammonia (NH3, 17.0086343 Da) "
    "and H2O (18.0091422). Each neutral loss peak has intensity 1/5 of "
    "the primary peak. For XCorr p-value, three types of neutral losses are included. "
    "Loss of ammonia and H20 are applied to b- and y- ions and a carbon monoxide "
    "loss (CO, 27.9949) is also applied to b- ions. Each neutral loss peak has an "
    "intensity 1/10 of the primary peak. Neutral losses are not yet "
    "implemented for the res-ev score functions."

Alternatively we can edit the score functions so the better match (easy one would be intensity).

Would this edit warrant a note in release-notes?

**Comment by bmx8177** [comment]
Based off our last conversation I edited the new text as follows:

"Controls whether neutral loss ions are considered in the search. "
"For XCorr, the loss of ammonia (NH3, 17.0086343 Da) is applied to singly b- and y-ions and the loss of water (H2O; 18.0091422) is applied to b-ions. If the precursor charge is >=3, then a doubly-charged version of each ion is added. For XCorr p-value, three types of neutral losses are included. "
"Loss of ammonia and H20 are applied to b- and y- ions and a carbon monoxide "
"loss (CO, 27.9949) is also applied to b- ions.  Higher charge fragments are included for all possible charges less than the precursor charge. All neutral loss peak have an "
"intensity 1/10 of the primary peak. Neutral losses are not yet "
"implemented for the res-ev score functions."

**Comment by wsnoble** [comment]
Looks good. You can go ahead and check this in, with the minor edits in red
below.

Bill


"Controls whether neutral loss ions are considered in the search. "
"For XCorr, the loss of ammonia (NH3, 17.0086343 Da) is applied to singly
charged b- and y-ions, and the loss of water (H2O; 18.0091422) is applied
to b-ions. If the precursor charge is >=3, then a doubly-charged version of
each ion is added. For XCorr p-value, three types of neutral losses are
included. "
"Loss of ammonia and water are applied to b- and y-ions, and a carbon
monoxide "
"loss (CO, 27.9949) is also applied to b-ions. Higher charge fragments are
included for all possible charges less than the precursor charge. All
neutral loss peaks have an "
"intensity 1/10 of the primary peak. Neutral losses are not yet "
"implemented for the res-ev score function."

**Comment by bmx8177** [comment]
Done.
