### ISSUE TITLE
Comet output filename changes

### ISSUE THREAD

**Issue by mriffle** [crux-toolkit/crux-toolkit#484]
I don't know if this is intentional or not, but possibly related to the issue I just reported about comet output.

The filenames output by crux comet have changed.

In the 3.2 release, the files were output with the string "comet." prepended to the output. E.g.:

```
comet.UWPRLumos_2019_0605_AZ_016_eh238_AZ.target.pep.xml
```

Whereas in the latest build, this would be:

```
UWPRLumos_2019_0605_AZ_016_eh238_AZ.target.pep.xml
```

This carries over into the .pin files generated by comet as well. The specId in the 3.2 release would be:

```
./crux3.2-output/comet.UWPRLumos_2019_0605_AZ_013_eh237_AZ_41_3_1
```

But in the latest release it's:

```
./UWPRLumos_2019_0605_AZ_013_eh237_AZ_41_3_1
```

This syntax change does break my current data processing pipelines. I think it would be easy for me to handle this on my end, but I'm just not sure if this is an intentional change or related to the other comet-related issue I reported. Is the output going to use this new syntax going forward?

**Comment by wsnoble** [comment]
This is an unintentional change.  We will work on getting it fixed. Thanks for alerting us to the problem.
