### ISSUE TITLE
Add Tide options to eliminate peaks around the precursor

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#50]
Tide does not exclude from the observed spectrum peaks close to the m/z of the precursor, whereas Crux does:

```
// skip all peaks within precursor ion mz +/- 15
if(peak_location < precursor_mz + 15 &&  peak_location > precursor_mz - 15){
  continue;
}
```

We should find out what Comet does, and then make sure that Tide does what Comet does.

Bill

Reported by: wsnoble

**Comment by wsnoble** [comment]
I'm not sure what "the case for charged reduced peaks" is (see comment above). Can we close this issue?

**Comment by kaipot** [comment]
Sure, closing now.
