### ISSUE TITLE
param-medic is missing some options in the documentation

### ISSUE THREAD

**Issue by wfondrie** [crux-toolkit/crux-toolkit#504]
I noticed today that the online documentation doesn't state that `crux param-medic` can use the `--fileroot` option. I thought this was odd, so I tested it and indeed, the `--fileroot` option does work with `param-medic`. 

I'll update the parameter documentation to reflect this and see if there there are other missing options as well.

**Comment by wsnoble** [comment]
I looked into this. I think all that's needed is to add four more options to 

```
vector<string> ParamMedicApplication::getOptions() const {
```

in src/app/ParaMedicApplication.cpp

The additional lines are
```
    "fileroot",
    "output-dir",
    "overwrite",
    "parameter-file"
```
Of course, this won't affect any smoke tests. I compiled with the change and the usage message looks correct. I will push this change unless you can think of other parameters that might be added.
