### ISSUE TITLE
--precursor-window-type manual

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#508]
Hi,

The manual for the --precursor-window-type at: http://crux.ms/commands/tide-search.html says that:
"The peptide mass is computed as the sum of the **_average_** amino acid masses plus 18 Da for the terminal OH group."

I am not sure this is correct. I think tide-index now uses monoisotopic masses.

**Comment by wsnoble** [comment]
You are correct. I checked in a fix last night to change average to monoisotopic.
