### ISSUE TITLE
Comet does not work with pipeline command

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#509]
A user reported that this command

crux pipeline --search-engine comet 210521_Amyloid_DDA_Sample_01a.ms2 swiss.HUMAN.20141123.amyloid.v2.fasta

yields this error:

FATAL: Cannot perform post-processing without decoys. Set decoy_search to 1 or 2.

I suspect this is due to a Comet upgrade.

**Comment by CharlesEGrant** [comment]
When using comet as the search engine for the pipeline command the '--decoy_search' option must be provided, and set to 1 or 2. (By default comet search doesn't generate decoys, which are needed by percolator for post processing.

I can't find the email from the user. If you could forward that email to me I'll respond to them.

**Comment by wsnoble** [comment]
Thanks, Charles. I will follow up with the user.
