### ISSUE TITLE
Question about tide and comet results

### ISSUE THREAD

**Issue by nattzy94** [crux-toolkit/crux-toolkit#511]
Hi,

I have a question about mass spec analysis in general and would be grateful for some help.

I am performing a mass spec analysis using multiple search engines to support my peptide identifications. Currently I have used tide-search with low-resolution settings (`mz-bin-width=1.0005079`) as I wanted to use the `exact-p-value=T` setting. This identified 4,705 spectra at 1% minimal FDR .

When I run crux comet (with `fragment_bin_tol=0.03`) however, I get significantly fewer identifications, 93 spectra at 1% minimal FDR. When I rerun comet with `fragment_bin_tol= 1.0005079`. This identifies many more spectra - 2,075 at 1% minimal FDR and I would like to use these results. 

However, as the mass spectra were obtained using high resolution settings, would it be inappropriate to analyse the data using low-res settings despite the greater number of identified spectra?

**Comment by wsnoble** [comment]
On Mon, Jul 12, 2021 at 1:43 AM nattzy94 ***@***.***> wrote:

> Hi,
>
> I have a question about mass spec analysis in general and would be
> grateful for some help.
>
> I am performing a mass spec analysis using multiple search engines to
> support my peptide identifications. Currently I have used tide-search with
> low-resolution settings (mz-bin-width=1.0005079) as I wanted to use the
> exact-p-value=T setting.
>

Incidentally, for this analysis you should be using --score-function both
to get the res-ev score as well.


> This identified 4,705 spectra at 1% minimal FDR .
>
> When I run crux comet (with fragment_bin_tol=0.03) however, I get
> significantly fewer identifications, 93 spectra at 1% minimal FDR. When I
> rerun comet with fragment_bin_tol= 1.0005079. This identifies many more
> spectra - 2,075 at 1% minimal FDR and I would like to use these results.
>

You may want to use param-medic to figure out what bin size to use for this
data:

http://crux.ms/commands/param-medic.html

It's described here:

https://pubs.acs.org/doi/abs/10.1021/acs.jproteome.7b00028
https://pubs.acs.org/doi/full/10.1021/acs.jproteome.8b00954


> However, as the mass spectra were obtained using high resolution settings,
> would it be inappropriate to analyse the data using low-res settings
> despite the greater number of identified spectra?
>

There is nothing inherently wrong with changing the bin size from the
nominal size based on your experimental settings. The important part is to
make sure that the bin size accurately reflects the uncertainty in the
observed data.

Bill

**Comment by nattzy94** [comment]
Thanks for the reply. 

Does the `--auto_fragment_bin_tol` parameter in `crux comet` use the same method as param-medic to estimate the bin width? Or does this actually invoke param-medic?

**Comment by wsnoble** [comment]
It actually invokes param-medic.
