### ISSUE TITLE
ActivePeptideQueue::SetActiveRange duplicates theoretical peptides 

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#517]
Hi,

I found a bug. 

The SetActiveRange function duplicates the peptides if the heaviest peptide (in Dalton) is smaller than the neutral mass of the heaviest spectrum (in Dalton). 

Using the data Yang Lu younglululu reported in Issue #516, the heaviest peptide in the index file is "DYAWYWGDFFFLEESELIFDGVFNISPHPMYSIGYLGYYGLSLICNDYK 5913.7041" let's call it peptide A, and there is one decoy with the same mass, let's call it peptide B. These peptides are the last ones in the queue. The heavies spectrum from the mass spec file is the one with SCAN ID 82 (and 41). This spectrum should be score against two peptides A and B. Strangely, this spectrum is scored against three peptides: twice against peptide A, and once peptide B. You can see this in your results as well in the cluster and on your local PC. there are two PSM lines with exactly the same information!
I rerun an old CRUX version, Crux version: 3.2-78825c96 compiled on May/17/2019. This was compiled before Tailor, and this problem already existed. I also run tide-search with exact-p-value T option. This uses a different function (and code) to manage the active peptide queue (int ActivePeptideQueue::SetActiveRangeBIons), and the problem still persists. Therefore, this bug is not raised by Tailor.

The problem is here:
```
  bool done = false;
  //Modified for tailor score calibration method by AKF
  if (queue_.empty() || queue_.back()->Mass() <= max_range || queue_.size() < min_candidates) {
    if (!queue_.empty()) {
      ComputeTheoreticalPeaksBack();
    }
    while (!(done = reader_->Done())) {
      // read all peptides lighter than max_range
      reader_->Read(&current_pb_peptide_);

```

The problem is that, first, the ComputeTheoreticalPeaksBack(); includes the "code" of the last peptide from the queue to the list of the peptides to be socred. And later in `while (!(done = reader_->Done())) {` it checks if reached the end of the peptide index. If the end of the peptide index is reached, every time you call this function, it will generate a new "code" for the last peptide in the queue. 

It is difficult to fix this bug, because the `reader_->Done()` does something else too (it reads something from the peptide index file), so you cannot just call to test the end of the index file any time. See the TODO:260 in code of 'Done()' from src/app/tide/records.h:153
```
 bool Done() {
    if (!valid_)
      return true;
    coded_input_ = new google::protobuf::io::CodedInputStream(raw_input_);
    if (!coded_input_->ReadVarint32(&size_))
      return valid_ = false;
    return (size_ == 0);
    // TODO 260: there should be an easy way to tell if we're at the end
    // of the file, but I can't seem to find a reliable way to do that
    // easily...
  }

```

**Comment by wsnoble** [comment]
Thanks for this diagnosis, Attila. What is the practical effect of the bug?  If it's rare and doesn't actually affect the results (i.e., if you just occasionally compute an extra XCorr), then maybe it's ignorable.  Alternatively, if it's not easy to prevent this from happening, is it possible to detect when it happened and clean it up afterward?

**Comment by kfattila** [comment]
Hi Bill,

1. I think, this bug occurs rarely. It can be avoided if the heaviest peptide (in Da) in the queue is larger than the heaviest spectrum (in Da). I think this bug has a really insignificant impact on the search results, and I tend to believe, it never happens in real applications, but one should be aware of this potential bug. 
2. When the bug occurs, then it simply inflates the "number of distinct matches" a little bit. This might be a slight problem in subsequent analysis (like with Percolator) when this information is used as a feature. It can be detected easily and accurately if you find the same peptide sequence among the set of candidate peptides w.r.t. a given spectrum.   
3. I came to think of it, it might be easy to fix this. There is a local variable in the `RecordReader` class in `records.h` called `bool valid_` see below:
```
 bool Done() {
    if (!valid_)
      return true;
    coded_input_ = new google::protobuf::io::CodedInputStream(raw_input_);
    if (!coded_input_->ReadVarint32(&size_))
      return valid_ = false;
    return (size_ == 0);
    // TODO 260: there should be an easy way to tell if we're at the end
    // of the file, but I can't seem to find a reliable way to do that
    // easily...
  }
```


We could use this variable in the SetActiveRange() as follows:
 ```
bool done = false;
  //Modified for tailor score calibration method by AKF
  if (queue_.empty() || queue_.back()->Mass() <= max_range || queue_.size() < min_candidates) {
    if (!queue_.empty() && reader_->valid_ == True) {    //<-- Look here, the **reader_->valid_ == True** is new!
      ComputeTheoreticalPeaksBack();
    }
    while (!(done = reader_->Done())) {
      // read all peptides lighter than max_range
      reader_->Read(&current_pb_peptide_);
...
```

I guess this would fix this bug, but I have not tried it. So, be careful :)

**Comment by wsnoble** [comment]
Do you have an example where it occurs? That would be helpful in testing
this potential fix.

**Comment by kfattila** [comment]
In the experiment with the data Yang Lu younglululu reported in Issue #516, this bug occurs.

**Comment by kfattila** [comment]
It is fixed with tide-lite PR.
