### ISSUE TITLE
unable to compile Crux

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#518]
I pulled a clean copy of Crux on 12 Aug 2021. I was not able to compile Crux at this time. The compile process fails at the linker and it appears that Percolator is the problem. The log file of the make is attached and I have posted below is the last few lines of the log file.

../../../src/libperclibrary.a(Scores.cpp.o): In function `Scores::print(int, std::ostream&)':
Scores.cpp:(.text+0xcd1): undefined reference to `PercolatorAdapter::printScores(Scores*, int, std::ostream&)'
../../../src/libperclibrary.a(Scores.cpp.o): In function `_GLOBAL__sub_I__ZN11ScoreHolder8printPSMERSobb':
Scores.cpp:(.text.startup+0x64): undefined reference to `ModificationDefinitionContainer::ModificationDefinitionContainer()'
Scores.cpp:(.text.startup+0x73): undefined reference to `ModificationDefinitionContainer::~ModificationDefinitionContainer()'
collect2: error: ld returned 1 exit status
make[5]: *** [tests/unit_tests/percolator/gtest_unit] Error 1
make[4]: *** [tests/unit_tests/percolator/CMakeFiles/gtest_unit.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ext/build/src/percolator-stamp/percolator-build] Error 2
make[1]: *** [ext/CMakeFiles/percolator.dir/all] Error 2
make: *** [all] Error 2

[make-log.txt](https://github.com/crux-toolkit/crux-toolkit/files/6978181/make-log.txt)

**Comment by wsnoble** [comment]
I confirmed that I also run into the same error when compiling on pyrrolysine.

**Comment by CharlesEGrant** [comment]
The linking problem seems to be associated with the Google Test unit tests that are now a standard part of the Percolator build. I added a line to ext/CMakeLists.txt that disables the Percolator unit tests, and that seemed to fix our build.
