### ISSUE TITLE
Is there a parameter to specify MS1 and MS2 bin width?

### ISSUE THREAD

**Issue by nattzy94** [crux-toolkit/crux-toolkit#519]
I would like to perform a search with a narrow MS1 bin width (0.06) followed by wide MS2 bin width (0.5) as my data was acquired using an Orbitrap/Ion trap setup. Is there a way to specify this using `tide-search` or `crux comet`? Am I correct in understanding that the `mz-bin-width` parameter is used for all spectra (MS1 and MS2)?

**Comment by wsnoble** [comment]
In Tide, the MS2 bin width is controlled by the mz-bin-width parameter. You can also specify an offset (mz-bin-offset) and you can have the width set for you automatically (auto-mz-bin-width) via Param-Medic.  The MS1 tolerance is specified via the precursor-window option.  Again, there is an auto-precursor-window option to use Param-Medic for this. Be sure to check the precursor-window-type as well.

In Comet, MS1 tolerance is controlled via peptide_mass_tolerance, and MS2 by fragment_bin_tol. As in Tide, there are auto-* options to use Param-Medic.
