### ISSUE TITLE
Tide: In the pepXML, all search hits are listed as rank 0

### ISSUE THREAD

**Issue by mriffle** [crux-toolkit/crux-toolkit#521]
In the pepXML output from tide, there are 5 PSMs listed per scan. However, they're all listed as rank 0. Here's an example:

```
    <spectrum_query spectrum="UWPRLumos_2019_0605_AZ_016_eh238_AZ.20980.20980.2" start_scan="20980" end_scan="20980" precursor_neutral_mass="798.4532" assumed_charge="2" index="3">
    <search_result>
    <search_hit hit_rank="0" peptide="VAIPMPR" peptide_prev_aa="K" peptide_next_aa="L" protein="tr|F1N3V9|F1N3V9_BOVIN" num_tot_proteins="1" num_matched_ions="7" tot_num_ions="12" calc_neutral_pep_mass="798.4422" massdiff="+0.0110" num_tol_term="2" num_missed_cleavages="0" num_matched_peptides="437" is_rejected="0" protein_descr="">
<modification_info modified_peptide="VAIPM[15.99]PR">
<mod_aminoacid_mass position="5" mass="147.03"/>
</modification_info>
        <search_score name="spscore" value="219.47122192" />
        <search_score name="sprank" value="1" />
        <search_score name="deltacn" value="0.00000000" />
        <search_score name="deltalcn" value="0.39130399" />
        <search_score name="res-ev score" value="23.00000000" />
    </search_hit>
    <search_hit hit_rank="0" peptide="VAQAPWK" peptide_prev_aa="K" peptide_next_aa="A" protein="tr|F1ML89|F1ML89_BOVIN" num_tot_proteins="1" num_matched_ions="3" tot_num_ions="12" calc_neutral_pep_mass="798.4388" massdiff="+0.0143" num_tol_term="2" num_missed_cleavages="0" num_matched_peptides="437" is_rejected="0" protein_descr="">
        <search_score name="spscore" value="36.96896744" />
        <search_score name="sprank" value="6" />
        <search_score name="deltacn" value="0.21739100" />
        <search_score name="deltalcn" value="0.39130399" />
        <search_score name="res-ev score" value="23.00000000" />
    </search_hit>
    <search_hit hit_rank="0" peptide="NGDLPRK" peptide_prev_aa="K" peptide_next_aa="F" protein="tr|F1MUH8|F1MUH8_BOVIN" num_tot_proteins="2" num_matched_ions="3" tot_num_ions="12" calc_neutral_pep_mass="798.4348" massdiff="+0.0184" num_tol_term="2" num_missed_cleavages="1" num_matched_peptides="437" is_rejected="0" protein_descr="">
        <alternative_protein protein="sp|Q2KIN0|ZCHC7_BOVIN" protein_descr="" num_tol_term="2"  peptide_prev_aa="K" peptide_next_aa="F"/>
        <search_score name="spscore" value="50.78444672" />
        <search_score name="sprank" value="5" />
        <search_score name="deltacn" value="0.22222200" />
        <search_score name="deltalcn" value="0.22222200" />
        <search_score name="res-ev score" value="18.00000000" />
    </search_hit>
    <search_hit hit_rank="0" peptide="NLQRLR" peptide_prev_aa="R" peptide_next_aa="T" protein="tr|F1MH68|F1MH68_BOVIN" num_tot_proteins="1" num_matched_ions="4" tot_num_ions="10" calc_neutral_pep_mass="798.4824" massdiff="-0.0292" num_tol_term="2" num_missed_cleavages="1" num_matched_peptides="437" is_rejected="0" protein_descr="">
        <search_score name="spscore" value="98.29853058" />
        <search_score name="sprank" value="3" />
        <search_score name="deltacn" value="0.00000000" />
        <search_score name="deltalcn" value="0.00000000" />
        <search_score name="res-ev score" value="14.00000000" />
    </search_hit>
    <search_hit hit_rank="0" peptide="LNQRIR" peptide_prev_aa="K" peptide_next_aa="G" protein="tr|F1N0M7|F1N0M7_BOVIN" num_tot_proteins="1" num_matched_ions="4" tot_num_ions="10" calc_neutral_pep_mass="798.4824" massdiff="-0.0292" num_tol_term="2" num_missed_cleavages="1" num_matched_peptides="437" is_rejected="0" protein_descr="">
        <search_score name="spscore" value="98.29853058" />
        <search_score name="sprank" value="4" />
        <search_score name="deltacn" value="0.00000000" />
        <search_score name="deltalcn" value="0.00000000" />
        <search_score name="res-ev score" value="14.00000000" />
    </search_hit>
    </search_result>
    </spectrum_query>
```

**Comment by chambm** [comment]
This is also a problem with psm-convert from Percolator PIN. Rank should never be 0. A simple `max(1, rank)` should ensure that (but that won't fix the issue here where there are actually multiple hits per spectrum).

**Comment by kfattila** [comment]
I am just looking at the text file above and (to my eyes) the problem seems to be that there is no 'rank' column in the text file. There is a 'res-ev rank', but probably the converter is looking for a column 'rank'.

**Comment by wsnoble** [comment]
Good point. I guess the converter needs to know about all of the "rank" variants: xcorr rank, res-ev rank, combined p-value rank (and, presumably, p-value rank, though that one does not seem to be listed in http://crux.ms/file-formats/txt-format.html).

This problem was likely introduced when the new score functions got added.

**Comment by bmx8177** [comment]
I think I found where the bug is and can fix it. Patch incoming soon.
Bill - I'm not aware of p-value rank and can not find that particular phrase anywhere in the code. What are you referencing?

**Comment by wsnoble** [comment]
Glad to hear the bug has been found.

I was just assuming there must be a p-value rank if someone just used exact p-value scoring.  But I guess I'm mistaken.

**Comment by bmx8177** [comment]
That is correct. Xcorr rank (for some reason) is used for both xcor and xcorr p-value.

**Comment by bmx8177** [comment]
Patch is attached. Fixed some other small things at the same time (eg lint tests)
[diff.txt](https://github.com/crux-toolkit/crux-toolkit/files/7737754/diff.txt)
.

**Comment by wsnoble** [comment]
Attila will be reviewing this patch.

**Comment by kfattila** [comment]
Hi Andy, the patch looks good but few concerns:
There are more rank-related columns:
  SP_RANK_COL,   PERCOLATOR_RANK_COL,   PARSIMONY_RANK_COL,
I am not sure what are these, ask @younglululu :
  PRECURSOR_INTENSITY_RANK_M0_COL, // added by Yang
  PRECURSOR_INTENSITY_RANK_M1_COL, // added by Yang
  PRECURSOR_INTENSITY_RANK_M2_COL, // added by Yang

Most of the patch contains lint fixes, but I still see some inconsistency around the parentheses at many places:
+  if(is_light_) {    ----> +  if (is_light_) {
+    while ( (count < 3) && (has_changed == false)){     ----> +    while ( (count < 3) && (has_changed == false)) {
+  if (length_ < 2 ) {   ----> +  if (length_ < 2) {
+  if (sequence_ == NULL ) {   ----> +  if (sequence_ == NULL) {

It is hard to see what I propose, but look for the spaces around the brackets.

**Comment by younglululu** [comment]
Thanks Attila for the suggestions! 

1. PRECURSOR_INTENSITY_RANK_M{1-3}_COL are the extra features used in DIAmeter, indicating the precursor intensity logrank.

2. The lint problem you pointed out are from model/Protein.cpp. I can definitely fix the lint problem in the code written by others later on, but I don't believe it's related to this particular issue.

**Comment by wsnoble** [comment]
Just a comment here w.r.t. lint: we are trying to fix issues raised by lint, but it's OK to leave a few lingering ones if they require more extensive changes to other files.  Bad variables types should be fixed if we are modifying the file where they are defined.

**Comment by bmx8177** [comment]
I added cases to account for SP_RANK_COL and PERCOLATOR_RANK_COL.

I did not add cases that accounted for PARSIMONY_RANK_COL. This is because this rank col is only used for spectral counting. I don't think spectral counting is accounted for in a pepxml file so I skipped it.

I also skipped Yang's 3 rank columns as they are not used to rank the final DIAMeter score. As a result, it does not make sense to read it in as a rank column.

In terms of lint issues. I wasn't planning on fixing all of them in this patch (there are over 50 errors in the 2  files I touched). My philosophy was to fix a few each time I submit a patch (to not overwhelm each patch). 

@kfattila - I have attached the updated patch. Let me know if you have any other comments or whether I am good to push it.
[diff.txt](https://github.com/crux-toolkit/crux-toolkit/files/7758334/diff.txt)

**Comment by kfattila** [comment]
Thanks for the updates! I am fine with the modifications. 

However, about the lint issues: I understand and I agree with you. However, if you fix some lint issues in a line, you should fix all the lint issues in that line, not just half of them. 

For instance here, in line 137:
```diff
-  if(!is_memmap_ && !is_light_){ 
-    if (sequence_ != NULL){
+  if(!is_memmap_ && !is_light_) {
+    if (sequence_ != NULL) {
```

you fixed the curly bracket on the RHS (which is nice) , but there is no space after `if`. You could have done that too. The same here, space missing after `if`:
```diff
@@ -172,7 +172,7 @@ void Protein::print(
   )
 {
   // covnert to heavy protein
-  if(is_light_){
+  if(is_light_) {
     toHeavy();
   }
   int   sequence_index;
@@ -263,7 +263,7 @@ void Protein::serialize(
   )
 {
   // covnert to heavy protein
-  if(is_light_){
+  if(is_light_) {
     toHeavy();
   }
```

There is two spaces after the `line_length =  `:
```diff
@@ -480,7 +480,7 @@ bool Protein::readTitleLine
     int line_length;
     size_t buf_length = 0;
 
-    if((line_length =  getline(&new_line, &buf_length, fasta_file)) == -1){
+    if ((line_length =  getline(&new_line, &buf_length, fasta_file)) == -1){
       carp(CARP_FATAL, "Error reading Fasta file.\n");
     }
  ```

But here and at many other places you did perfectly! No need to change anything below:
```diff
@@ -688,7 +688,7 @@ char* Protein::getSequencePointer(
   int offset
 )
 {
-  if(is_light_){
+  if (is_light_) {
```

**Comment by bmx8177** [comment]
Oddly the lint tests do not say they are errors so I didn't catch them. But I see what you are talking about. I added a space after 'if' to make the code consistent. Let me know if you have any other concerns or if I'm good to push.
[diff.txt](https://github.com/crux-toolkit/crux-toolkit/files/7780706/diff.txt)

**Comment by kfattila** [comment]
Thanks for the changes! The code now is beautiful! Do the performance and smoke tests pass? Did you test the code so that RANK fields appear correctly in the pepXML?

**Comment by bmx8177** [comment]
Yes, performance and smoke tests pass. Yes, I did some spot checks to check that rank appears in the pepXML. I'll merge code now.
