### ISSUE TITLE
Diameter code runs in standard tide-search

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#539]
Hi Yang, 

Would it be possible to add an if condition to avoid running code of diameter when only the standard tide-search with XCorr scoring runs? It should be easy. Let me do the code review.

**Comment by kfattila** [comment]
One comment. I think your code runs correct, but let me just raise a concern regarding your code in peptide.cc at lines: 83-90:

```
  double total = aa_masses[0];
  for (int i = 1; i < Len() && total <= max_possible_peak; ++i) {
    workspace->AddBIon(total, 1);
    b_ion_mzbins_.push_back(MassConstants::mass2bin(Peptide::MassToMz(total + MassConstants::B, 1)));
    ion_mzbins_.push_back(MassConstants::mass2bin(Peptide::MassToMz(total + MassConstants::B, 1)));
    ion_mzs_.push_back(Peptide::MassToMz(total + MassConstants::B, 1));
    total += aa_masses[i];
  }
```
I have just two minor concerns to make sure your code does what you intented:
1. The Peptide::MassToMz(total + MassConstants::B is not the final theoretical peak, because the mass of the Proton is missing. 
The exact theoretical peak would be: Peptide::MassToMz(total + MassConstants::B + MASS_PROTON

2. The standard XCorr score uses only unique theoretical peaks, thus it filters out redundant theoretical peaks. If you need the same theoretical peaks which are used in the standard XCorr, then you can access these peaks in :peaks_[0] and in peaks_[1], respectively for different charge states. 

3. vector.push_back and sort are somewhat slow operations, please be careful.

Please also remove the code which you don't need (commented code lines for debugging).

**Comment by younglululu** [comment]
Hi Attila,

Thanks very much for the comments. Actually my implementation is the same as what you suggested. 

Here is how I calculated m/z: Peptide::MassToMz(total + MassConstants::B, 1). MASS_PROTON is actually appended in the function Peptide::MassToMz shown below.

static double MassToMz(double mass, int charge) {
   return mass / (charge * 1.0) + MASS_PROTON;
}

Could you please let me know if you agree with it? Thanks!

**Comment by kfattila** [comment]
Yes, Thanks! Indeed, it looks correct. How about my 2nd concern? Have you considered it?

**Comment by younglululu** [comment]
Hi Attila,

Thanks very much for the comments.

For your second concern, are you talking about the double* peaks_ defined in ObservedPeakSet? If so, according to my understanding, the length of peaks_ is equal to the bin size, which shouldn't be indexed by the charge state. If not, could you elaborate more about your thoughts? Thanks!

For your third concern, that's a good point. Do you have any suggestion in mind? Thanks!

**Comment by kfattila** [comment]
I meant the AddIons in the Peptide.cc. Tide search generates unique theoretical peaks. Refactored XCorr "generates" redundant theoretical peaks. And it is less good in practice.

**Comment by wsnoble** [comment]
I agree with Attila. We should be using the regular XCorr peak set here, not the refactored set.

**Comment by wsnoble** [comment]
Yang and I looked at this code, Attila, and we are trying to understand this comment above: "you can access these peaks in :peaks_[0] and in peaks_[1], respectively for different charge states."  It looks like the peak_ object is defined in  ObservedPeakSet at line 123 of

https://github.com/crux-toolkit/crux-toolkit/blob/master/src/app/tide/spectrum_preprocess.h

We don't understand your comment about accessing different charge states via peaks_[0], peak_[1], etc.  Can you please explain?

**Comment by kfattila** [comment]
Good point. I meant another 'peaks_' It is defined in src/app/tide/theoretical_peak_set.h:526. This one contains list (indexes) of the theoretical peaks.  Sorry, I did not realize there are two different peaks_. Let me know if you need more help!

**Comment by younglululu** [comment]
Hi Attila,

Thanks very much for the comments. I checked the peaks_ in src/app/tide/theoretical_peak_set.h and I think the my DIAmeter code can be optimized by re-using it. But I need to think more about from the implementation perspective, because the solution is definitely not straightforward. 

Since the code is not turned off for standard tide-search, shall we create a new issue about it and close this one? Thanks!

**Comment by wsnoble** [comment]
Not sure I understand your last sentence, Yang.  Did you mean to say "Since the code is now turned off" rather than "not turned off"?

**Comment by younglululu** [comment]
Sorry for the typo. what I meant was that since DIAmeter feature calculation is now turned off for standard tide-search, shall we create a new issue about it and close this one? Thanks!

**Comment by wsnoble** [comment]
You can certainly create a new issue, copying over Attila's comments. But you should wait for Attila's OK before committing these changes and closing this issue.

**Comment by younglululu** [comment]
Thanks for the suggestion. Here is the new issue: https://github.com/crux-toolkit/crux-toolkit/issues/548

**Comment by kfattila** [comment]
This is fixed.
