### ISSUE TITLE
There is a discrepancy between the XCorr documentation and the XCorr implementation in calculating the neutral losses

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#540]
The difference in performance is negligible. The paper (https://pubs.acs.org/doi/pdf/10.1021/pr101196n, page 3873, column 1, top) says that, I quote:
"• a peak with intensity 10 representing the neutral loss of ammonia from each b- and y-ion,
• a peak with intensity 10 representing the neutral loss of water from each b-ion, and
• each a-ion, with intensity 10.
For spectra with precursor charge of 3 or higher, doubly charged
versions of each of the above ions are included in the theoretical
spectrum."
 
The current Tide-Search calculates:
 • a loss peak with intensity 10 representing the neutral loss of ammonia from each b- and y-ion
 • a loss peak with intensity 10 representing the neutral loss of water from each b- **and y-ion**
**Tide-search does not generate a-ions.**
For spectra with precursor charge of 3 or higher, doubly charged
versions of **the loss ions are NOT included** in the theoretical
spectrum.

The refactored XCorr works as described in the Paper.

The original XCorr in Jimmy Eng's papers from 1994 and 1995 generates water, ammonia losses and a-ions, but they aren't specific enough how it handles higher charges.

The XCorr score correlation between the XCorr from tide-search and  Xcorr from the paper:
![image](https://user-images.githubusercontent.com/7715741/145568251-e03c0021-fe87-4451-a230-c51f71fff74e.png)

The performance plots on Humvar and Malaria dataset:
![image](https://user-images.githubusercontent.com/7715741/145568816-e2c7328c-6f31-4ffa-8743-868018788a20.png)
![image](https://user-images.githubusercontent.com/7715741/145568973-7df421c9-1e7d-4044-ab08-0d3409aa96fa.png)

My conclusion is that this is affected only when the users use: `--use-neutral-loss-peaks T ` and the difference is negligible in the performance on two datasets. So, I would propse using the XCorr as it is described in the paper.

Since I removed the peak types from tide-search in order to speed it up thus I cannot reimplement tide-search's XCorr into the new, fast tide-search version. Thus, I propose to implement the XCorr in the improved, fast tide-search, as it is described in the paper. What do you think, Bill?

**Comment by kfattila** [comment]
I've performed some additional tests in comparing the tide.xcorrs against the comet.xcorrs using the HumVar data with bin_width=0.02, and bin_offset=0.0. 

I compared the old, tide.XCorr against Comet.Xcorr, (without neutral loss):
![image](https://user-images.githubusercontent.com/7715741/145676625-929c2494-9893-43ac-8fee-1484f042b00c.png)

The new, fast tide.XCorr against Comet.XCorr, (without neutral loss):
![image](https://user-images.githubusercontent.com/7715741/145676658-20e1d8c2-16a9-44eb-bb99-9cb763102c82.png)
The two plots above are the same.

I compared the old, tide.XCorr against Comet.Xcorr, (**with** neutral loss):
![image](https://user-images.githubusercontent.com/7715741/145676692-094e59db-8b80-486a-af6c-fc8be65a3b66.png)

The new, fast tide.XCorr against Comet.XCorr, (**with** neutral loss):
![image](https://user-images.githubusercontent.com/7715741/145676718-57ef20a3-2158-4f23-b334-8d6f24db136a.png)

**Comment by wsnoble** [comment]
Incidentally, the Comet neutral losses are controlled by use_NL_ions:

http://comet-ms.sourceforge.net/parameters/parameters_202101/use_NL_ions.php

Comet also includes parameters for including various other ion types 
<img width="203" alt="image" src="https://user-images.githubusercontent.com/22529318/145692118-e90845dd-5779-49fb-ae53-52c44dbec578.png">

I don't know how Comet handles higher-charge fragments, but I emailed Jimmy to ask.

I think we should leave Tide-search as is, i.e., calculate b- and y-ions with no a-ions, and include neutral losses if use-neutral-loss-peaks=T (which is the default). I am not sure how to handle +2 neutral losses. I've also asked Jimmy about this.

Incidentally, on at least one recent dataset I have seen a significant boost in power when including neutral losses.

**Comment by wsnoble** [comment]
Here is a description of how Comet handles higher charge state fragments:

https://uwpr.github.io/Comet/parameters/parameters_202102/max_fragment_charge.html

Not sure yet what it does with neutral losses -- Jimmy is checking.

**Comment by kfattila** [comment]
Ok, I'll make tide-search handle NL peaks as before. This will make it a bit slower. 

I bet Comet does not handle NL losses for higher charge states. This is what it seems to me based on my experiments above.

**Comment by wsnoble** [comment]
Jimmy confirmed that the water/ammonia neutral loss contributions, controlled by "use_NL_ions = 1", are applied only to 1+ fragments.

**Comment by kfattila** [comment]
Ok, I fixed it. 
Scatter plot of original tide.xcorr vs updated tide.xcorr (no loss peaks), HumVar data low-res bin width:
![image](https://user-images.githubusercontent.com/7715741/145811100-9d7dce9f-6550-4db6-84c3-160ec83c1934.png)
Scatter plot of original tide.xcorr vs updated tide.xcorr (with neutral loss peaks):
![image](https://user-images.githubusercontent.com/7715741/145811155-86bf8f33-8a90-468a-aae9-f67065cb7caa.png)

Same for high res bin_width settings.
Comet.XCorr vs Tide.XCorr (new):
![image](https://user-images.githubusercontent.com/7715741/145814996-21f3c138-9105-44d6-aac5-b502fdac8914.png)


So, I now understand how the neutral losses are calculated, I noticed that the Refactored XCorr is even more divergent from tide.xcorr, when neutral losses are considered. 
Scatter plot of Xcorr vs refactored xcorr when neutral losses are not considered:
![image](https://user-images.githubusercontent.com/7715741/145816882-3dd2a67b-6b9d-4bf2-b998-c875e1ef7915.png)
Scatter plot of Xcorr vs refactored xcorr when neutral losses are considered:
![image](https://user-images.githubusercontent.com/7715741/145816927-471c1661-bbc5-4496-84fe-1a31573cdc3e.png)

Maybe it is not visible well, but the second scatter plot is worse.
