### ISSUE TITLE
Tide-index generates negative number of peptides

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#545]
INFO: Wrote 9100000 peptides
INFO: Skipped 9218987 duplicate targets and 9219173 duplicate decoys.
INFO: Wrote 4585054 targets and 4603254 decoys.
INFO: Computing modified peptides...
INFO: Opening 250 files for modifications.
INFO: Created -1516210937 peptides.

**Comment by wsnoble** [comment]
Is this just overflow? I.e., do we need to change the type of the num_peptides variable?

**Comment by kfattila** [comment]
Well, it did not free up disk space, :) so it is likely to be an overflow. I will change it to int64.

**Comment by bmx8177** [comment]
Looking at Bill's screen just now I saw this was an active bug. I thought we had fixed this in some pull request. Am I right @kfattila?

**Comment by kfattila** [comment]
Hi, the bug is still in tide-index, I will fix it soon. There was a similar bug in tide search, it reported negative number of candied peptide per spectrum. This is fixed.

**Comment by kfattila** [comment]
This is fixed by the tide-index app update.
