### ISSUE TITLE
inconsistency in pepxml between score functions

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#549]
Crux creates slightly different pepxml files when you run different score functions. Specifically, `<search_score name="xcorr_rank" value="2" />` the rank tag is added when XCorr is run. However, this tag is missing when any other score function is run (XPV, combined, tailor). Not sure if you want to add that tag to other score function outputs or remove from XCorr score output. The relevant code is at PepXMLWriter::printScores. Two screens shots to show difference. 
![image](https://user-images.githubusercontent.com/22140743/148795825-7c578fe1-7554-434a-9646-9f472388d285.png)
![image](https://user-images.githubusercontent.com/22140743/148795857-5199cf33-dfd6-45ae-9acb-713edf0bd4d4.png)

**Comment by wsnoble** [comment]
We discussed this and decided not to change it unless we find that it is causing problems for end users.
