### ISSUE TITLE
Can tide-index generate decoys using protein reverse strategy?

### ISSUE THREAD

**Issue by nattzy94** [crux-toolkit/crux-toolkit#550]
Hi,

I am trying to analyse my mass spec data using multiple search engines. Most search engines use a protein reverse method to generate decoys whereas tide uses a peptide-reverse of shuffle strategy. Is it possible to generate a decoy database with a protein reversal strategy using `tide-index`?

**Comment by wsnoble** [comment]
No, `tide-index` does not have a `protein-reverse` option. For target-decoy competition FDR control to be valid, each target peptide in the database must have a corresponding decoy peptide. Achieving this goal in the context of protein reversal is challenging, especially in conjunction with more complex enzymatic digestion rules. A proper protein reversal strategy should still cleave the peptides at the same locations in the forward and reverse directions. This ends up being equivalent to the `peptide-reverse` strategy.

**Comment by bmx8177** [comment]
For more context.

The reason we need to cleave the proteins at the same location in the forward and reverse direction is that it ensures the target and decoy peptide have the same mass. For target-decoy competition to be valid, each target in the database must have a corresponding decoy peptide. This means that anytime a target peptide is a candidate for a spectrum, the decoy peptide is also always a candidate. The only way to ensure that is if the target and decoy peptide have the same time. Doing a protein reversal strategy does not properly do this.

Example is shown below.
AAAR SSS
SSSR AAA
