### ISSUE TITLE
fileComparator.py seems to produce wrong results when running smoke tests even though the files are the same.

### ISSUE THREAD

**Issue by acquayefrank** [crux-toolkit/crux-toolkit#551]
When running the smoke tests filecomporator.py fails some tests based on precision.  
But when I compare the files using TotalCommander the files are actually identical. 

These files can be found [here](https://disk.yandex.com/d/3MwuGnV6dDDscQ).

A log of the error message obtained:
```
    Examples: 
      | test_name                 | index_args                                                    | search_args                                                                                                                                                               | fasta             | index           | spectra  | actual_output          | expected_output                |
      |Python file comparator:There are 1 rows in the actual data that do not match 1 rows in the expected data.
 tide-default              |                                                               | --precursor-window 3 --precursor-window-type mass --mz-bin-width 1.0005079                                                                                                | small-yeast.fasta | tide_test_index | demo.ms2 | tide-search.target.txt | tide-default.txt               |
      
      expected true
           got false
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/SmokeTestStepDefinitions.rb:55:in `/^All lines in (.*) should be in (.*) with ([^\s]+) digits precision$/'
      ./features/tide-search.feature:24:in `And All lines in crux-output/tide-search.target.txt should be in good_results/tide-default.txt with 5 digits precision'
      ./features/tide-search.feature:20:in `And All lines in crux-output/<actual_output> should be in good_results/<expected_output> with 5 digits precision'
```

**Comment by CharlesEGrant** [comment]
I generated the same files and they appear different in diff. It looks like the big problem is that current output seems to be getting sorted by neutral mass. There are some trivial differences in deltaCn and XCorr, but those should be handled by precision sensitive Cucumber script we have. tide-default.txt is our current 'known good' standard. tide-search.target.txt is the current output for the test.

[tide-default.txt](https://github.com/crux-toolkit/crux-toolkit/files/7991506/tide-default.txt)
[tide-search.target.txt](https://github.com/crux-toolkit/crux-toolkit/files/7991507/tide-search.target.txt)
.

**Comment by kfattila** [comment]
Could you please attach the log file and the param files too? Neither tide-default.txt nor tide-search.target.txt are sorted by neutral mass. Both should be sorted by neutral mass.
