### ISSUE TITLE
Tide-index generates decoys when allow-dups T

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#555]
Tide-index generated decoy peptides with the following parameter:
--decoy-format none --allow-dups T
Note that: Tide index should have not generated decoy peptides.

But it does not generate decoy peptides when:
--decoy-format none --allow-dups F

A

**Comment by wsnoble** [comment]
I tested this and verified that there is a problem. Here is a sample fasta file:

```
$ cat sample.fasta 
>sample
PEPTIDEKPEPTTTIDER
```

And here is the command line I used:

```
$crux tide-index --overwrite T --allow-dups T --decoy-format none --peptide-list T --output-dir sample sample.fasta sample
WARNING: The output directory 'sample' already exists.
Existing files will be overwritten.
INFO: CPU: Williams-MacBook-Pro-2.local
INFO: Crux version: 4.1-eb571643-2021-12-17
INFO: Wed Feb  9 10:27:15 PST 2022
INFO: Beginning tide-index.
INFO: Running tide-index...
WARNING: The output directory 'sample' already exists.
Existing files will be overwritten.
INFO: Reading sample.fasta and computing unmodified peptides...
INFO: Generated 1 targets, including duplicates.
INFO: Generated 1 decoys.
INFO: No decoys will be generated
INFO: Reading proteins
INFO: Skipped 0 duplicate targets and 0 duplicate decoys.
INFO: Wrote 1 targets and 1 decoys.
INFO: Writing peptide lists...
INFO: Precomputing theoretical spectra...
INFO: Elapsed time: 0.0212 s
INFO: Finished crux tide-index.
INFO: Return Code:0
```
After this completes, the peptide list looks like this:

```
$cat sample/tide-index.peptides.txt 
target	decoy	mass	proteins
PEDITTTPEPKEDITPER		2067.0007	
PEPTIDEKPEPTTTIDER		2067.0007	sample
```

I am guessing that the new code that Yang added to output decoys in the target list does not handle `--decoy-format none`.

**Comment by kfattila** [comment]
What should be the format of the peptide-list.txt without decoys? Should tide-index print an empty column or should it skip the 'decoy' column entirely?

**Comment by wsnoble** [comment]
Skip it entirely, I think.  Though either would be acceptable.

**Comment by kfattila** [comment]
This is fixed by the new tide-index app update.
