### ISSUE TITLE
Handle spectra with missing or zero charge

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#557]
This is a request from a Crux user. If a spectrum has no charge state specified or has a charge state of 0, then tide-search should search the spectrum in all possible charge states, ranging from min-precursor-charge to max-precursor-charge.  Note that this requires adding the `min-precursor-charge` option, which does not yet exist.

**Comment by bmx8177** [comment]
Isn't that this parameter? 
![image](https://user-images.githubusercontent.com/22140743/155037509-3a3e800c-5251-49c1-9bd6-e5ebb2c04bb8.png)

**Comment by wsnoble** [comment]
I believe (though I could be mistaken) that that parameter simply tells the program to skip over some spectra if they do not have the specified charge state.  It does not do anything with spectra that have no assigned charge state.  Am I wrong?

In fact, I thought Tide had some code in it (originally from Mike MacCoss) that tries to infer the charge state when no charge is given.  I was thinking we should get rid of that code and replace it with code that simply searches each spectrum in all possible charge states.  Maybe we can leave the "inference" code in place, but document it and put it under user control.

**Comment by bmx8177** [comment]
Ah yes, you are correct. The `--spectrum-charge` is not relevant.

@younglululu I have some vague recollection about some code we talked about where Tide tried a range of charges. Am I remembering right?

**Comment by younglululu** [comment]
@bmx8177 Yes, but I don't quite remember what were the conclusion we draw at that time. I only vaguely remembered that there is a large chunk of code related to determining the missing charge though I don't understand them.

**Comment by wsnoble** [comment]
There is a loop over charge states at line 569 of https://github.com/crux-toolkit/crux-toolkit/blob/master/src/app/TideSearchApplication.cpp

But I can't find where that is created.

**Comment by kfattila** [comment]
MakeSpecChargesIMO, 
The experimental spectra must be sorted by calculated neutral mass for tide-search. Otherwise, the search would need different activePeptideQueues to go forth and back over the sorted theoretical peptides. The loop over charge states in line 569 isnt a loop over charge states, it is a loop over spectrum-charge-state combinations. 

Tide-search already handles experimental spectra with multiple charge states. For instance, the yeast experimental dataset contains several experimental spectra with double and triple charge states. 
I think the simplest solution would be to handle this situation during loading the experimental spectra., but it must be done before sorting the experimental spectra by mass. The sorting is done in the loadSpectra function in SpectrumCollection* TideSearchApplication::loadSpectra(const string& file) : 482. in TideSearchApplication.cpp

This could be handled easily in src/app/tide/spectrum_collection.cc line 27:
```Spectrum::Spectrum(const pb::Spectrum& spec) {
  spectrum_number_ = spec.spectrum_number();
  precursor_m_z_ = spec.precursor_m_z();
  rtime_ = spec.rtime();
  for (int i = 0; i < spec.charge_state_size(); ++i)
    charge_states_.push_back(spec.charge_state(i));
```
if  spec.charge_state_size() == 0 or  spec.charge_state(0) == 0, then just create a vector for charge_states with the desired charge states.

**Comment by wsnoble** [comment]
Thanks, Attila. If you have time to make these changes on a branch, I'll be happy to test it out and review it when I get back from my trip.

I think we should make a new smoke test for this. I'm imagining an input file containing two spectra, one with charge state 0 and one with charge-state 1.  Then we will specify --min-precursor-charge 2 --max-precursor charge 4 and make sure that we get results only for charge states 2, 3 and for for the second spectrum. I can work on creating this test.

**Comment by kfattila** [comment]
Can you send me data with 0 charge states. I have never bumped into such case.

**Comment by wsnoble** [comment]
I can’t right now (on a phone) but you can easily create such data by search and replace for the charge state in an mgf file.

**Comment by wsnoble** [comment]
Attila, here is a sample for the smoke test for this functionality: https://noble.gs.washington.edu/~wnoble/proj/2010_wnoble_crux-tinkering/results/results.html

**Comment by kfattila** [comment]
Hi Bill, thanks for the data you generated, it helped a lot. I wrote the code, but I found a problem. The pwiz parser and the mstoolkit parser does not read the precursor mass if the charge state is 0. So, if the charge is 0, then the precursor_m_z is also 0, despite it is defined in the mgf file. I tried to trace down the code, but it looks like that it leads to the vendor and external codes in pwiz. :/

Maybe problem appears with only MGF files, I do not know. 

I also saw that @younglululu made some changes in the code, maybe he could help if he knows how to force the parsers to read the precursor mass if charge state is missing.

**Comment by wsnoble** [comment]
Hmm, what happens if you just don't specify a charge state at all in the mgf file? Does pwiz read the precursor mass in that case?

**Comment by younglululu** [comment]
Yes, I can certainly help! But my experiences in dealing with these two parsers was that pwiz parser is much easier to modify compared to mstoolkit parser. And I only managed to modify pwiz parser only in DIAmeter. 

I would be happy to have a more detailed discuss on crux meeting this Friday or any time earlier upon to your convenience. :D

**Comment by kfattila** [comment]
Thanks a lot @younglululu ,

Do you know where is the parsing for the charge states and the precursor ion mass is located in the code?

Bill, If I remove the CHARGE=0, then the charge state is automatically predicted. I have two different spectra without charge states. The pwiz automatically predicts two charge states: 2,3 for the first experimental spectrum, and it predicts charge state 1 for the second experimental spectrum.

**Comment by wsnoble** [comment]
Yes, the heuristic for assigning charge states when charge is not specified is something I think Mike MacCoss came up with when he was still a postdoc.  We want to figure out a way to turn this off and instead get the full range of charge states.  That heuristic was developed when +3 was essentially the maximum charge state. And it doesn't even make sense for chimeric spectra like those produced by DIA.

**Comment by kfattila** [comment]
Am I right, it is in the pwiz? Maybe pwiz guys could remove it?

**Comment by chambm** [comment]
For pwiz, if an MGF has a single charge, it is considered definitive. If it's 0 there's no special handling. That would just get you a selectedIon with an MS_charge_state with value="0". It's up to the mzML reader to decide what to do with that. I don't think the MGF format specifies that CHARGE=0 is even valid, much less that it should be interpreted as a range of charges. Instead, if you want to specify multiple possible charge states in MGF, it's done like:
`CHARGE=2+ 3+ 4+` or `CHARGE=2+ and 3+ and 4+`. Pwiz will handle either case but I'm not sure about other tools.

**Comment by wsnoble** [comment]
Thanks, this is very good to know!

**Comment by fundmntlTheorem** [comment]
We (Thermo) write charge state 0 into the scan trailer when the charge state of the precursor can't be determined, which happens often if the master analyzer was the ion trap.  In fact for development I've been writing 0 to the trailer for any non-PRM ion trap method.  I've been getting by with a Proteome Discoverer feature that will search Charge state 0 as a selectable range of charge states, ex 2, 3, 4.  Possibly a user would want to overwrite the charge state for DIA experiments as well, where the trailer writes just the default charge state of 2.  Currently when I use Tide I directly specify raw files without converting to an intermediate format, so doing a step of converting to MGF wouldn't be as desirable.  It would be great if Tide could configure the search of the multiple charge states like Bill was describing.  For me it would be enough usually to globally specify a range of charge states to search every spectrum, irrespective of the spectrum charge state.  The handling of charge == 0 could be a separate thing, that also uses the value in some override_charge_state variable.  So maybe we'd have this:

override_charge_mode = all-spectra or unrecognized-only
override_charge_state = comma delimited list

**Comment by chambm** [comment]
ProteoWizard reads "Charge State: 0" from Thermo RAW files as meaning "charge unknown" and so it doesn't add a charge state to the spectrum. "Monoisotopic M/Z: 0" is similar except we use the isolation m/z. If you want ProteoWizard to use the singly/multiply charged predictor based on how much TIC is below the precursor m/z (where multiply charged will be given a range of "possible charge state" terms), then add the SpectrumList_ChargeStateCalculator filter. It can be used directly on any type of input file. Here's an old doxygen page for it:
https://proteowizard.sourceforge.io/dox/classpwiz_1_1analysis_1_1_spectrum_list___charge_state_calculator.html

**Comment by wsnoble** [comment]
I guess the problem is that if we have charge=0, then precursor_m_z ends up also being zero, even though it's defined in the input file. We'd like to be able to get the precursor_m_z even if charge=0. Is this possible?

**Comment by chambm** [comment]
I'm not sure I understand. The instrument gives you precursor m/z even if it can't determine charge state. It's precursor mass you can't get without knowing the charge.

**Comment by wsnoble** [comment]
Well, Attila knows better than I do, but based on his description from earlier in this thread, it sounds like he is feeding into pwiz an MGF file with the precursor m/z specified and charge state set to 0, and we get back an object that has no charge state and no precursor m/z.  Attila, can you provide more details?

**Comment by kfattila** [comment]
Where is this filter added in the code?

**Comment by chambm** [comment]
In crux code? I don't know. GitHub search doesn't find it. I tested converting an MGF with and without CHARGE=0 (i.e. without any CHARGE line).

With CHARGE=0:
```
<selectedIon>
  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="445.122000" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
  <cvParam cvRef="MS" accession="MS:1000041" name="charge state" value="0"/>
</selectedIon>
```

With no CHARGE:
```
<selectedIon>
  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="445.122000" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
</selectedIon>
```

As you can see, no charge state prediction.

**Comment by kfattila** [comment]
Thank you. This is helpful.

**Comment by younglululu** [comment]
I think both pwiz and mstoolkit parser determine the charge state in the assignZState function from src/model/Spectrum.cpp

FYI, here is a fig I drew previously about the workflow of how pwiz/mstoolkit parse the data.
![image](https://user-images.githubusercontent.com/15314522/159065263-c738ee91-b3b8-49e7-8436-97ce652832dc.png)

**Comment by kfattila** [comment]
> We (Thermo) write charge state 0 into the scan trailer when the charge state of the precursor can't be determined, which happens often if the master analyzer was the ion trap. In fact for development I've been writing 0 to the trailer for any non-PRM ion trap method. I've been getting by with a Proteome Discoverer feature that will search Charge state 0 as a selectable range of charge states, ex 2, 3, 4. Possibly a user would want to overwrite the charge state for DIA experiments as well, where the trailer writes just the default charge state of 2. Currently when I use Tide I directly specify raw files without converting to an intermediate format, so doing a step of converting to MGF wouldn't be as desirable. It would be great if Tide could configure the search of the multiple charge states like Bill was describing. For me it would be enough usually to globally specify a range of charge states to search every spectrum, irrespective of the spectrum charge state. The handling of charge == 0 could be a separate thing, that also uses the value in some override_charge_state variable. So maybe we'd have this:
> 
> override_charge_mode = all-spectra or unrecognized-only override_charge_state = comma delimited list

@wsnoble, do you want to add these two options (`override_charge_mode` and `override_charge_state`) to tide-search irrespectively of handling charge=0.

**Comment by kfattila** [comment]
Welcome back! Today I finally found the code, where charge states are handled in Crux. Currently, this is how crux works.

Charge=0+ and the lack of Charge= are treated differently with pwiz and mstoolkit (mstk).

MsToolKit assigns a charge=0+ in both cases: when charge=0+ or it is missing entirely. Charge=0+ is handled in crux, with a method by Mike MacCoss. This method either (1) assigns a charge state of 1+ or (2) assigns both, charges states 2+ AND 3+. 

In the case of pwiz: 
(A) if the Charge information is missing, then crux again uses Mike's method that is it either (1) assigns a charge state of 1+ or (2) assigns charges states 2+ AND 3+. 
(B) if the charge=0+, then nothing happens, the spectrum is handled as a charge 0+.

@wsnoble, how shall we proceed? Basically, we have everything in crux to handle these situations, we do not need to dig in the external parsers.

**Comment by kfattila** [comment]
For the record: 
1. pwiz handles multiple charge states: If the charge states are defined in the mgf file as `Charge=1+ 2+ 3+` or `Charge=1+ and 2+ and 3+`. pwiz handles them all, but it does not handle comma separated charge states. 
2. mstoolkit only reads the first charge state. and omits all the subsequent charge states.

**Comment by wsnoble** [comment]
I think we should get rid of the old charge state inference code from Mike MacCoss.

We should fully document, in an FAQ entry, how the different parsers handle spectra with multiple charge states.

We should get rid of the `charge-state` option and add the `min-precursor-charge` option.

Then for any spectrum with missing charge or charge of 0, we should search it with all charges from min to max.

**Comment by wsnoble** [comment]
As requested above, we can also add an option

`override-charges = T|F`

If this is set to T, then all spectra are searched in all charge states from min-charge to max-charge.  Otherwise, the default behavior is to search with all charge states only if a spectrum has no charge or charge=0.

**Comment by kfattila** [comment]
This has been handled with the tide-lite PR.
