### ISSUE TITLE
invalid/incorrect characters in percolator pepXML

### ISSUE THREAD

**Issue by jvolkening** [crux-toolkit/crux-toolkit#559]
Hello,

In the percolator pepXML output, crux writes out `peptide_prev_aa` and `peptide_next_aa` attributes in the `<alternative_protein>` elements. There seem to be a few issues with this:

1. Where does this information come from? It's not in the pepXML input file from Comet. Comet only puts these attributes on the parent `<search_hit>` element (e.g. the primary protein reported). As far as I can tell, crux is copying this information to the alternative proteins listed, but that's not always going to be correct.

2. More problematic is that occasionally I'm seeing garbage written to this attribute, including non-print characters like NULL. It doesn't happen very often, but when it does the result is invalid XML which downstream tools choke on. For instance, in the pipeline I ran today it happened in one peptide (two PSMs) in one sample out of eighteen. I observed it in a previous run in three samples out of eighteen. When I have seen it happen it is in very short, low-scoring peptides (5-6 aa), although I don't have a large enough sample size to know if this is significant. Here is an example:

```xml
    <spectrum_query spectrum="HIDDEN" start_scan="89821" end_scan="89821" precursor_neutral_mass="689.2971" assumed_charge="1" index="15265">
    <search_result>
    <search_hit hit_rank="0" peptide="ASPCGR" peptide_prev_aa="M" peptide_next_aa="Q" protein="tr|A0A1D5PJU2|A0A1D5PJU2_CHICK" num_tot_proteins="4" calc_neutral_pep_mass="688.2957" massdiff="+1.0014" num_tol_term="1" num_missed_cleavages="0" num_matched_peptides="428" is_rejected="0" protein_descr="">
        <alternative_protein protein="tr|F1NKP5|F1NKP5_CHICK" protein_descr="" num_tol_term="1"  peptide_prev_aa="'" peptide_next_aa="^@"/> 
        <alternative_protein protein="tr|R4GI43|R4GI43_CHICK" protein_descr="" num_tol_term="1"  peptide_prev_aa="^@" peptide_next_aa="^@"/> 
        <alternative_protein protein="tr|A0A1D5PVX8|A0A1D5PVX8_CHICK" protein_descr="" num_tol_term="1"  peptide_prev_aa="<84>" peptide_next_aa=")"/> 
<modification_info modified_peptide="A[42.01]SPCGR">
<mod_aminoacid_mass position="1" mass="113.05"/>
<mod_aminoacid_mass position="4" mass="160.03"/>
</modification_info>
        <search_score name="percolator_score" value="-0.46992585" />
        <search_score name="percolator_qvalue" value="0.17674419" />
        <search_score name="percolator_PEP" value="0.72337133" />
<analysis_result analysis="peptideprophet">
<peptideprophet_result probability="0.27662867">
<search_score_summary>
<parameter name="percolator_score" value="-0.46992585"/>
<parameter name="qvalue" value="0.17674419"/>
<parameter name="pep" value="0.72337133"/>
</search_score_summary>
</peptideprophet_result>
</analysis_result>
    </search_hit>
    </search_result>
    </spectrum_query>
```

In this case, the `^@` and `<84>` are Vim's representation of non-printing characters.

**Comment by jvolkening** [comment]
Also saw this in the log from the run of the file quoted above:

```
WARNING: Missing cterm flanking aa for protein:tr|A0A1D5PJU8|A0A1D5PJU8_CHICK offset:0
WARNING: Missing nterm flanking for protein:tr|A0A1D5PJU8|A0A1D5PJU8_CHICK offset:0
```

Protein ID doesn't match that of the wonky entry, though.

**Comment by kfattila** [comment]
Crux Percolator now keeps and reports the original Percolator output files, and Crux no longer converts the percolator output files to some crux file format. So, I think, this issue can be closed.
