### ISSUE TITLE
tide-index bug in handling missed cleavages on modified residues

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#565]
A user reported that they were seeing this target peptide in a Tide index with (supposedly) no missed cleavages: MDASEEPLPPVIYTMENKPIVTCAGDQNLFTSVYPTLSQQLPR. Here is the command line:

```crux tide-index --output-dir index-0 --peptide-list T --auto-modifications-spectra export_Mzidentml_F134282.mgf --auto-modifications T --seed time --overwrite T --peptide-list T uniprot-proteome.fasta PXD006856-index-0```

The log file provided indicates that Param-Medic identified the given MGF file as containing SILAC data:

```INFO: Search parameter recommendations:
INFO: SILAC: 4Da separation detected.
INFO: SILAC: 6Da separation detected.
INFO: SILAC: 8Da separation detected.
INFO: iTRAQ: no reporter ions detected
INFO: TMT: no reporter ions detected
INFO: Phosphorylation: not detected
INFO: Variable modification of 4.02511Da on K
INFO: Variable modification of 6.02013Da on K
INFO: Variable modification of 6.02013Da on R
INFO: Variable modification of 8.0142Da on K
```

I guess these variable mods should suppress cleavage.

I located the above peptide and created a FASTA file containing just the first peptide:

```
>sp|P48553|TPC10_HUMAN Trafficking protein particle complex subunit 10 OS=Homo sapiens OX=9606 GN=TRAPPC10 PE=1 SV=2
MDASEEPLPPVIYTMENKPIVTCAGDQNLFTSVYPTLSQQLPR
```
When I run tide-index on this, I get eight target peptides:

```
MDASEEPLPPVIYTMENKPIVTCAGDQNLFTSVYPTLSQQLPR
MDASEEPLPPVIYTMENK[4.03]PIVTCAGDQNLFTSVYPTLSQQLPR
MDASEEPLPPVIYTMENK[6.02]PIVTCAGDQNLFTSVYPTLSQQLPR
MDASEEPLPPVIYTMENKPIVTCAGDQNLFTSVYPTLSQQLPR[6.02]
MDASEEPLPPVIYTMENK[8.01]PIVTCAGDQNLFTSVYPTLSQQLPR
MDASEEPLPPVIYTMENK[4.03]PIVTCAGDQNLFTSVYPTLSQQLPR[6.02]
MDASEEPLPPVIYTMENK[6.02]PIVTCAGDQNLFTSVYPTLSQQLPR[6.02]
MDASEEPLPPVIYTMENK[8.01]PIVTCAGDQNLFTSVYPTLSQQLPR[6.02]
```

The problem is that I don't get the peptides MDASEEPLPPVIYTMENK, which should occur when there is no modification on the K. I should also get PIVTCAGDQNLFTSVYPTLSQQLPR and PIVTCAGDQNLFTSVYPTLSQQLPR[6.02].  Oddly, though there is a variable modification on R as well as K, tide-index does succeed in cleaving after the R.

**Comment by kfattila** [comment]
Is this the new tide-index?

**Comment by wsnoble** [comment]
The initial results above are from the old tide-index, but I just tried it on the branch for the new version and got the same result.

**Comment by kfattila** [comment]
You do not get peptides  MDASEEPLPPVIYTMENK and PIVTCAGDQNLFTSVYPTLSQQLPR because the K is followed by P so the trypsin would not cleave there. Try the enzyme trypsin/P

**Comment by wsnoble** [comment]
Doh! Thanks, Attila.  That should have been obvious to me.

Indeed, with trypsin/p, I verified that the list of target peptides is

MDASEEPLPPVIYTMENK
MDASEEPLPPVIYTMENK[4.03]
MDASEEPLPPVIYTMENK[6.02]
MDASEEPLPPVIYTMENK[8.01]
PIVTCAGDQNLFTSVYPTLSQQLPR
PIVTCAGDQNLFTSVYPTLSQQLPR[6.02]
