### ISSUE TITLE
cascade search index file does not exist

### ISSUE THREAD

**Issue by emmats** [crux-toolkit/crux-toolkit#569]
I am using a previous script that I have edited for a new job run a cascade search. I'm hoping there is something simple that I have overlooked. Maybe I did not make my index files correctly?

I get the following error when I try to run it (I have 3 index files, this is the first):
FATAL: The file /net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/Mcap.coral.eggs.index, does not exist. 

The script can be found here (also pasted below): /net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/cascade.coral.eggs.job 
The script for making the "missing" index file is here: /net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/tide.index.16S.job

Thank you!

crux cascade-search \
   --compute-sp T \
   --overwrite T \
   --output-dir cascade.coral.eggs \
   --num-threads 1 \
   --precursor-window 10 \
   --precursor-window-type ppm \
   --missed-cleavages 2 \
   --mz-bin-offset 0 \
   --mz-bin-width 0.02 \
   --enzyme trypsin \
   --fragment-mass mono \
   --decoy-format peptide-reverse \
   --keep-terminal-aminos C \
   --concat T \
   --top-match 5 \
   --remove-precursor-peak T \
   --remove-precursor-tolerance 15 \
   --use-flanking-peaks F \
   --use-neutral-loss-peaks F \
   --min-mass 200 \
   --max-mass 7200 \
   /net/nunn/vol1/mmudge/2021_01_20_coraleggs/IT/MZML/*.mzXML \
   /net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/Mcap.coral.eggs.index, /net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/symb.coral.eggs.index, /net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/16S.coral.eggs.index

**Comment by wsnoble** [comment]
I think maybe the problem is that you have spaces in your list of index names. There should be no spaces, like this:

```
/net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/Mcap.coral.eggs.index,/net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/symb.coral.eggs.index,/net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/16S.coral.eggs.index
```

**Comment by emmats** [comment]
I've verified that I used the correct fastas for my searches. When we used the first and second fastas from the cascade search in previous Comet searches, we got >2000 PSMs (at 1% FDR). So I'm not sure why my cascade search yielded 0 at 1% FDR.

**Comment by wsnoble** [comment]
Please post your log file from cascade-search.

**Comment by emmats** [comment]
[cascade-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/8612569/cascade-search.log.txt)

**Comment by wsnoble** [comment]
It doesn't look like a catastrophic failure, since you are seeing some PSMs at 5% and 10%.

INFO: Number of PSMs at 1% FDR = 0.
INFO: Number of PSMs at 5% FDR = 162.
INFO: Number of PSMs at 10% FDR = 383

My guess is that your previous Comet search used different parameter settings which led to better performance. I note that you are using raw XCorr score rather than a calibrated score, which may be part of the problem.  Trying Tailor scoring (see the use-tailor-calibration option at http://crux.ms/commands/tide-search.html) might help. I would also recommend setting top-match to 1 instead of 5.

**Comment by emmats** [comment]
I am getting an error that use-tailor-calibration does not exist. My arguments are copied below. I am using crux/3.2-9a35807

crux cascade-search \
   --compute-sp T \
   --overwrite T \
   --output-dir cascade.coral.eggs2 \
   --num-threads 1 \
   --precursor-window 10 \
   --precursor-window-type ppm \
   --missed-cleavages 2 \
   --mz-bin-offset 0 \
   --mz-bin-width 0.02 \
   --enzyme trypsin \
   --fragment-mass mono \
   --decoy-format peptide-reverse \
   --keep-terminal-aminos C \
   --concat T \
   --top-match 1 \
   --remove-precursor-peak T \
   --remove-precursor-tolerance 15 \
   --use-flanking-peaks F \
   --use-neutral-loss-peaks F \
   --min-mass 200 \
   --max-mass 7200 \
   --use-tailor-calibration T \
   /net/nunn/vol1/mmudge/2021_01_20_coraleggs/IT/MZML/*.mzXML \
   /net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/Mcap.coral.eggs.index,/net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/symb.coral.eggs.index,/net/nunn/vol1/emmats/searches/Coral.Eggs.cascade/16S.coral.eggs.index

**Comment by wsnoble** [comment]
Tailor scoring was added in Crux 4.0, as documented in the release notes:

http://crux.ms/release-notes.html

I recommend upgrading to the most recent build of Crux: http://crux.ms/download.html

**Comment by emmats** [comment]
It looks like that is not available on the cluster so I'm just going to have GSIT upgrade and go from there. Thanks!

**Comment by emmats** [comment]
I'm attaching the files resulting from my latest search. I got some PSMs in my 1st database, but none in my second. I have searched the data with the second DB (combined with the 1st) in comet and there were PSMs against the 2nd DB. The 112 I got for my first DB search is still much lower than what I achieved with Comet. Also, why does the search not proceed to the 3rd DB, even if there are no PSMs in the second?
[cascade-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/8635860/cascade-search.log.txt)
[cascade-search.params.txt](https://github.com/crux-toolkit/crux-toolkit/files/8635861/cascade-search.params.txt)
[cascade-search.txt](https://github.com/crux-toolkit/crux-toolkit/files/8635862/cascade-search.txt)

**Comment by wsnoble** [comment]
Cascade-search stops if the number of detections in any step is below a threshold of 20.  This is necessary to ensure valid FDR control. Here is the relevant paragraph from the [original paper](https://pubs.acs.org/doi/full/10.1021/pr501173s):

The minimal identifications threshold k, which is specific to the cascade FDR procedure (line 7, Algorithm 2), guards against situations where an unusually low number of identifications compromises our ability to control the FDR. As noted in a similar, although not identical, setup in ref [12], separate FDR analysis is legitimate if the expected number of identifications is reasonably large. In practice, we found that setting k ∼ 20 seems to guarantee control of the FDR.

As for the difference in search results between Comet and Tide, this likely depends on what parameters you selected for the two algorithms.  The first entry in our FAQ may be helpful here: http://crux.ms/faq.html

**Comment by bmx8177** [comment]
Could you post your Comet parameters? Something might immediately pop out as being different.

**Comment by wsnoble** [comment]
One big difference is that you are searching using a 1 Da bin size with Comet (fragment_bin_tol = 1.0005) and a 0.02 Da bin size with Tide (--mz-bin-width 0.02). Which is correct? 

Can you run `crux param-medic /net/nunn/vol1/mmudge/2021_01_20_coraleggs/IT/MZML/2021_01_20_coraleggs_10B_23.mzXML` and send the resulting log file?

**Comment by emmats** [comment]
The data was collected with an ion trap, not orbitrap, so that is why the Comet bin size is bigger. I should probably change that for the cascade file.
[param-medic.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/8642541/param-medic.log.txt)

**Comment by wsnoble** [comment]
Yes, you definitely need to fix that.

Param-medic didn't get enough data to make its estimate.  Can you try again using

 `crux param-medic /net/nunn/vol1/mmudge/2021_01_20_coraleggs/IT/MZML/*.mzXML`?

**Comment by emmats** [comment]
I've made the changes to the parameters file and am trying again.

**Comment by emmats** [comment]
Here is the most recent param-medic log.
The cascade search with the revised parameters just finished as well and it looks much more promising
[param-medic.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/8643284/param-medic.log.txt)
!

**Comment by wsnoble** [comment]
I would use the param-medic parameters if I were you:

INFO: Precursor error: 35.60 ppm
INFO: Fragment bin size: 0.6279 Th

It looks like your 10ppm setting may be too optimistic.

**Comment by wsnoble** [comment]
Note that in future you can have param-medic set these parameters for you automatically by using `--auto-precursor-window warn` and `--auto-mz-bin-width warn` on your cascade-search command line.

**Comment by emmats** [comment]
Thanks!
