### ISSUE TITLE
Upgrade Percolator to version 3.6

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#570]
Here is the list of changes in Percolator 3.6:

v3.06

    Added extended unit tests.
    Added code for quicker FDR calculation.
    Updated urls to xerces and google test
    Switched compiler to c++11
    Added basic pepXML support.
    Improved testing in Github actions:
        Made separate stages for unit and system tests for Ubuntu
        Introduced a test build for centos
        Moved unit and system tests to release code.
        Changed the dependency structure to gtest
    Added command-line argument to switch off reporting to analytics
    Added possibility to include spectrum file name in tab-delimited input, that is carried over to tab-delimited output.
    Added possibility to include retention time in tab-delimited input.
    Discontinued support of the Elude model
    Removed all retention time modeling and all other DOC features

One thing that is not mentioned above is that Lukas added support for a filename column for tab delimited input and output.
If percolator detects a column named "filename" in input, it will carry over its content to output files.  We should make sure Crux makes use of this.

**Comment by CharlesEGrant** [comment]
It looks like Crux currently won't build on TeamCity with the latest Percolator. src/app/PercolatorAdapter.cpp will need to be updated.

**Comment by wsnoble** [comment]
Yes, I figured as much.  In the interim, while we work on that, can we point Crux to the previous Percolator release?

**Comment by CharlesEGrant** [comment]
Will do.

**Comment by CharlesEGrant** [comment]
Fixed by commit 514a697d350ebf69c84c8843adca4abdeff88d7f. See i[ssue #587 ](https://github.com/crux-toolkit/crux-toolkit/issues/587)
