### ISSUE TITLE
Use Percolator's built-in support for pepxml output

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#584]
Currently, crux percolator produces pepxml by parsing the Percolator text files and then calling psm-convert on them.  Instead, we should use Percolator's built-in support for pepxml output.  In the process, we can disable our attempt to produce mzidentml files. This should significantly simplify the code.  In particular, it will eliminate the need for ifdef's in the Percolator source to do the parsing.

**Comment by wsnoble** [comment]
I expanded this idea to entirely eliminate the post-processing of Percolator results, and instead just allow Percolator to produce its own output files.  The problem is that doing this means we need to update spectral-counts to be able to parse native Percolator tab-delimited files.  I started working on this in [this branch](https://github.com/crux-toolkit/crux-toolkit/pull/585).

**Comment by wsnoble** [comment]
Need to hook the existing pepxml option in Crux percolator to the xmloutput option in standalone percolator.

https://github.com/percolator/percolator/wiki/Command-line-options

**Comment by CharlesEGrant** [comment]
Fixed in commit bc4562e.
