### ISSUE TITLE
discrepancy between tide-search and tide-search target/decoy mapping

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#586]
There is a discrepancy between the target/decoy mapping in the output of tide-search and tide-index. Look at pairing created by the 
'original target sequence' and the 'sequence' column in the search file and compare to the tide-index.peptides.txt file. 

tide-index --missed-cleavages 1 --output-dir tide-index --peptide-list T hsapiens.fasta tide-index
tide-search --precursor-window 35 --score-function xcorr --mz-bin-width 0.02 --num-threads 6 --concat T --top-match 1 --overwrite T --output-dir crux-output test.ms2 tide-index

[hsapiens.fasta.txt](https://github.com/crux-toolkit/crux-toolkit/files/9283902/hsapiens.fasta.txt)
[test.ms2.txt](https://github.com/crux-toolkit/crux-toolkit/files/9283905/test.ms2.txt)

**Comment by kfattila** [comment]
I confirm this bug in the old tide-index. I also confirm that this bug is already fixed in the new tide-index.

**Comment by bmx8177** [comment]
How close are you to merging the new tide-index to main branch? Might not be worth me tracking it down if that merge is close to happening.

**Comment by wsnoble** [comment]
We are quite close. I agree that you should not try to track this down.

**Comment by kfattila** [comment]
@bmx8177, this bug should be fixed in the recent, new tide-index. Could you please check out the latest crux version and check if this bug is still there?

**Comment by bmx8177** [comment]
Confirmed that case above has been fixed
