### ISSUE TITLE
Update to latest Kojak

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#588]
Mike Hoopmann says, "Kojak inside Crux will need to be updated to a more recent release to benefit from the optimizations that Bill and I discussed last week. Particularly, the newer Kojak will remove the alternate localizations for crosslinks, and give a small boost in PSMs in the output from Percolator. "

**Comment by CharlesEGrant** [comment]
This seems to require adding Mike's NeoPepXMLParser as a dependency, which in turn requires adding the [Expat library](https://libexpat.github.io) as a dependency.  Building Expat as part of the Crux build would be complex (I think). It is available as a package on every platform except windows. On Windows it is available as a download with a GUI installer.

**Comment by wsnoble** [comment]
Ugh, adding more dependencies is onerous.  Mike, is there any way we can avoid this, even if it means having less functionality in the Crux version of Kojak?

**Comment by mhoopmann** [comment]
You already have expat. It's been in MSToolkit for a decade or so. Whenever I compile NeoPepXMLParser, I just link MSToolkit.

**Comment by mhoopmann** [comment]
For what it's worth, I was able to complete the Crux installation with Kojak 2.0.0 alpha 22 (and NeoPepXMLParser) doing the following:

1. Cloned NeoPepXMLParser from GitHub. Ran its own Makefile to build libneopepxmlparser.lib
2. Pulled Kojak 2.0.0 alpha 22 from GitHub.
3. Updated the Kojak make dependencies to include (-I) the path to the NeoPepXMLParser code.
4. Updated the Crux make dependencies to link libneopepxmlparser.lib

I did a test run on some data and Crux-Kojak completed without error, reporting version 2.0.0 alpha 22 in the results.

So there shouldn't be any expat issues and pulling down and compiling the NeoPepXMLParser library should be fairly straightforward. Please let me know if you're having any issues.

**Comment by CharlesEGrant** [comment]
Completed in commit [ee228a2](https://github.com/crux-toolkit/crux-toolkit/commit/ee228a2fa9e0b0a727cd0c665fa60e082f98d429)
