### ISSUE TITLE
Allow inclusion of arbitrary charge states in tide-index

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#589]
This is a request from a tide-search user:

> I was looking at some tide-search output files, and noticing that there were a lot of 1+ charge state peptides, which I wouldn't be interested in, and perhaps they could make the results worse.  I thought to limit the charge states searched to 2 and 3, but the --spectrum-charge parameter can be 1, 2, 3, or all, with no option for say --spectrum-charge 2 3.  Have you considered allowing a range of charge states to be searched, or maybe there's a different way to do this?

We should modify the --spectrum-charge parameter to accept a comma-separated list of numbers and only search those specified charge states.

**Comment by kfattila** [comment]
There is a tide search param:

--max-precursor-charge <integer> – The maximum charge state of a spectra to consider in search. Default = 5.

Maybe we just need a --min-precursor-charge param?

**Comment by wsnoble** [comment]
Yes, that makes sense.  If we do that, we can also eliminate the --spectrum-charge option, since at that point it will be unnecessary.

**Comment by wsnoble** [comment]
Resolved with commit 7586f912b25f224324606c50f210741af8bcb5f1
