### ISSUE TITLE
Add support for --protein-name-separator in Percolator

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#599]
This option exists in Percolator but is not currently supported in Crux.

Also, I think the default should be to use a comma instead of tab.

**Comment by kfattila** [comment]
Added. It will be in the perc-no-parse branch.
```
InitStringParam("protein-name-separator", ",",
    "Determines the character to separate the protein IDs in the tab-delimited output format ",
    "Available for all percolator", true);
```

**Comment by wsnoble** [comment]
Charles, what is the status of [issue 630](https://github.com/crux-toolkit/crux-toolkit/issues/630)? Are we still waiting to merge the latest version of Percolator into Crux? I think Percolator fixed this on [April 11](https://github.com/percolator/percolator/issues/343).

**Comment by CharlesEGrant** [comment]
We updated to the latest commit of Percolator on April 12.

**Comment by wsnoble** [comment]
Andy, can you test whether --protein-name-separator currently works in Percolator?

**Comment by bmx8177** [comment]
Yes, --protein-name-separator currently works in Percolator.
