### ISSUE TITLE
aTDC is broken

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#600]
I'm trying to run the average TDC method, but there is a problem. I get an error:
```
INFO: Using a-TDC (5 decoy sets).
FATAL: Missing 1 decoy scores for file 0, scan 2813, charge 2 (expected 5, found 4)
```
I did check the peptides generated, and tide-index successfully managed to generate all the five decoys.  I run tide-search with top-match 1, Concat = F. The truncated outout:
```2813	2	... 88	CNGQGK	1_S_57.02	trypsin-full-digest	decoy_tr|G3V3D6|G3V3D6_HUMAN(255),decoy_sp|Q8WV16|DCAF4_HUMAN(355),decoy_tr|Q86SY2|Q86SY2_HUMAN(185)	RG,RG,RG	decoy	CGNQGK	2
2813	2	...	88	CANNGK	1_S_57.02	trypsin-full-digest	decoy_sp|Q14008|CKAP5_HUMAN(695)	KE	decoy	CGNNAK	0
2813	2	...	88	CNQGGK	1_S_57.02	trypsin-full-digest	decoy_tr|G3V3D6|G3V3D6_HUMAN(255),decoy_sp|Q8WV16|DCAF4_HUMAN(355),decoy_tr|Q86SY2|Q86SY2_HUMAN(185)	RG,RG,RG	decoy	CGNQGK	4
2813	2	... 88	CNNAGK	1_S_57.02	trypsin-full-digest	decoy_sp|Q14008|CKAP5_HUMAN(695)	KE	decoy	CGNNAK	3
```
The first two column is the scan Id and the charge state, the last column is the decoy idx. There were 88 candidate peptides. So, there are four decoy peptides, and they are coming from two different target peptides. Certainly, there is a bug somewhere. But I do not understand, how should tide-index handle multiple decoy per target, in principle?  Note: it works well for most of the other spectra. 

From Bill:
"Are you familiar with the associated [paper](https://pubs.acs.org/doi/10.1021/acs.jproteome.8b00802)? If I understand right, the final column in the output is an index indicating which decoy database the given PSM comes from, right? So in this case we are missing a decoy from database 1? If all five PSMs are present for every scan, then I think assign-confidence should be able to use this information to do aTDC. I would first just preprocess the output file to eliminate scans with fewer than 5 associated PSMs, to make sure aTDC works. Then you can look into why those decoys are missing.  If we can't fix the problem on the indexing side, we may have to modify assign-confidence to skip over those scans. "

**Comment by kfattila** [comment]
I did try aTDC with an old crux, which I compliled a year ago, (before I touched the tide-index and tide-search code), and aTDC  already breaks with this old version of crux. Therefore, I do not break something in tide-index while upgrading it. 

The problem is that, tide-index successfully generates the desired amount of decoy peptide-per-target, now it is 5, and tide-index indexes them from 1-5 consequently. The problem is that tide-search fails to find all he decoy PSMs in its internals data containers. 

Bill could you please preproduce this bug, maybe I specified some parameters incorrectly.

**Comment by wsnoble** [comment]
I was able to reproduce this error with the current version of Crux, and also run aTDC successfully with a version from December, 2021. I will send details by slack.

**Comment by kfattila** [comment]
From Bill: "I noticed is that the decoys for a given peptide are all different from one another. This is not correct. The decoys can be repeated in different decoy databases. When we check for duplicates, we just want to be sure that the newly generated decoy does not occur in the target database or in the current decoy database."

**Comment by wsnoble** [comment]
I pushed edits to the documentation yesterday on this branch.  However, I still have four tests that fail:

```
Failing Scenarios:
cucumber features/diameter.feature:14 # Scenario Outline: User runs diameter, Examples (#1)
cucumber features/diameter.feature:15 # Scenario Outline: User runs diameter, Examples (#2)
cucumber features/tide-search.feature:48 # Scenario Outline: User runs tide-index / tide-search, Examples (#21)
cucumber features/tide-search2.feature:24 # Scenario Outline: User runs tide-search, Examples (#3)

160 scenarios (4 failed, 156 passed)
1259 steps (4 failed, 1255 passed)
6m16.161s
```

The attached patch is from a `git diff` after I update the good_results directory so that all tests pass on CentOS7. Not sure if this is helpful to check in.

[diffs.txt](https://github.com/crux-toolkit/crux-toolkit/files/9842125/diffs.txt)

**Comment by kfattila** [comment]
Can you send me the diff for tide-ppmwin.txt? I do not expect changes there either.

**Comment by wsnoble** [comment]
It’s in the diff.txt that I posted above.
