### ISSUE TITLE
statistics over the last 32 weeks

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#606]
The "Crux weekly usage by MS proteomics community over the last 32 weeks (in thousand runs)." statistics on the front page of crux.ms says the stats are for the year 2018! see: crux.ms

**Comment by CharlesEGrant** [comment]
Our TeamCity build system had a script written by Rita for updating the Crux usage data. I've now ported the script into the default build action for the crux-toolkit/crux-toolkit.github.io action. The user data will be updated on every commit to that repository, or it can be manually updated by clicking on the "Run workflow" button for the update-usage-statistics action. We should consider automatically running it on a weekly basis.
