### ISSUE TITLE
Fix how start_scan is handled in parsing MGF files

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#607]
Copying this content from an issue [here](https://github.com/wenbostar/PDV/issues/42#issuecomment-1297519317):

> I tested Crux v4.1, the current version of PDV works well with mzML/pepXML, mzML/mzid, mzXML/pepXML, mzXML/mzid files. I added a few examples generated using Crux v4.1 to the [README [github.com]](https://urldefense.com/v3/__https://github.com/wenbostar/PDV*database-searching__;Iw!!K-Hz7m0Vt54!nAH16y0vaWXxkenOqsqj5XkSuZHdmfqpfQYP3Sl_Rm1R06irEqmJUZ4yqpHWgJocgNUPt1hIrsEBK-I6o4lbTY0$).

> For MGF input, it looks like the spectrum ID mapping for both pepXML and mzid outputs was changed in v4.1 so PDV cannot parse the result sucessfully in some cases.

> So far, I found the start_scan was assigned differently with different head formats of MGF:

>    When there is no SCANS in MGF and it looks like scan number cannot be parsed from TITLE by Crux, start_scan is an ordinal number of spectrum in mgf file;
>    When there is no SCANS in MGF and TITLE is in a format like "TITLE=SF_200217_U2OS_TiO2_HCD_OT_rep1.1501.1501.2", start_scan is scan number parsed from the title (1501 for TITLE=SF_200217_U2OS_TiO2_HCD_OT_rep1.1501.1501.2);
>     When there is SCANS in MGF, start_scan is scan number from SCANS.

> Considering different spectra may have the same scan number when a MGF file is combined from multiple MGF files, I would suggest to always assign start_scan as the ordinal number of spectrum in mgf file. Using a consistent way for spectrum mapping for the same format of MS/MS data will make users parse the result easier.

Can we make this change, or is this handled by pwiz?

**Comment by kfattila** [comment]
@wsnoble, I took a look at this issue and I check the code, but I do not really understand, what is the issue here. Can we discuss it during the meeting?

**Comment by wsnoble** [comment]
Here is what I'd add as an FAQ:

**Q: What is the difference between "scan ID" and "scan index"?**

The scan ID is an integer assigned by the mass spectrometer during acquisition. Typically, this value is reported in the input file and carried through to the Tide output file. However, some input formats (notably, MGF) do not explicitly support scan IDs.  The parsers used by Crux (Proteowizard and mstoolkit) may attempt to retrieve the scan ID from the "TITLE" line of the MGF file, but in some cases the scan ID is not provided at all.  Therefore, to ensure that users and downstream applications always have access to an integer index, Tide always also reports a "scan index."  This is simply the ordinal index (starting from 1) of the scan in the given input file.
