### ISSUE TITLE
distinct matches/spectrum when num-decoys-per-target > 1

### ISSUE THREAD

**Issue by freejstone** [crux-toolkit/crux-toolkit#610]
Hi there,

If I am recalling correctly, a previous version of crux-tide produced different `distinct matches/spectrum` in the target and decoy search.txt files when `--concat F`. I believe this is fixed, but now if the user specifies more than one set of decoy indices using `--num-decoys-per-target`, then the `distinct matches/spectrum` value scales according to the number of decoy indices. This can 
 be problematic if a user filters for one of the decoy indices, and creates a pin file for subsequent use in crux percolator, as the `lnNumSP` value will be much higher for decoys than targets.

I have attached the target and decoy search files from a separate search from tide-index where I used `--num-decoys-per-target 3`. For the scan ID 10365, there are 446 distinct matches/spectrum in the decoy file while only 152 for the target file.

[dcy_sep0.tide-search.decoy.txt](https://github.com/crux-toolkit/crux-toolkit/files/10048934/dcy_sep0.tide-search.decoy.txt)
[dcy_sep0.tide-search.target.txt](https://github.com/crux-toolkit/crux-toolkit/files/10048936/dcy_sep0.tide-search.target.txt)

Cheers,

Jack

**Comment by freejstone** [comment]
FWIW I realise that there is an issue already an issue for the fact that using `--num-decoys-per-target` under reports the number of decoy PSMs for each decoy index compared to the target PSMs. I thought this was a "different" enough issue to report, but if not feel free to close this issue.

**Comment by wsnoble** [comment]
I am confused by this: "This can
be problematic if a user filters for one of the decoy indices, and creates a pin file for subsequent use in crux percolator, as the lnNumSP value will be much higher for decoys than targets."

Isn't the conclusion simply that the user shouldn't do this? Are you suggesting that the behavior should be to report the number of matches only in the first database?

**Comment by freejstone** [comment]
> The current value is indeed the number of decoys that are searched against, though the search results are reported separately

So that I understand, say there are 3 decoys for every target, is each scan searched against the 3 decoy databases combined? And then you report the best scoring PSM against each index separately?  In the above scenario, I did anticipate that each scan would get 3 ``distinct matches/spectrum` values, one for each decoy database. In saying that I am happy for my issue to be disregarded, since it sounds like it might be a matter of preference. I doubt as well if general users really spend much time considering these values in the context of more than one decoy (myself being probably the only exception).

Cheers,

Jack

**Comment by wsnoble** [comment]
OK, I looked into this some more, and now I understand your thinking better.  Since the tide-search.decoy.txt file contains a "decoy index" column indicating which decoy database the PSM comes from, it makes sense to report the distinct matches/spectrum on a per-database basis. This is also the only way one could hope to use Percolator with such a file. Attila, can you comment on whether this is feasible?

**Comment by wsnoble** [comment]
Jack, can you please check that all of your "distinct matches/spectrum" entries are evenly divisible by the number of database?

Attila, what do you think about doing the division before reporting the value to the user? As its currently implemented, these results files can't be used with Percolator. (OTOH, if you really did want to use Percolator, then you probably shouldn't be doing multi-decoy searching ...)

Bill

**Comment by freejstone** [comment]
In the attached file, the number in the `distinct matches/spectrum` column for scan 10365 is 446, which is not divisible by 3. But is the lack of divisibility a bug? I don't expect tide-index to yield 3 distinct decoys every time.

**Comment by wsnoble** [comment]
Ah, but "distinct" here just applies within each database, not across databases.  We should see exactly the same number of distinct decoys in each database. Can you verify that you used `--allow-dups T` and `--concat F`?

**Comment by freejstone** [comment]
Oh, Sorry I did not properly read Attila's comment regarding `--allow-dups`. The search results are for `--allow-dups F`, which explains why the reported numbers are not divisible by 3.

**Comment by kfattila** [comment]
If you use ```--allow-dups F``` or ``--concat T``` then the assign-confidence program cannot carry out the aTDC method, and it would halt with an error message. So, I am wondering then what is the purpose of ``--num-decoys-per-target>1```? The `--num-decoys-per-target` triggers the aTDC calculation in the `assign-confidence` program. If you dont intend to use it, perhaps you should use `--num-decoys-per-target=1`
 
I would not recommend dividing the `number of matches` with the `number-of-decoys-per-target` because the number of distinct matched would not indicate the actual number of matches.

**Comment by freejstone** [comment]
I see. My original intention was not for standard use. I wanted to use `--allow-dups F`, `--concat F`, `--num-decoys-per-target>1` as I was investigating multiple decoy competition (which is not supported in crux, but I just needed several decoys for each target and I was going to do the rest). I simultaneously wanted to observe Percolator's performance using one of the decoy indices, when I realised that even though each spectrum was searched against each decoy index separately, the `distinct matches/spectrum` was taken over all the decoy indices together.

I doubt this will be a problem for anyone using crux as intended.

**Comment by wsnoble** [comment]
OK, now that we've got this sorted out, I'm going to close out this issue. Let us know if you have more questions.
