### ISSUE TITLE
Change tide-search to specify PTMs with higher precision

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#611]
The precision of mass modifications should be 4 decimal places, not 2.

**Comment by kfattila** [comment]
From tide-search:
```
Amino acid modifications
--mod-precision <integer> – Set the precision for modifications as written to .txt files. Default = 2.
```

Does this work? Did you try?

**Comment by wsnoble** [comment]
Ah, I couldn't find that one. I was looking under "Input and output" and only saw --mass-precision. I guess all we need to do is change the default value from 2 to 4 and then update the smoke tests.  There are several standards that require four digits.

**Comment by wsnoble** [comment]
I will make a PR for this.
