### ISSUE TITLE
search_enzyme_number=11 out of range (0-10)

### ISSUE THREAD

**Issue by freejstone** [crux-toolkit/crux-toolkit#614]
The current version of standalone Comet allows for no digestion of the proteins by setting `--search_enzyme_number  11`. However, when I set this, in Crux Comet I get the following error message:

crux comet --decoy_search 0 --output_percolatorfile 1 --overwrite T --search_enzyme_number 11 combined_ISB18.mzML tide-index/index-0/combined_target_decoy.fasta
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
WARNING: The file 'crux-output/comet.log.txt' already exists and will be overwritten.
INFO: CPU: AY3NPWH1QXJ
INFO: Crux version: 4.1-4ff75ee-2022-09-28
INFO: Wed 30 Nov 2022 16:43:38 AEDT
INFO: Beginning comet.
FATAL: search_enzyme_number=11 out of range (0-10)

Cheers,

Jack

**Comment by CharlesEGrant** [comment]
Fixed in commit [d5bcef0](https://github.com/crux-toolkit/crux-toolkit/commit/d5bcef000b084135c9782fecb0b254e0bda86c4a). Just needed to add No_cut line to Crux code in src/parameter.cpp:116.
