### ISSUE TITLE
Param-medic reported total spectra different to actual number of spectra

### ISSUE THREAD

**Issue by freejstone** [crux-toolkit/crux-toolkit#618]
While running Param-medic (within the call to tide-search) it reports the total number of spectra processed as 234692, while the beginning of tide-search reports a total of 62330 spectra (see log file attached). The actual number in the mgf file is 62330. Is the number of reported by param-medic a bug? Or is it duplicating spectra and testing the duplicates at varying parameter settings?

[Ecl_2022_1214_neo_pepsep_150um_30cm_1-9_TRX-DDA-Xray-HEMa-T1-FR0_91_narrow.tide-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10365564/Ecl_2022_1214_neo_pepsep_150um_30cm_1-9_TRX-DDA-Xray-HEMa-T1-FR0_91_narrow.tide-search.log.txt)

Jack

**Comment by wsnoble** [comment]
I verified this behavior with a tiny MGF file containing just two spectra:

```
$ crux param-medic sample.mgf 
INFO: Writing results to output directory 'crux-output'.
INFO: CPU: pyrrolysine.gs.washington.edu
INFO: Crux version: 4.1-2fab3c91-2022-11-09
INFO: Mon Jan  9 16:57:50 PST 2023
INFO: Beginning param-medic.
INFO: param-medic processing input file sample.mgf...
INFO: 
INFO: Search parameter recommendations:
INFO: Processed 8 total spectra
```

Looking at the code, it seems like param-medic is counting each spectrum multiple times, by considering different charge states. Indeed, if you specify a single value for `pm-charge-state`, then the number is correct:

```
$ crux param-medic --overwrite T --pm-charges 2 sample.mgf
WARNING: The output directory 'crux-output' already exists.
Existing files will be overwritten.
WARNING: The file 'crux-output/param-medic.log.txt' already exists and will be overwritten.
INFO: CPU: pyrrolysine.gs.washington.edu
INFO: Crux version: 4.1-2fab3c91-2022-11-09
INFO: Mon Jan  9 17:01:23 PST 2023
INFO: Beginning param-medic.
WARNING: The file 'crux-output/param-medic.txt' already exists and will be overwritten.
INFO: param-medic processing input file sample.mgf...
INFO: 
INFO: Search parameter recommendations:
INFO: Processed 2 total spectra
```


[sample.mgf.txt](https://github.com/crux-toolkit/crux-toolkit/files/10378058/sample.mgf.txt)
