### ISSUE TITLE
construction of decoy sequences with variable modifications appear to differ new tide-index version

### ISSUE THREAD

**Issue by freejstone** [crux-toolkit/crux-toolkit#619]
From our Slack discussion:

> I noticed that the way tide-index (I believe) creates decoys has slightly changed when variable modifications are considered. Before the recent version, a target peptide, say, PEPTIDE, would have the decoy, say, TPEPIDE, and all applications of variable modifications on this decoy peptide would still have the same sequence of amino acids so TPEP[15.99]IDE might pair with the target P[15.99]EPTIDE. But I notice that this has now changed, and all "versions" of the decoys have a different amino acid sequence.

Attached is the fasta file, log file, and peptide list of an example. As you can see while the target VASMEK has the decoy VEASMK, the target VASM[15.99]EK has the decoy VAM[15.99]SEK.

[example.fasta.txt](https://github.com/crux-toolkit/crux-toolkit/files/103799
[tide-index.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10379944/tide-index.log.txt)
[tide-index.peptides.txt](https://github.com/crux-toolkit/crux-toolkit/files/10379945/tide-index.peptides.txt)
42/example.fasta.txt)

Thanks,

Jack

**Comment by kfattila** [comment]
Hi Jack,

I confirm that the decoy generation has slightly changed for modified peptides and your observation is correct. Unmodified and modified peptides are considered different. What is your issue?

A.
