### ISSUE TITLE
Using multiple decoys with --concat F does not give one PSM for each decoy database.

### ISSUE THREAD

**Issue by freejstone** [crux-toolkit/crux-toolkit#621]
Hi Crux team,

I am using the following command in tide-index:

`crux tide-index --num-decoys-per-target 4 --overwrite T --output-dir index --peptide-list T --seed 0 --overwrite T uniprot-compressed_true_download_true_format_fasta_query__28_28prote-2023.01.03-00.39.10.70.fasta index`

I anticipate that the subsequent tide-search using this index would generate a decoy search file, containing 4 psms for each scan if `--concat F` (one for each decoy database). There might be exceptions to this of course: e.g. if there are too few candidates in the precursor window (that is if `distinct matches/spectrum` is small). However in the attached example, there are only 22094 scans that have 4 psms, while 37064 scans have fewer than 4 psms.

I have attached the decoy search file, the tide index log and the tide search log. Please let me know if there is anything else I can do.

Jack

[narrow_single.tide-search.decoy.txt.zip](https://github.com/crux-toolkit/crux-toolkit/files/10415734/narrow_single.tide-search.decoy.txt.zip)
[tide-index.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10415736/tide-index.log.txt)
[narrow_single.tide-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10415738/narrow_single.tide-search.log.txt)

**Comment by wsnoble** [comment]
I think you have to use `--allow-dups T`.  Can you try this?

**Comment by freejstone** [comment]
Looks like I am running into the same problem. I get 22228 scans with 4 psms and 36930 scans with less than 3 psms.

[tide-index.log.txt](https://githu
[narrow_single.tide-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10415833/narrow_single.tide-search.log.txt)
b.com/crux-toolkit/crux-toolkit/files/10415830/tide-index.log.txt)
[narrow_single.tide-search.decoy 2.txt.zip](https://github.com/crux-toolkit/crux-toolkit/files/10415834/narrow_single.tide-search.decoy.2.txt.zip)
[Uploading narrow_single.tide-search.decoy.txt.zip…]()

**Comment by wsnoble** [comment]
Can you send the peptide list?

**Comment by freejstone** [comment]
It is still 50MB compressed, can I share it with you over Slack?

**Comment by wsnoble** [comment]
OK, so the index does indeed contain four decoys for every target, as shown by this command:

```
$ awk -F "\t" 'NR > 1 {print $2}' tide-index.peptides.txt | awk -F "," '{print NF}' | sort -u
4
```

Can you pull out one scan that gives you three PSMs and send the mgf, the log file, and the output file?

**Comment by freejstone** [comment]
Yes sure. I have attached the mgf containing the single scan with 3 PSMs, the log file and output decoy file. Let me know if you need anything else.
[Ecl_2022_1214_neo_pepsep_150um_30cm_1-9_TRX-DDA-Xray-HEMa-T1-FR0_91_scan_12706.mgf.txt](https://github.com/crux-toolkit/crux-toolkit/files/10416237/Ecl_2022_1214_neo_pepsep_150um_30cm_1-9_TRX-DDA-Xray-HEMa-T1-FR0_91_scan_12706.mgf.txt)
[narrow_single_one_scan_thread_3.tide-search.decoy.txt](https://github.com/crux-toolkit/crux-toolkit/files/10416238/narrow_single_one_scan_thread_3.tide-search.decoy.txt)
[narrow_single_one_scan_thread_3.tide-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10416239/narrow_single_one_scan_thread_3.tide-search.log.txt)

**Comment by wsnoble** [comment]
Looking at the last column, it looks like you got decoys from the first three indices (0, 1, 2) but not the last one (index 3). My hunch is that this is related to how Tide fails to handle ties properly. We will look further into this.

**Comment by kfattila** [comment]
It is strange that all decoys (0-2)  were generated

**Comment by kfattila** [comment]
@freejstone, can you send me the data you have to reproduce your bug? Thanks. A.

**Comment by freejstone** [comment]
Yes sure, attached is the fasta file and the single-scan mgf. Let me know if you like the complete mgf, I can upload it somewhere for you to download (it is ~ 1 GB).
[uniprot-compressed_true_download_true_format_fasta_query__28_28prote-2023.01.03-00.39.10.70.fasta.txt.zip](https://github.com/crux-toolkit/crux-toolkit/files/10430361/uniprot-compressed_true_download_true_format_fasta_query__28_28
[Ecl_2022_1214_neo_pepsep_150um_30cm_1-9_TRX-DDA-Xray-HEMa-T1-FR0_91_scan_12706.mgf.txt](https://github.com/crux-toolkit/crux-toolkit/files/10430366/Ecl_2022_1214_neo_pepsep_150um_30cm_1-9_TRX-DDA-Xray-HEMa-T1-FR0_91_scan_12706.mgf.txt)
prote-2023.01.03-00.39.10.70.fasta.txt.zip)

**Comment by kfattila** [comment]
I wasn't able to reproduce your bug. I have clone a fresh copy of crux, I compiled and it works for me, i.e., it reports all the four decoys.  I used this script:
```
#!/bin/sh

DATA=./Ecl_2022_1214_neo_pepsep_150um_30cm_1-9_TRX-DDA-Xray-HEMa-T1-FR0_91_scan_12706.mgf
FASTA=./uniprot-compressed_true_download_true_format_fasta_query__28_28prote-2023.01.03-00.39.10.70.fasta

CRUX=./src/crux

$CRUX tide-index --allow-dups T --num-decoys-per-target 4 --overwrite T --output-dir index-dups --peptide-list T --seed 0 --overwrite T $FASTA peptide-index

$CRUX tide-search  --auto-precursor-window warn --auto-mz-bin-width warn --top-match 1 --use-tailor-calibration T --concat F --overwrite T --num-threads 3 --pin-output T $DATA peptide-index

```
[tide-index.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10434462/tide-index.log.txt)
[tide-search.decoy.txt](https://github.com/crux-toolkit/crux-toolkit/files/10434463/tide-search.decoy.txt)
[tide-search.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10434464/tide-search.log.txt)
[tide-search.target.txt](https://github.com/crux-toolkit/crux-toolkit/files/10434465/tide-search.target.txt)

**Comment by freejstone** [comment]
Interesting. I redid the tide-index and tide-search myself and still get the same issue. I am using Crux version: 4.1-05bc272-2022-11-01, which is only a couple of months old. I will try downloading a fresh version of Crux and redoing tide-index/tide-search and see if that helps.

**Comment by freejstone** [comment]
I just checked and it works fine using the newest version of Crux.

**Comment by kfattila** [comment]
Great!
