### ISSUE TITLE
No terminal mods

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#623]
I ran a search using n-terminal mods, but none showed up. I don't know if it's because they are not actually getting created in the index, or are not being used in the search step.

[tide-index.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10450364/tide-index.log.txt)
[Bacillus-subtilis.fasta.txt](https://github.com/crux-toolkit/crux-toolkit/files/10450432/Bacillus-subtilis.fasta.txt)
[pipeline.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10450525/pipeline.log.txt)

MGF files are [here](https://noble.gs.washington.edu/internal/data/crux-datasets/2017tran-denovo/Bacillus-subtilis/)

**Comment by kfattila** [comment]
This log file is very old. It is from September. And you used a build from aug. we had a similar bug and we already fixed it. Could you please update your crux to the latest version and try again?

**Comment by kfattila** [comment]
See GitHub issue #603.
