### ISSUE TITLE
Tide-search combining options 'peptide-centric-search' and 'use-tailor-calibration' fails to put Tailor Scores into output

### ISSUE THREAD

**Issue by mpiqueca** [crux-toolkit/crux-toolkit#625]
Combining the options to do 'peptide-centric-search T' and 'use-tailor-calibtation T' results in a tide-search.target.txt that has the "tailor score" field in the header line, but no Tailor Scores are present in the body.  The two files are identical except for the header line; neither contains any Tailor Scores.  I'm attaching the first 10 lines of each.

Command used:
```
crux tide-search \
    --mz-bin-width 1.0005079 \
    --peptide-centric-search T \
    --use-tailor-calibration T \
    --output-dir Tideout \
    Fille.ms2 \
    TideIndexFile
```
changing only the use-tailor-calibration between the two runs.

Crux version:
```
INFO: Beginning version.
====================
Crux version 4.1-f575777-2023-01-13
====================
Proteowizard version 3.0.23013
====================
Percolator version 3.06.0, Build Date Jan 13 2023 19:33:34
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas KÃ¤ll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
====================
Comet version 2022.01 rev. 2
====================
Boost version 1_76
====================
INFO: Elapsed time: 0.000109 s
```
Attached files:

[tide-search.target.TailorScoreF.head.txt](https://github.com/crux-toolkit/crux-toolkit/files/10483635/tide-search.target.TailorScoreF.head.txt)
[tide-search.target.TailorScoreT.head.txt](https://github.com/crux-toolkit/crux-toolkit/files/10483637/tide-search.target.TailorScoreT.head.txt)

**Comment by wsnoble** [comment]
I reproduced this behavior.  See the attached zip file for an example.  Also, with peptide-centric=T, the "file" column disappears.

[sample.zip](https://github.com/crux-toolkit/crux-toolkit/files/10483997/sample.zip)

**Comment by kfattila** [comment]
I think when tailor-calibration is used with peptide centric search, tide should halt with a fatal error message. Is that ok? I never tried or tested with peptide centric null distribution. @wsnoble What do you think?

**Comment by bmx8177** [comment]
That reminds me. Attila's proposal is also what we do with combined p-value. We throw an error message saying it is not implemented yet.

**Comment by wsnoble** [comment]
Ah, good point, Attila. I hadn't thought about this in any detail, but you're right that the Tailor calibration assumes a spectrum-centric approach.  It might be adaptable to work with peptide-centric scoring, but verifying that would be its own research project. Michael, you will need to either not do peptide-centric searching (which is what I recommend) or only use XCorr.

Attila, if you want to make this change, I can review the pull request.
