### ISSUE TITLE
Percolator proteinIDs column missing

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#629]
The proteinIds column appears to be missing when running Percolator within Crux.

~/bin/crux-toolkit/Release/src/crux percolator tide-search.txt

[percolator.target.psms.txt](https://github.com/crux-toolkit/crux-toolkit/files/10523950/percolator.target.psms.txt)
[tide-search.txt](https://github.com/crux-toolkit/crux-toolkit/files/10523953/tide-search.txt)

**Comment by wsnoble** [comment]
I think this is a bug in percolator related to the protein-name-separator option.  One quick fix would be to get rid of this option from the percolator command line in crux:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/22529318/215234917-5ef93897-41c9-488e-bb58-8ce38f19ce3f.png">

Of course, the better option is to upgrade Percolator to include this fix. I'm pretty sure Lukas fixed this recently, but I'm not sure it's in a tagged percolator release yet.

**Comment by bmx8177** [comment]
Note to self. Check if smoke-test has test for spectral counts

**Comment by bmx8177** [comment]
Took a look at this and I'm currently confused.

It appears that there is a bug in Percolator. When I give Percolator a pin file (from Crux) and run it with default parameters, I get mostly an empty proteinIDs column. Any peptide that only comes from a single protein is empty. However, the proteinIDs value is populated when a peptide is found in multiple proteins.

**Comment by bmx8177** [comment]
It looks like Attila posted a similar issue already.

https://github.com/percolator/percolator/issues/342

**Comment by wsnoble** [comment]
Attila verified that after the recent Percolator update, this problem has been fixed.
