### ISSUE TITLE
Spectral Counts do not work with current Percolator Output

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#630]
May need to fix issue #629 first

[spectral-counts.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/10524248/spectral-counts.log.txt)
[percolator.target.psms.txt](https://github.com/crux-toolkit/crux-toolkit/files/10524249/percolator.target.psms.txt)

**Comment by bmx8177** [comment]
Confirmed that spectral cnt runs without syntax errors after Percolator protein ID bug fix.

Next need to confirm whether we are getting the correct results. 

Things to do
1) replace --protein-name-separator default from comma to tab so that it matches what make-pin gives as output file. Note that I can't figure out how to pass \t - so far only works with actual tab
2) @CharlesEGrant - It appears that you commented out most of the spectral count smoke tests. Can you comment on why?

**Comment by wsnoble** [comment]
I think we commented them out when they broke a while back. There is a separate issue to revive them. But I think you should do this with your pull request. There will not be any known good results to compare with.

**Comment by bmx8177** [comment]
ok - I figured out what the issue is when --measure=RAW. Spectral counts expects that protein IDs are separated by a comma while Percolator currently separates protein IDs by a tab. I currently can't fix b/c

1) --protein-name-separator argument in Percolator appears to be broken
2) I can't figure out where in the code base spectral counts reads in input files.

**Comment by wsnoble** [comment]
Andy, did you see [this](https://github.com/crux-toolkit/crux-toolkit/issues/599#issuecomment-1548524581)? Can you confirm that you are using the very latest version of Crux?

**Comment by bmx8177** [comment]
I am using the latest version of Crux. I can confirm that --protein-name-separator currently works in Percolator. After some diffing I think the problem is in make-pin. The make-pin automatically uses tab as the protein ID separator and I don't believe there is a parameter to change it.

**Comment by bmx8177** [comment]
see line 338 in PinWriter.cpp. You can see that the tab is hard coded.
I'm don't know why it is like that.

**Comment by wsnoble** [comment]
I'm pretty sure it was hard coded back before the protein-name-separator option existed in Percolator.


Seems like an easy fix, though, right?  Can't you just pull the correct separator from the params object and use that in line 338.

**Comment by bmx8177** [comment]
Not exactly. I think src/app/SpectralCounts.cpp expects that the protein ID separator is a comma. I could change src/app/SpectralCounts.cpp so that it also  looks at the params object. However, I am unable to find the relevant part of the code where the percolator input is actually read.

In any case - the easy fix is to change the hard code to a comma. I am confirm and tested that the raw spectral counts code runs correctly once I do that. 

If you are ok with this I will test the other types of quant such as NSAF, dNSAF, etc.

**Comment by wsnoble** [comment]
I am OK with that.

**Comment by bmx8177** [comment]
Got 4 out of 10 additional smoke tests working.

Realized that normalized spectral count score (SI_n) does not work b/c the input need a scan column. The current percolator output does not contain it at the moment (at least by itself). Need to edit MatchFileReader::parse so that it can read in Percolator files (as Bill noted in line 178 last year).

**Comment by bmx8177** [comment]
@wsnoble Does Percolator still output pepXML files? A number of the old spectral count smoke test use pepXML as input but I don't see it as an output option. Could be missing something though.

Note we probably need to remove pepxml-output as a Percolator parameter as it does nothing right now (and update documentation). <- assuming pepXML is not supported by Percolator anymore.

**Comment by wsnoble** [comment]
No, Percolator does not produce pepXML.  Can you remove that parameter as part of your work on spectral-counts?

**Comment by bmx8177** [comment]
Determine if assign-confidence can output pepxml (documentation say it does not). If assign-confidence does not output pepxml, consider removing spectral counts smoke tests that use it as input.

Add code to  assign-confidence so that it can be used as input into spectral-count. Need to update documentation to reflect this. Add smoke test for this case as well.

**Comment by bmx8177** [comment]
From Bill
"On second thought, if we can support peptideprophet, that seems like a Good Thing. Do you want to check whether peptideprophet still outputs pepxml and whether the smoke tests can be easily updated to work with it?"

**Comment by bmx8177** [comment]
@wsnoble I currently have a working version of spectral counts (in that all smoke test pass). However, I have not had time to look at the other spectral count bug reports that were recently assigned to me. I think it would be worth it to do a PR now so we can push a fixed version of spectral counts. I can then work through the reminder of the bug reports. What do you think?

**Comment by wsnoble** [comment]
Yes, can you submit a PR for review? Please be sure to update the release notes to reflect any bug fixes.

**Comment by bmx8177** [comment]
This has been fixed with the most recent merge (pull request #660)
