### ISSUE TITLE
mix-max FDR threshold incorrect

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#632]
@sjust-seerbio found this in Crema code. We should fix in assign-confidence.

This logic gives incorrect q-values. It results in large q-values being propagated to more relaxed score cutoffs, when the correct implementation propagates small q-values to stricter score cutoffs.

https://github.com/crux-toolkit/crux-toolkit/blob/90582211ef4e7c3b16526f0315ae28426f2492e1/src/app/AssignConfidenceApplication.cpp#L1232-L1237

**Comment by kfattila** [comment]
How did it work so far? It looks like mix-max would report only 1.0 q values.

**Comment by bmx8177** [comment]
It does not report only 1.0 qvalues.

Note that fdrmod list starts with largest FDR and ends with smaller FDR. However, the loop it is a part of starts at high index and goes to low index (line 1210).

If fdrmod = [1.0, 0.8, 0.9, 0.8, 0.7, 0.5, 0.6, 0.7, 0.7]

Current code yield [1, 0.8, 0.7, 0.7 0.7, 0.7, 0.7, 0.7, 0.7]

I believe correct code should yield: [1, 0.8, 0.8, 0.8, 0.7, 0.5, 0.5, 0.5, 0.5]

Hopefully that make sense? The solution would be to move these couple of lines outside this loop and into another loop

**Comment by kfattila** [comment]
I checked the assign confidence smoke tests for mix-max. The expected results looked good. I'll keep digging it tomorrow.

**Comment by kfattila** [comment]
@bmx8177, why do you think, can I merge?

**Comment by bmx8177** [comment]
Yes you can go ahead a merge. Smoke tests pass
