### ISSUE TITLE
I thought I'd take a look at this with Valgrind's threading error tool, helgrind. I haven't identified the problem yet but I do see that if I run:

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#636]
I thought I'd take a look at this with Valgrind's threading error tool, helgrind. I haven't identified the problem yet but I do see that if I run:

`valgrind --tool=helgrind src/crux tide-search --overwrite T ../doc/user/example-files/demo.ms2 ../doc/user/example-files/small-yeast.fasta`

Helgrind doesn't flag any errors. However, if I run

`valgrind --tool=helgrind src/crux tide-search --overwrite T --compute-sp T ../doc/user/example-files/demo.ms2 ../doc/user/example-files/small-yeast.fasta
`
Helgrind flags multiple errors. Maybe the problem is specific to the '--compute-sp T' option?

Info about helgrind [here](https://valgrind.org/docs/manual/hg-manual.html#hg-manual.overview).

_Originally posted by @CharlesEGrant in https://github.com/crux-toolkit/crux-toolkit/issues/407#issuecomment-1059443431_

**Comment by kfattila** [comment]
@CharlesEGrant reported 1-2 years ago that valgrind reports memory leak in sp-computation. I don't remember exactly what Charles said but I found memory leak issue in sp-computation and it is fiex with my latest PR. Maybe Charles, could you please confirm with valgrind that the memory leak is gone?

**Comment by CharlesEGrant** [comment]
Using the command

valgrind --tool=helgrind src/crux tide-search --num-threads 4 --overwrite T --compute-sp T ../doc/user/example-files/demo.ms2 ../doc/user/example-files/small-yeast.fasta &> crux.log

hellgrind is still complaining about dozens  and dozens of possible data race issues.  I don't know if these are serious errors. A sample of one error below

==29556== Possible data race during read of size 8 at 0x4EFD600 by thread #6
==29556== Locks held: none
==29556==    at 0x6A4B28: myrandom() (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6A4C87: myrandom_limit(int) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6DB56C: SpSpectrum::ExtractPeaks(int) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6DBBD9: SpSpectrum::PreprocessSpectrum(Spectrum const&, int) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6E42ED: SpScorer::SpScorer(Spectrum const&, int, double) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6871E3: TideMatchSet::report(std::basic_ofstream<char, std::char_traits<char> >*, std::basic_ofstream<char, std::char_traits<char> >*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Spectrum const*, int, ActivePeptideQueue const*, std::vector<pb::Protein const*, std::allocator<pb::Protein const*> > const&, bool, bool, boost::mutex*) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6916F7: TideSearchApplication::search(void*) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0xD8BD76: thread_proxy (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x5823737: mythread_wrapper (hg_intercepts.c:398)
==29556==    by 0x58763F8: start_thread (in /usr/lib64/libpthread-2.32.so)
==29556==    by 0x5D274C2: clone (in /usr/lib64/libc-2.32.so)
==29556== 
==29556== This conflicts with a previous write of size 8 by thread #5
==29556== Locks held: none
==29556==    at 0x6A4B59: myrandom() (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6A4C87: myrandom_limit(int) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6DB56C: SpSpectrum::ExtractPeaks(int) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6DBBD9: SpSpectrum::PreprocessSpectrum(Spectrum const&, int) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6E42ED: SpScorer::SpScorer(Spectrum const&, int, double) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6871E3: TideMatchSet::report(std::basic_ofstream<char, std::char_traits<char> >*, std::basic_ofstream<char, std::char_traits<char> >*, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Spectrum const*, int, ActivePeptideQueue const*, std::vector<pb::Protein const*, std::allocator<pb::Protein const*> > const&, bool, bool, boost::mutex*) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0x6916F7: TideSearchApplication::search(void*) (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==    by 0xD8BD76: thread_proxy (in /home/cegrant/Projects/crux-toolkit/release/src/crux)
==29556==  Address 0x4efd600 is 2496 bytes inside data symbol "_ZZ11get_mt19937vE8mt19937_"
==29556== 
==29556== ----------------------------------------------------------------

**Comment by CharlesEGrant** [comment]
I wonder if our PRNG is not thread safe?

**Comment by kfattila** [comment]
Thanks!

**Comment by kfattila** [comment]
I have removed the sp-score scoring from tide-search with the tide-lite PR.
