### ISSUE TITLE
Representing terminal amino acid modifications

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#639]
In the current Tide output format, terminal PTMs cannot be distinguished from side chain PTMs.  I think we should represent them using a hyphen, so a modification of XXX on the first amino acid of PEPTIDEK would be `[XXX]-PEPTIDEK` and the same modification on the last amino acid would be `PEPTIDEK-[XXX]`. This will allow the terminal amino acids to have both a sidechain and terminal modification.  So if the sidechain mod is YYY, then you'd get `[XXX]-P[YYY]EPTIDEK` or `PEPTIDEK[YYY]-[XXX]`.

**Comment by kfattila** [comment]
When you use TMT-6plex labeling on n terminal and lysine you would get peptides like 'PEPTIDEK[229.16]-[229.16]'. Is this Ok?

**Comment by wsnoble** [comment]
I pinged Jimmy about this, and here is his answer:

"Easy answer for this one with regards to TMT.  TMT mods are peptide n-term and lysines.  So [229]-PEPTIDEK[229].  

The less clear answer is how should one treat your example case of a modification on the c-terminus and lysine residue?  Comet code considers residue modifications and terminal modifications as separate entities.  So it is possible in Comet to analyze a peptide that results in n[229]P[32]EPTIDEK (for a mythical modification on the first proline) or PETIDEK[229]c[229] for a 229 mod on both lysine and c-term.

Even if it's not chemically possible to have a real modification on a terminal residue plus a real modification on the corresponding n- or c-terminus, I can see use cases where one might want to allow both to occur on a peptide for a search.  I guess for most flexibility, have another user parameter that controls whether or not to allow term mod + adjacent residue mod.  This must be a very minor issue because I don't recall anyone even mentioning Comet's handling of terminal mods when the adjacent residue is also modified."

I don't think we should bother with that extra parameter and instead just follow Comet's lead by allowing both terminal and side-chain modifications on the same amino acid.

**Comment by kfattila** [comment]
Thanks!

**Comment by kfattila** [comment]
@wsnoble, shall I do this? Did we agree on this? It will require to change the tide-index google protocol buffer format.

**Comment by wsnoble** [comment]
Yes, please do.

**Comment by kfattila** [comment]
This has been fixed with the tide-lite PR.
