### ISSUE TITLE
Update file formats html 

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#641]
The Tab-delimited file format file seems to be outdated. 
I think, the column names of diameter should be added. 
I alos think that the `res-ev p-score` is also incorrect. Shouldn't it be `res-ev score`?

**Comment by wsnoble** [comment]
The final output format for diameter is just the same as percolator.  But there is an intermediate search file with these columns:

```
file
scan
charge
spectrum precursor m/z
spectrum neutral mass
peptide mass
delta_cn
delta_lcn
xcorr score
tailor score
xcorr rank
precursor intensity logrank M0
precursor intensity logrank M1
precursor intensity logrank M2
rt-diff
dynamic fragment p-value
static fragment p-value
precursor coelution
fragment coelution
precursor fragment coelution
ensemble score
distinct matches/spectrum
sequence
modifications
cleavage type
protein id
flanking aa
target/decoy
```

We need to update the file-formats.html file to mention both of these file types and include the relevant columns.

**Comment by bmx8177** [comment]
Atilla is correct. Looks like we accidentally wrote 'res-ev p-value' twice. 
![image](https://user-images.githubusercontent.com/22140743/226430284-3d394c7e-d8ff-4156-94a9-a4b00e1b452b.png)
