### ISSUE TITLE
Unexpected change in XCorr score after summing spectrum peak intensities for peaks in the same bin. 

### ISSUE THREAD

**Issue by temana-short** [crux-toolkit/crux-toolkit#642]
### Summary
When two different peaks are in the same bin, I've been told that tide-search treats them as one peak, but with the intensities summed. As part of my analysis, I have to pre-process the spectra, including summing peaks when they're in the same bin. 

However, I've found that tide-search computes different XCorr scores when I sum the peaks vs. when I don't, likely relating to the background subtraction component of the XCorr score calculation. I'm not sure if this is a bug, or if tide-search doesn't actually treat peaks in the same bin as one summed peak.

### Experiment setup

Use tide-search to search the two below spectra against a peptide database with only one peptide: AA, which has a theoretical y1+ ion peak at 90.05 m/z.

My Crux version is: 4.1-f575777-2023-01-13

tide-search non-default parameters:
- mz-bin-width = 1
- precursor-window-type = mass
- precursor-window = 100
- min-peaks = 1

### Experiment 1
experiment_1.mgf:
MASS=Monoisotopic
BEGIN IONS
PEPMASS=80.0
CHARGE=2+
SCANS=1
90.0 10000
90.3 20000
END IONS

BEGIN IONS
PEPMASS=80.0
CHARGE=2+
SCANS=2
90.0 30000
END IONS

Because the peaks at mzs 90.0 and 90.3 are in the same bin (with mz-bin-width = 1 and default mz-bin-offset = 0.4), I expect that summing the peak intensities should not impact the XCorr score when matched against the peptide AA. And as expected, the two spectra PSMs have the same XCorr score (0.2470). 

### Experiment 2
experiment_2.mgf:
MASS=Monoisotopic
BEGIN IONS
PEPMASS=80.0
CHARGE=2+
SCANS=1
90.0 10000
90.3 20000
95.0 100000
END IONS

BEGIN IONS
PEPMASS=80.0
CHARGE=2+
SCANS=2
90.0 30000
95.0 100000
END IONS

When both spectra have an added peak at 95.0 m/z (which is not a theoretical peak of the peptide AA), I still don't expect summing the peak intensities (of peaks in the same bin) to impact the XCorr score. However, the spectra have different XCorr scores:
- SCANS=1: 0.10579509
- SCANS=2: 0.13062080

Any help would be appreciated,
Temana

**Comment by kfattila** [comment]
Hi Temana,

When two peaks in an experimental spectrum fall in the same bin then Tide-search takes the maximum of the intensities of the peaks and not the sum of the intensities. This is true for the standard XCorr scoring and for the refactored score scoring used in exact p-value calculation. I am not sure what is the behavior in the case of res-ev scoring. 

Why do you think Tide was supposed to sum up the peaks in the same bin?

Attila

**Comment by kfattila** [comment]
In your first experiment, You have only one peak and XCorr scales the peaks between 0 and 50.0. Thus, it does not matter what is the intensity of your single peak, it will be always scaled to 50.0. This is the reason you obtain the scame XCorr score in your experiment 1.

**Comment by wsnoble** [comment]
Indeed, the binning is described on p. 3872 of the [Tide paper](https://pubs.acs.org/doi/full/10.1021/pr101196n): "Next, each observed spectrum is preprocessed as follows. A set of bins, each of width 1.0005079 Da/charge, is laid over the full range of the m/z values reported in the input file for the spectrum. Each input MS/MS peak is bucketed into the nearest bin, which
retains only the highest intensity peak that fell into that bin."

**Comment by temana-short** [comment]
Thanks kfattila and wsnoble, the fact that the maximum intensity is taken makes a lot of sense. I'm not sure where my assumption that the peaks are summed came from now that I reflect, but regardless this fix will help a lot. Also, the experiment results make complete sense now. Thanks!
