### ISSUE TITLE
Unify sorting

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#646]
I followed up on Attila's comment that the randomness in tide-search is in the Sp calculation.  This is true: there is a quicksort implementation there that relies on a function called myrandom_limit().  I also noticed that this code is repeated: the same quick_sort code is in crux-utils.cpp and in crux_sp_spectrum.h, where it is called "QuickSort".  Perversely, there is also a function called "quicksort" in crux-utils.cpp that looks like this:

void quicksort(FLOAT_T a[], int array_size) {
  quick_sort(a, 0, array_size - 1);
}

I propose that we revamp the sorting.  First, get rid of the repeated code ("quick_sort" and "QuickSort") and get rid of the silly "quicksort."  Then consider replacing quick_sort with a library call.  For the latter, we should expect to see some changes in the results, so we will want to do some timing tests and performance tests.

**Comment by codeworse** [comment]
Is there a reason to keep quick_sort algorithm? It could be replaced with std::sort which is [introsort](https://en.wikipedia.org/wiki/Introsort) inside and also has $O(n \log n)$ complexity

**Comment by wsnoble** [comment]
I believe that when Benjamin Diament did this, it was in the context of optimizing Tide, and he found that his implementation outperformed the library sort.  But that optimization is not really relevant anymore.
