### ISSUE TITLE
Tide-search unexpected behaviour when assigning fragment masses to bins for XCorr score calculation.

### ISSUE THREAD

**Issue by temana-short** [crux-toolkit/crux-toolkit#647]
Crux-version: 4.1-f575777-2023-01-13

For a specific peptide (SCNPGDLHECVGYFIGCHGPFDKCLANK, with static +57.0215 modifications on C, and precursor charge 3+), I've calculated that theoretical fragment y5-NH3+ should have a peak at 588.2810 Th (also somewhat validated in an experiment described in the 4th paragraph below), with the closest other fragment peak at 587.2970 Th. 

When I create a peptide database with only that one peptide, and search against one spectrum with just one peak at 588.2967 Th, with --mz-bin-width 0.014125703 (estimated by param-medic on a larger set of spectra), with --use-flanking-peaks false, the formula provided for bin assignment in answer 5 of the crux FAQ page would suggest that the relevant theoretical fragment peak (588.2810 Th) and only observed peak (588.2967 Th) aren't in the same bin, and hence the XCorr score should be less than or equal to zero.

However, I've found that the XCorr score is positive (0.04966666), which suggests that the observed peak (588.2967 Th) is in the same bin as one of the peptide's theoretical fragment peaks. This was unexpected.

To validate that 588.2810 is indeed a theoretical fragment peak of the peptide, I searched five spectra, each with only one peak at m/zs 588.2808, 588.2809, 588.2810, 588.2811, 588.2812 respectively, against the peptide database including only that peptide, with --mz-bin-width 0.0001. Only the spectrum with just one peak at 588.2810 had a positive XCorr score (0.05), whereas the four other spectra had negative XCorr scores (-0.00033). This seems to validate that 588.2810 is a theoretical peak of the peptide (SCNPGDLHECVGYFIGCHGPFDKCLANK).

Any help would be appreciated,
Temana

**Comment by wsnoble** [comment]
Hi Temana,

Are you using the default bin offset of 0.4?

You can use the commands [print-processed-spectra](http://crux.ms/commands/print-processed-spectra.html) and [predict-peptide-ions](http://crux.ms/commands/predict-peptide-ions.html) to print out what Tide is doing to each peptide and spectrum. Maybe this can help with the debugging?


For examples, predict-peptide-ion lists the ions and doesn't report the masses you are looking for:

```
% crux predict-peptide-ions SCNPGDLHECVGYFIGCHGPFDKCLANK 3
INFO: Beginning predict-peptide-ions.
# PEPTIDE: SCNPGDLHECVGYFIGCHGPFDKCLANK
# AVERAGE: 3025.439209 MONO:3023.318604
# CHARGE: 3
# MAX-ION-CHARGE: peptide
# NH3 modification: 0
# H2O modification: 0
# ISOTOPE modification: 0
# FLANK modification: 0
m/z	mass	charge	ion-series	peptide-bond-index	nh3	h2o	isotope	flank
88.04	88.04	1	b	1	0	0	0	0
44.52	89.05	2	b	1	0	0	0	0
147.11	147.11	1	y	1	0	0	0	0
74.06	148.12	2	y	1	0	0	0	0
191.05	191.05	1	b	2	0	0	0	0
96.03	192.06	2	b	2	0	0	0	0
261.16	261.16	1	y	2	0	0	0	0
131.08	262.16	2	y	2	0	0	0	0
305.09	305.09	1	b	3	0	0	0	0
153.05	306.10	2	b	3	0	0	0	0
332.19	332.19	1	y	3	0	0	0	0
166.60	333.20	2	y	3	0	0	0	0
402.14	402.14	1	b	4	0	0	0	0
201.58	403.15	2	b	4	0	0	0	0
445.28	445.28	1	y	4	0	0	0	0
223.14	446.29	2	y	4	0	0	0	0
459.17	459.17	1	b	5	0	0	0	0
230.09	460.17	2	b	5	0	0	0	0
548.29	548.29	1	y	5	0	0	0	0
274.65	549.29	2	y	5	0	0	0	0
574.19	574.19	1	b	6	0	0	0	0
287.60	575.20	2	b	6	0	0	0	0
676.38	676.38	1	y	6	0	0	0	0
338.69	677.39	2	y	6	0	0	0	0
687.28	687.28	1	b	7	0	0	0	0
344.14	688.28	2	b	7	0	0	0	0
791.41	791.41	1	y	7	0	0	0	0
396.21	792.42	2	y	7	0	0	0	0
824.34	824.34	1	b	8	0	0	0	0
412.67	825.34	2	b	8	0	0	0	0
938.48	938.48	1	y	8	0	0	0	0
469.74	939.48	2	y	8	0	0	0	0
953.38	953.38	1	b	9	0	0	0	0
477.19	954.39	2	b	9	0	0	0	0
1035.53	1035.53	1	y	9	0	0	0	0
518.27	1036.54	2	y	9	0	0	0	0
1056.39	1056.39	1	b	10	0	0	0	0
528.70	1057.40	2	b	10	0	0	0	0
1092.55	1092.55	1	y	10	0	0	0	0
546.78	1093.56	2	y	10	0	0	0	0
1155.46	1155.46	1	b	11	0	0	0	0
578.23	1156.46	2	b	11	0	0	0	0
1229.61	1229.61	1	y	11	0	0	0	0
615.31	1230.62	2	y	11	0	0	0	0
1212.48	1212.48	1	b	12	0	0	0	0
606.74	1213.49	2	b	12	0	0	0	0
1332.62	1332.62	1	y	12	0	0	0	0
666.81	1333.63	2	y	12	0	0	0	0
1375.54	1375.54	1	b	13	0	0	0	0
688.27	1376.55	2	b	13	0	0	0	0
1389.64	1389.64	1	y	13	0	0	0	0
695.32	1390.65	2	y	13	0	0	0	0
1522.61	1522.61	1	b	14	0	0	0	0
761.81	1523.62	2	b	14	0	0	0	0
1502.72	1502.72	1	y	14	0	0	0	0
751.87	1503.73	2	y	14	0	0	0	0
1635.69	1635.69	1	b	15	0	0	0	0
818.35	1636.70	2	b	15	0	0	0	0
1649.79	1649.79	1	y	15	0	0	0	0
825.40	1650.80	2	y	15	0	0	0	0
1692.71	1692.71	1	b	16	0	0	0	0
846.86	1693.72	2	b	16	0	0	0	0
1812.86	1812.86	1	y	16	0	0	0	0
906.93	1813.86	2	y	16	0	0	0	0
1795.72	1795.72	1	b	17	0	0	0	0
898.37	1796.73	2	b	17	0	0	0	0
1869.88	1869.88	1	y	17	0	0	0	0
935.44	1870.89	2	y	17	0	0	0	0
1932.78	1932.78	1	b	18	0	0	0	0
966.90	1933.79	2	b	18	0	0	0	0
1968.95	1968.95	1	y	18	0	0	0	0
984.98	1969.95	2	y	18	0	0	0	0
1989.80	1989.80	1	b	19	0	0	0	0
995.41	1990.81	2	b	19	0	0	0	0
2071.96	2071.96	1	y	19	0	0	0	0
1036.48	2072.96	2	y	19	0	0	0	0
2086.86	2086.86	1	b	20	0	0	0	0
1043.93	2087.87	2	b	20	0	0	0	0
2201.00	2201.00	1	y	20	0	0	0	0
1101.00	2202.01	2	y	20	0	0	0	0
2233.93	2233.93	1	b	21	0	0	0	0
1117.47	2234.93	2	b	21	0	0	0	0
2338.06	2338.06	1	y	21	0	0	0	0
1169.53	2339.06	2	y	21	0	0	0	0
2348.95	2348.95	1	b	22	0	0	0	0
1174.98	2349.96	2	b	22	0	0	0	0
2451.14	2451.14	1	y	22	0	0	0	0
1226.07	2452.15	2	y	22	0	0	0	0
2477.05	2477.05	1	b	23	0	0	0	0
1239.03	2478.06	2	b	23	0	0	0	0
2566.17	2566.17	1	y	23	0	0	0	0
1283.59	2567.18	2	y	23	0	0	0	0
2580.06	2580.06	1	b	24	0	0	0	0
1290.53	2581.06	2	b	24	0	0	0	0
2623.19	2623.19	1	y	24	0	0	0	0
1312.10	2624.20	2	y	24	0	0	0	0
2693.14	2693.14	1	b	25	0	0	0	0
1347.07	2694.15	2	b	25	0	0	0	0
2720.24	2720.24	1	y	25	0	0	0	0
1360.62	2721.25	2	y	25	0	0	0	0
2764.18	2764.18	1	b	26	0	0	0	0
1382.59	2765.19	2	b	26	0	0	0	0
2834.29	2834.29	1	y	26	0	0	0	0
1417.65	2835.29	2	y	26	0	0	0	0
2878.22	2878.22	1	b	27	0	0	0	0
1439.61	2879.23	2	b	27	0	0	0	0
2937.29	2937.29	1	y	27	0	0	0	0
1469.15	2938.30	2	y	27	0	0	0	0
INFO: Elapsed time: 0.0909 s
INFO: Finished crux predict-peptide-ions.
INFO: Return Code:0
```

**Comment by temana-short** [comment]
Hi wsnoble,

I haven't tried the print-processed-spectra command, so I'll try that this morning.

For the predict-peptide-ions command, I used options --nh3 1 --h2o 1 since XCorr score considers NH3 and H2O loss on b- and y- ions. When I run that, I get the following row:

`531.26  531.26  1       y       5       1       0       0       0`

Accounting for the default fixed carbamidomethyl modification (+57.02) gives the 588.28 peak that I'm considering.

Thanks,
Temana

**Comment by temana-short** [comment]
Adding that I do use the default 0.4 offset.

I've played around with the print-processed-spectra command, and have confirmed that peaks 588.2810 Th and 588.2967 Th are in different bins with --mz-bin-width 0.014125703, agreeing with my calculations, and makes sense because the two peaks are further apart than the bin width.

Unless I've misunderstood something, it seems that the problem arises because either
(a) There isn't a theoretical peak at 588.2810 Th (which disagrees with the experiment in my 4th paragraph in original post)
(b) The formula for assigning theoretical peak values to bins is slightly different to the formula of assigning observed peak values to bins.

Adding to (b), the description of how bins are assigned in the tide-search parameter documentation for --mz-bin-offset is different to the formula mentioned in --mz-bin-width (see below). For example, consider two peaks at 0.401 Th and 0.409 Th, with 0.01 bin-width and 0.4 offset. The mz-bin-offset description seems to imply that the left edge of the first bin should be 0.4, which means that the right edge of the first bin is 0.41, hence the two peaks should be in the same bin. The mz-bin-width formula however implies that 0.401 is in bin 40, but 0.409 is in bin 41. The problem could be explained if both bin assigning methods are used at some point. My supervisor Uri suggested that a difference in rounding vs. floor could also explain the problem.

`--mz-bin-offset <float> – In the discretization of the m/z axes of the observed and theoretical spectra, this parameter specifies the location of the left edge of the first bin, relative to mass = 0 (i.e., mz-bin-offset = 0.xx means the left edge of the first bin will be located at +0.xx Da). Default = 0.4.`

`--mz-bin-width <float> – Before calculation of the XCorr score, the m/z axes of the observed and theoretical spectra are discretized. This parameter specifies the size of each bin. The exact formula for computing the discretized m/z value is floor((x/mz-bin-width) + 1.0 - mz-bin-offset), where x is the observed m/z value. For low resolution ion trap ms/ms data 1.0005079 and for high resolution ms/ms 0.02 is recommended. Default = 0.02.`

Any help would be appreciated, 
Temana

**Comment by kfattila** [comment]
Hi, Tide, first, calculates the bins of the fragment ions and the loss and the subtracts the bins. I think this discretization introduces a rounding error. This is particularly an issue for very small bin sizes.

**Comment by wsnoble** [comment]
Hmm, that's unfortunate. Maybe this explains some of the discrepancy between Tide and Comet. Do you have a sense for whether fixing this would be non-trivial?

**Comment by temana-short** [comment]
Hi kfattila,

Just hoping to confirm that my understanding of the subtraction you described is correct via an example: 

Given that:
- mz-bin-width is 0.014125703
- the y5+ fragment has mz (and mass) 605.3076, and hence is allocated to bin 42852
- the ammonia loss mass is 17.02656, and is hence allocated to bin 1205

Then the resulting bin of the y5+ fragment with ammonia loss is 42852 - 1205 = 41647.

If this is right, then I can account for and get around this in the analysis I'm currently doing.

Thanks,
Temana

**Comment by kfattila** [comment]
Hi Bill, 

It would be easy to fix this. The neutral losses could be handled before discretization before the 10-fold-region normalization. But I am afraid it would change the maximum intensity in a region, and the normalization would result in a quite different result. Maybe, could you ask Jimmy how Comet handles neutral losses (before or after the 10-fold-region normalization)?

**Comment by jke000** [comment]
In Comet, the neutral loss peaks processing is applied after the 10-window normalization and is done by subtracting "bins" so neutral loss peaks could/would end up in the wrong mass bin due to rounding especially for small mass bins.  Implementing it this way was a tradeoff I made years ago (the possibility of neutral loss bins being off vs. optimization).

**Comment by temana-short** [comment]
After accounting for the subtraction in bin allocation, I still run into unexpected behaviour (although less often). 

When searching a spectrum with only one observed peak at 595.26276 Th against the peptide VSSFSSLR, the XCorr score is 0.25 (mz-bin-width = 0.014125703, mz-bin-offset = 0.4, precursor charge = 2). Using `predict-peptide-ions`, the only close theoretical fragment peak comes from the b6+ ion, which reports 595.27 Th, and my calculation of that is 595.27222 Th to 5 decimal places. Using `print-processed-spectra` on the spectrum with only one peak at 595.26276 places it in bin 42140, while using it on a spectrum with only one peak at 595.27 places it in bin 42141. This is unexpected because the peaks being in different bins means that the XCorr score should be less than or equal to zero (and the subtraction problem mentioned above shouldn't matter in this case because the b6+ doesn't have water- or ammonia-loss).

Any help would be appreciated,
Temana

**Comment by kfattila** [comment]
The experimental peak 595.26278 from the spectrum reaches the spectrum preprocessing function of Tide-search as 595.262800 and this experimental peak falls in the 42141th bin. Maybe the protewizard or the spectrum parser does some rounding.

**Comment by temana-short** [comment]
Hi kfattila,

Thanks for your insights, I've accounted for rounding all observed peaks to 4 d.p., and this has further reduced the number of spectra that my analysis finds to behave unexpectedly (but not to zero). Just wondering how you identified that the peak reaches the preprocessing function of tide-search as 595.262800, and if you have any other tide-specific debugging tips, so that I can continue identifying and accounting for unexpected behaviours (and only ask here if I reach a dead end)?

Thanks,
Temana

**Comment by temana-short** [comment]
Hi kfattila,

I do know how to use printf functions in c++, but do not know how to compile crux. Any help would be appreciated. (Sorry for the delayed reply, have been overseas on break).

Thanks,
Temana

**Comment by wsnoble** [comment]
Detailed instructions are here:

http://crux.ms/tutorials/install.html

Can you try it and let us know if you run into difficulties?

**Comment by temana-short** [comment]
Hi wsnoble and kfattila,

I've followed the detailed instructions and can successfully compile and run crux with my own printf debug lines. As I'm still looking for PSMs that behave unexpectedly, I've added printf lines to `crux-4.1.Source/src/app/tide/spectrum_preprocess2.cc` to confirm assigned bins on preprocessed observed spectra. 

However, I'm struggling to find, for tide-search, where theoretical fragmentation spectra are calculated, and where XCorr  scores are calculated. Any help would be appreciated on understanding any of the following:

- Section of code that calculates peptide fragmentation spectra (mz)
- Section of code that assigns mzs to bins for peptide fragmentation spectra
- Section of code that calculates XCorr scores
- Variables that store peptide fragmentation spectra (mz and/or allocated bins)

Thanks,
Temana

**Comment by kfattila** [comment]
Hi Temana,

Congratulations on your successful build. Here are the code lines you are looking for:
1. The theoretical fragmentation ions are calculated in ./src/app/tide/peptide.cc in `AddIons(...)` function around line 76.
2. The theoretical fragmentation bins are calculated in ./src/app/tide/theoretical_peak_set.h' in functions AddYIon and AddBIon. The actual calculation is done by the `MassConstants::mass2bin(mass + MassConstants::Y + MASS_PROTON, charge);`
3. The XCorr scores are calculated in `void TideSearchApplication::collectScoresCompiled(` at line 1343. There are nested for loops. The outer one loops over the peptides, the inner one loops over the peaks.
4. Each peptide object has two member variables `peak_0' for storing single charge theoretical fragmentation bins, and `peak_1` for storing double charge theoretical fragmentation bins. 


Feel free to poke me if you need any further assistance or help. I'd be happy to provide you more info.
Attila

**Comment by temana-short** [comment]
Hi kfattila, 

I've been using the crux build from source to successfully fix some problems related to my own code (e.g. slightly off amino acid masses). However, I have encountered a problem that I can't work out:

In summary, a peak with m/z 545.3284 seems to enter tide preprocessing as 545.3285, perhaps due to protewizard, or the spectrum parser, or some rounding standard that I'm not aware of? I'm hoping to know if there's a known reason that this occurs so that I can account for it.

I added a line to the source code `crux-4.1.Source/src/app/tide/spectrum_preprocess2.cc` after line 115: `printf("peak_location: %f\n", peak_location);`, which to my knowledge prints the peak location (in m/z) at the beginning of preprocessing. When then running tide-search on the below spectrum with only one peak, the line of code I added gives `peak_location: 545.328500`. 

```
MASS=Monoisotopic
BEGIN IONS
PEPMASS=468.75503
CHARGE=2+
SCANS=11349
545.3284 273617.0
END IONS
```

Any help would be appreciated,
Temana

**Comment by kfattila** [comment]
Hi!

That's nice! I have no idea why this happens. Maybe, could you put your data into another format? Maybe you could convert the data into .ms2 or mzML format with msconvert, and see what happens. Different code parses different format.

**Comment by wsnoble** [comment]
You could also try the other parser with `--spectrum-parser mstoolkit`.

**Comment by temana-short** [comment]
All 4 combinations of using either parser (`--spectrum-parser ...`) and inputting .mgf or .ms2 result in the 545.3284 peak appearing as 545.3285 in `spectrum_preprocess2.cc`. 

Interestingly using `crux get-ms2-spectrum ...`, with either parser, results in the peak appearing correctly at 545.3284, which makes me think that perhaps the conversion occurs somewhere after proteowizard/mstoolkit parsing, but before `spectrum_preprocess2.cc`. 

Any help would be appreciated on describing what code occurs before `spectrum_preprocess2.cc`, e.g. where `spectrum.M_Z(i)` is set.

Thanks,
Temana

**Comment by kfattila** [comment]
Unfortunately, I cannot help you with this. However, I have a task which involves checking this part of the code in the near future. but I don't know when. So, there is a chance I will be able to help you later.

**Comment by temana-short** [comment]
Hi kfattila, that's fair. Thanks for all the help so far.

**Comment by kfattila** [comment]
I think I got this. Some information is lost when the real valued mz peak locations are converted to integers for the spectrumrecords file format. The parameter which controls the digits of precision is specified in `src/io/spectrumRecordWriter.cpp` at line 182: ```  const int kMaxPrecision = 10000; // store at most 4 digits of precision``` 

@temana-short, could you please change this line to 100,000 or 1,000,000 just to see if this solves the problem?
@wsnoble What should be do if increasing the maxprecision solves the problem? Shall we increase it? I do not think this discretization creates lots of problems in practice.

**Comment by wsnoble** [comment]
It seems unlikely that useful information is lost when this precision filter is applied.

**Comment by temana-short** [comment]
Hi kfattila,

I've done a couple tests with the `kMaxPrecision` variable (in line 170 of `src/io/SpectrumRecordWriter.cpp` for me), and found that it did have an impact, but didn't fully fix the problem.

Recall that the spectrum being used is

```
MASS=Monoisotopic
BEGIN IONS
PEPMASS=468.75503
CHARGE=2+
SCANS=11349
545.3284 273617.0
END IONS
```

I tried `kMaxPrecision` as 1000, 10000 (as it was originally), 100000, 1000000, 1000000000, and printf'd the `peak_location` variable right after it is defined in line 115 of `src/app/tide/spectrum_preprocess2.cc`, the results of that printf are below:

- 1000: 545.328000
- 10000: 545.328500
- 100000: 545.328440
- 1000000: 545.328440
- 1000000000: 545.328440

The strange thing is that increasing `kMaxPrecision` does seem to change the precision of the peak position, but only until 545.328440, even though the peak is positioned at 545.3284.

Any help would be appreciated,
Temana
