### ISSUE TITLE
Make tide-search report 1) the number of matching fragment ions, 2) the total theoretical fragment Ions and 3) their ratio

### ISSUE THREAD

**Issue by kfattila** [crux-toolkit/crux-toolkit#648]
Make tide-search report 1) the number of matching fragment ions, 2) the total theoretical fragment Ions and 3) their ratio.

**Comment by kfattila** [comment]
@wsnoble, are these good for the column names:
`b/y ions matched`
`b/y ions total`
`b/y ions fraction`

**Comment by thabangh** [comment]
Are the first two integers and the third a ratio of the two?

**Comment by kfattila** [comment]
Yes.

**Comment by wsnoble** [comment]
Then yes, I think those are reasonable names.

**Comment by kfattila** [comment]
Fixed with PR #650
