### ISSUE TITLE
Repeated target-decoy pairs in peptide list

### ISSUE THREAD

**Issue by freejstone** [crux-toolkit/crux-toolkit#649]
Hi crux team,

Now that I am on a new project I have decided to use the latest release of Crux. I have noticed that the peptide list produced by tide-index creates duplicate rows. See the following log file, fasta file, mgf and copy-paste of the duplicate rows. Attila, if you end up picking this up I can share with you on Slack the actual peptide list if you like (they are too big to share here). I used a fixed seed so it should be reproducable.

K[304.2022]PGVPAEPPALPPASQR	K[304.2022]EALPSPPQVAPPGAPR	2015.1438	gi|471368921|ref|XP_004374983.1|(518)
K[304.2022]PGVPAEPPALPPASQR	K[304.2022]EALPSPPQVAPPGAPR	2015.1438	gi|471368921|ref|XP_004374983.1|(518)

[tide-index.log.txt](https://github.com/crux-toolkit/crux-toolkit/files/11185078/tide-index.log.txt)
[Mudpit_LC-iTRAQ1.RAW (F004785).mzid_Mudpit_LC-iTRAQ1.RAW_(F004785).MGF.txt](https://github.com/crux-toolkit/crux-toolkit/files/11185083/Mudpit_LC-iTRAQ1.RAW.F004785.mzid_Mudpit_LC-iTRAQ1.RAW_.F004785.MGF.txt)
[Manatee_20131715.fasta.txt](https://github.com/crux-toolkit/crux-toolkit/files/11185082/Manatee_20131715.fasta.txt)

**Comment by kfattila** [comment]
Hi Jack,

It is not really a duplicated row. The problem is that param-medic reports duplicated modifications.  Once, the lysine is modified, in the other peptide, the n-terminal is modified. 

I do not know how to fix this. 

A

**Comment by freejstone** [comment]
Oh I see! Yes right that makes sense. Cheers, Jack
