### ISSUE TITLE
tide-search Sp score completely zero

### ISSUE THREAD

**Issue by temana-short** [crux-toolkit/crux-toolkit#653]
Hi,

I've run tide-search with `--compute-sp T`, but the `sp score` columns of tide-search.target.txt and tide-search.decoy.txt are completely zero (no PSM has a non-zero sp score). I'm wondering if this is expected or known behaviour?

For more details, I use Crux version: 4.1-f575777-2023-01-13, and ran the following prompt:

`/Users/temanashort/Desktop/honours_research/crux-4.1.Darwin.x86_64/bin/crux tide-search --overwrite T --output-dir /Users/temanashort/Desktop/honours_research/crux_output/shuffled_spectra_percolator/sp_not_computing --min-peaks 20 --num-threads 0 --top-match 1 --use-tailor-calibration T --mass-precision 8 --mz-bin-width 0.014125703 --compute-sp T --pin-output T /Users/temanashort/Desktop/honours_research/data/PXD008996/A431_01uM_DON_3_2.mgf /Users/temanashort/Desktop/honours_research/resolved_crux_output/testing_indices/PXD008996/seed_1000`

Additionally, the related `b/y ions matched` columns are also completely zero, and the program took much longer to run with `--compute-sp T` (300 seconds vs. 10 seconds) even though the added columns are all zero.

Any help would be appreciated,
Temana

**Comment by kfattila** [comment]
Can you please send me the log and the output files? Thanks

**Comment by temana-short** [comment]
Hi kfattila,

Here is a link to the output files: 
https://unisyd-my.sharepoint.com/:f:/g/personal/temana_short_sydney_edu_au/EtCkrC2g30tAm8deInKP-LgBbfATFOBz4H29ZbZaRo2stA?e=wZdCx6 
password: sp_score

I thought that some of the options (e.g. --mz-bin-width 0.014125703) might've been causing problems, so I re-ran tide-search with fewer options (only --overwrite T, --compute-sp T, and --output-dir ...), but have the same problem.

Thanks for looking at this,
Temana

**Comment by kfattila** [comment]
Thanks for the data. I got them. Could you please update your crux to the latest version from the github. I have checked the sp-scores recently, 1-2 months ago, and it worked fine for me. Let me know if the lates version also produces purely 0 sp-scores.
Thanks.

**Comment by temana-short** [comment]
Hi kfattila,

Just downloaded and ran the most recent build of Crux (4.1-b74024b-2023-05-11), still got all zeros for the Sp score. 

I thought it might've been the dataset, so I tried the tutorial spectra and .fasta file (https://crux.ms/tutorials/gettingstarted.html), but even then got all zeros for the Sp score:

`crux-4.1.Darwin-2.x86_64/bin/crux tide-index crux_output/sp_score/test3/small-yeast.fasta crux_output/sp_score/test3/yeast-index` then `crux-4.1.Darwin-2.x86_64/bin/crux tide-search --compute-sp T --top-match 1 --output-dir crux_output/sp_score/test3 --overwrite T crux_output/sp_score/test3/demo.ms2 crux_output/sp_score/test3/yeast-index` (I can send log and output files if you'd like).

At this point, I'm not sure what else could be different (maybe Macbook Air, M2 chip, MacOS Monterey 12.5.1)

Thanks for looking at this,
Temana

**Comment by kfattila** [comment]
The XCorr is calulated in Tide-search based on the Comet/Sequest scoring. The SP-score and the number of the b/y ion matches are calualted with a totally different code with using different preprocessing peptide fragmentation, etc. The number of matching peaks in XCorr and in SP are different but correlated.

**Comment by temana-short** [comment]
Hi kfattila,

It makes sense that the different code results in different results. I'm still surprised because I can validate that thousands of spectra I searched had 10+ unique b/y ion matches using the XCorr scoring method, but the Sp scoring code somehow reports zero b/y ion matches, with the same mz-bin-width. Although I guess there's not much else we can do here, so I'm happy with the Github issue being closed.

Thanks for the help,
Temana

**Comment by kfattila** [comment]
Hi Temana,

We have reorganized the code of the whole tide-search program. Now, tide-search reports the total number of b-y ions, and the matching by ions, and their fractions, etc. This is calculated with using the theoretical peaks used for XCorr. So, this should be consistent. I am sorry for that it took so long. I also ask you to update your crux. Now, Tide-search got much faster when you run it with multiple spectrum files. I'd appreciate if you share with us any issues you encounter.
