### ISSUE TITLE
Question about Percolator columns

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#656]
I was looking through io/MatchColumns and saw these columns in the image. These columns currently do not match the Percolator output columns. Are these old, currently unused column headers?
![image](https://github.com/crux-toolkit/crux-toolkit/assets/22140743/2a05c02d-4b5e-4b95-b767-30aaa1778ff0)

**Comment by wsnoble** [comment]
Percolator now handles all of its own outputs.  Those columns are irrelevant and could be removed.
