### ISSUE TITLE
Percolator command documentation

### ISSUE THREAD

**Issue by bmx8177** [crux-toolkit/crux-toolkit#657]
The Percolator documentation at http://crux.ms/commands/percolator.html indicates that pepxml can still be written as an output. However, this argument is not found in PercolatorApplication::getOptions. To my understanding is if the argument is not in PercolatorApplication::getOptions then it should be on the website. Not sure what is going on. I poked around and failed to figure it out.

**Comment by wsnoble** [comment]
Closed in favor 584.
