### ISSUE TITLE
inflated PSMs in percolator pipeline (compared to TPP)

### ISSUE THREAD

**Issue by emmats** [crux-toolkit/crux-toolkit#668]
I did a Comet search of a metaproteomics experiment and used that pep.xml in parallel downstream analyses with 1) TPP (peptide and proteinprophet) and 2) percolator. For both I did a FDR/q-value cut-off of 0.01. For the TPP pipeline I "found" 34341 peptides, 7969 proteins, with a total of 42204 PSMs. For the percolator pipeline, I found 33468 peptides, 10743 proteins, and >155 million PSMs (distinct spectrum matches). I'm trying to understand why my PSMs from percolator are so inflated compared to TPP. 
Here is the Comet pep.xml file: https://drive.google.com/file/d/1wYXsu9a-AtE5JVhcn1lebJF2f57lM8oi/view?usp=sharing

My percolator command (crux 4.1) looked like this: crux percolator ../raw/bak/*.pep.xml --decoy-prefix DECOY_ --pout-output T --output-dir crux-output-syn-xml

**Comment by wsnoble** [comment]
My first question is why you are using an old version of Percolator.  Is it possible to use the latest version?

Also, can you send the Percolator log file?

**Comment by wsnoble** [comment]
OK, so this log file says `Final list yields 37061 target peptides with q<0.01.`  Is this the one for which you say you are getting 155 million PSMs? According to the log file, there are only 814914 target PSMs in the file.

**Comment by emmats** [comment]
I've been looking at target.psms file and filtering by q-value to get results. I do the q-value filtering in R : percolator.q.value<0.01
I've attached the file that I'm using.
[percolator.target.peptides.synthetic.txt](https://github.com/crux-toolkit/crux-toolkit/files/12719193/percolator.target.peptides.synthetic.txt)

**Comment by wsnoble** [comment]
Thank you for sending the file, but I'm still confused. Are you saying that you somehow get 155M PSMs from the file you sent?

**Comment by emmats** [comment]
Yes. I filtered based on q-value, divided the file based on file index. When I look at file index 0 only and sum the column "distinct.matches.spectrum" I get 155M PSMs.

**Comment by wsnoble** [comment]
Ah, I understand the problem.  distinct.matches.spectrum is a count of the number of peptides in the database whose masses fall within the precursor mass range.  In other words, it's the number of sequences that were scored by XCorr during the database search. You can find documentation for all the column meanings [here](http://crux.ms/file-formats/txt-format.html).  If you want to count the number of PSMs at q<0.01, just threshold the psm.txt file at 0.01 and count the number of lines.

**Comment by emmats** [comment]
Thanks for clarifying! I'm so glad it was user error and that there isn't anything wrong with percolator.
