### ISSUE TITLE
SERVER GOT HACK TO MAKE GAMBLING ONLINE AND SPAM

### ISSUE THREAD

**Issue by OLIV853** [crux-toolkit/crux-toolkit#678]
![wasiat4d-zy crux ms](https://github.com/crux-toolkit/crux-toolkit/assets/153894964/173645e5-62a1-439d-b1b3-47fdf0af9305)

Hello Sir,

I want to inform that  Your Server site already got hacked to make so many sub domain for gambling online site that's ilegal to do.

You can check in google use this keyword :
slot site:crux.ms

it will display so many this is serveral of the links:
http://wasiat4d-zy.crux.ms/

The button link is direct to gambling online site and only can access use indonesia IP address :
https://vvip.ikantaki.xyz/hoki/
https://idagent138.lol/

Please Remove,Banned also Track the Hacker and make the Hacker go to Jail.

As an Indonesian citizen, I want to emphasize that online gambling is clearly prohibited by Indonesian law. In accordance with Article 27 paragraph (2) of the ITE Law, this act is a prohibited act. Therefore, individuals are prohibited from distributing, transmitting or making accessible gambling content online.

I have attached clear photographic evidence related to this case. My request is that you immediately take the necessary action to delete this sub-domain and online gambling page, or at least suspend access immediately so that online gambling content cannot be accessed. I hope that firm steps will be taken to ensure the integrity of the father's name is maintained and to avoid potential legal problems in the future.

I am grateful for the attention and action taken regarding this matter. I am sure that you will uphold ethics and legal compliance in carrying out your services.

Yours faithfully,

**Comment by CharlesEGrant** [comment]
Thanks for pointing this out. As the other folks you've warned about this have said this was a case of subdomain hacking enabled by incorrect configuration of our DNS record. This should be fixed now and further subdomain hacks should not be possible.
