### ISSUE TITLE
Cannot find sort-by-column in applications.

### ISSUE THREAD

**Issue by DavidMery** [crux-toolkit/crux-toolkit#679]
I am getting an error when trying to run the demo. It says "Cannot find sort-by-column in available applications" when trying to use this command.

$ crux sort-by-column --column-type real --ascending T crux-output/percolator.target.psms.txt "percolator score" > crux-output/percolator.target.psms.sort.txt
Cannot find sort-by-column in available applications
 Usage: crux <command> [options] <argument>

crux supports the following primary commands:

**Comment by bmx8177** [comment]
Hi DavidMery - we removed the sort-by-column command in April 2021 due to low usage. Can you tell us where in the demo you found in this command? I am wondering if we forgot to update documentation somewhere.

**Comment by DavidMery** [comment]
After I downloaded crux, I found tutorials in the crux/doc/tutorials/search that used the sort-by-column command. 

Can you direct me to tutorials that are updated?

Thank you,

**Comment by DavidMery** [comment]
That worked! 

I downloaded the most recent build and that fixed the issue with documentation.
