### ISSUE TITLE
Raise an error on repeated command line arguments

### ISSUE THREAD

**Issue by wsnoble** [crux-toolkit/crux-toolkit#680]
A crux user tried to specify three different types of mods like this:
`--mods-spec K+229.162932 --mods-spec 3M+15.994915 --mods-spec 3STY+79.966331`

This will actually only give you the third modification, because that one clobbers the other two.

We should add a check for repeated command line arguments and issue an error if any are detected.

**Comment by kfattila** [comment]
What exactly should the error message be?

**Comment by kfattila** [comment]
CRUX prints out this info:
```INFO: Total Options in command line: 13
INFO: Default values will be overwritten for:
INFO: ->: decoy-format
INFO: ->: digestion
INFO: ->: max-length
INFO: ->: max-mods
INFO: ->: memory-limit
INFO: ->: min-length
INFO: ->: missed-cleavages
INFO: ->: mods-spec
INFO: ->: nterm-peptide-mods-spec
INFO: ->: output-dir
INFO: ->: overwrite
INFO: ->: peptide-list
INFO: ->: temp-dir
WARNING: The output directory 'param-test/HUMAN_FT_OX_TMT' already exists.
Existing files will be overwritten.
WARNING: The file 'param-test/HUMAN_FT_OX_TMT/tide-index.log.txt' already exists and will be overwritten.
INFO: CPU: L429746
INFO: Crux version: 4.2-33db77c9-2024-04-08
INFO: Пт 12 апр 2024 12:00:16 MSK
INFO: Beginning tide-index.
INFO: Running tide-index...
```

Is this needed? Maybe we can print them in CARP-DEBUG?

**Comment by wsnoble** [comment]
The error should say something like "ERROR: Command line argument foo was repeated."  The program should exit at that point.

Yes, I agree that the INFO message about default values being overwritten can be pushed to CARP-DEBUG.
