### ISSUE TITLE
Tide precursor window calculation discrepancies

### ISSUE THREAD

**Issue by VarunAnanth2003** [crux-toolkit/crux-toolkit#689]
Running a basic `tide-search` on an `.mgf` file with only one spectra showed something in the logs that I believe to be slightly off:

Maximum verbosity log attached below:

> WARNING: Proteowizard parser could not determine scan numbers for this file. Assigning new scan numbers.
DETAILED DEBUG: found scan:1 1 [0-2147483647](tel:02147483647)
DETAILED DEBUG: num of peaks: 92
DEBUG: MS_charge_state
DEBUG: Charge:2
DEBUG: mz:496.2
DETAILED DEBUG: curr_ms1_scan: -1
DETAILED DEBUG: Starting to convert spectrum to pb...
...
INFO: Read 1 spectra.
DEBUG: Maximum observed m/z = 534.319400.
INFO: Starting search.
DETAILED DEBUG: Scan=1 Charge=2 Mass window=[841.827651, 1138.943292]

All other settings (except `precursor-window`), were defaults. I set a very large precursor window of 150,000 to create some edge cases for a Python implementation of digestion and candidate selection for database search. The "maximum observed m/z" figure does not make much sense, as I do not see how this number 534.319400 came to be from a single spectrum `.mgf` with PEPMASS=496.2 and CHARGE=2.

In addition, the tide calculated mass window seems to be off from manual calculations, show below:

> CALCULATING MASS WINDOW:
mz_mass = 496.2
charge = 2
spectrum_mass = charge * (mz_mass - 1.007276466812)
**spectrum_mass = 990.385447**
precursor_window = 150,000 ppm
window_lower_bound = spectrum_mass / (1.0 + (precursor_window / 1000000))
window upper bound = spectrum_mass / (1.0 - (precursor_window / 1000000))
**window_lower_bound = 861.2047365** =/= 841.827651
**window_upper_bound = 1165.159349** =/= 1138.943292

Are these discrepancies related? Any advice would be appreciated. I have also attatched the `.mgf` and `.fasta` required to reproduce these results.

[test_mgf.txt](https://github.com/user-attachments/files/16046248/test_mgf.txt)
[test_fasta.txt](https://github.com/user-attachments/files/16046249/test_fasta.txt)

I have also included the full log file:

[tide-search-log.txt](https://github.com/user-attachments/files/16046255/tide-search-log.txt)

**Comment by kfattila** [comment]
I think tide-search is correct. Try the 3rd option here: https://warwick.ac.uk/fac/sci/chemistry/research/barrow/barrowgroup/calculators/mass_errors/

**Comment by kfattila** [comment]
I do not understand how did you get 1165.159349? 

With using your formula, I have:
990.3854*(1+150000/1000000) = 1138.94321

**Comment by bittremieux** [comment]
The `534.319400` is the m/z of the maximum peak in the spectrum. It doesn't have anything to do with the precursor.

The mass window of `[841, 1138]` is correct based on my manual calculation using `precursor mass - (precursor mass * precursor tolerance / 1e6)`.

Like I mentioned on Slack, I suspect that there's simply a typo in the documentation on the Tide web page.

**Comment by kfattila** [comment]
Ah, I see! Indeed, there is a confusion with multiplication and division.

**Comment by VarunAnanth2003** [comment]
Thanks, this clears things up!

**Comment by VarunAnanth2003** [comment]
With some further testing I wanted to reopen this issue to get some other eyes on what I think may be an issue in how tide calculates the precursor window. I will try to be as clear as possible but please let me know if anything I say here is confusing.

We have the formula for converting neutral mass to m/z. It is as follows:

`m/z = (mass + (charge * PROTON)) / charge`

With `PROTON = 1.00727646677`. Tide uses this constant for Proton mass.

Therefore, to convert from m/z to neutral mass, we have:

`mass = charge * (m/z - PROTON)`

According to @bittremieux , "the isolation window in the mass spec and thus the precursor tolerance operates on m/z values, without knowing or taking the charge into account". From this I gather that in order to calculate a neutral mass window (useful, because you don't need to keep track of the m/z values for all possible charge states for each candidate), you must calculate the window in m/z units and then convert to neutral mass, using the equation above.

As an extension of the previous example I gave:
`precursor m/z = 496.2`
`charge = 2+`
`precursor tolerance (ppm) = 600,000`

I am aware this ppm value is excessively high, but it just makes the discrepancy more obvious.

According to the detailed debug, the neutral mass window calculated by tide is: `[396.154189, 1584.616754]`

However, a manual calculation following what I believe to be the proper steps results in a different figure.
```
lower_mz_bound = 496.2 * (1 - (600,000/1,000,000))
lower_mz_bound = 198.48

upper_mz_bound = 496.2 * (1 + (600,000/1,000,000))
upper_mz_bound = 793.92
```

We now convert this window to neutral mass:

```
lower_neutral_mass_bound = 2 * (198.48 - 1.00727646677)
lower_neutral_mass_bound = 394.95

upper_neutral_mass_bound = 2 * (793.92 - 1.00727646677)
upper_neutral_mass_bound = 1585.83
```

We find a neutral mass window of `[394.95, 1585.83]` which differs from the tide reported `[396.15, 1584.62]`

I believe tide arrived at this figure by converting to neutral mass "earlier". If instead of converting the m/z window bounds into neutral mass bounds at the last step, we convert the reported precursor m/z into neutral mass at the start of our calculations, we get:

```
precursor mass = 2 * (496.2 - 1.00727646677)
precursor mass = 990.385447
```

We now use this calculated mass as the input to the window calculation:

```
lower_neutral_bound = 990.385447 * (1 - (600,000/1,000,000))
lower_neutral_bound = 396.15

upper_neutral_bound = 990.385447 * (1 + (600,000/1,000,000))
upper_neutral_bound = 1584.62
```

By doing this, we recover the tide calculated window of `[396.15, 1584.62]`.

So, which window is correct? The one that keeps things in units of m/z until the very end? Or the one that uses the calculates neutral mass of the spectrum in the calculations? What I have read suggests the former, but tide uses the latter.

**Comment by bittremieux** [comment]
Yes, I think you're correct.

**Comment by kfattila** [comment]
Interesting findings. We adjusted Tide's tolerance window calculation to comet's one. Maybe you should ask Jimmy Eng about this.

**Comment by jke000** [comment]
It's true that Comet calculates its ppm tolerance on the neutral  mass (or rather the singly protonated mass to be explicitly correct) and not on the m/z.  I don't think this discrepancy was ever an issue that I gave any thought to.  Nor has any user brought up the issue over decades, likely because in the ppm magnitude most users typically use, the difference ends up being in the 4th decimal point of the mass bounds.  It does make sense to apply the ppm on the m/z as that's what most researchers think of when they consider instrument mass measurement errors.  I'll make the change in Comet before the its next release.
